import { IAnalyticsEvent } from "@/types/analytics";

export const SEED_ANALYTICS: IAnalyticsEvent[] = [
  {
    id: "EVT-202609-00101",
    eventType: "view",
    businessId: "biz-1",
    businessName: "Bole Medhanialem Pharmacy",
    city: "Addis Ababa",
    country: "Ethiopia",
    device: "mobile",
    browser: "Mobile Safari",
    os: "iOS 18",
    duration: 42,
    registeredBy: "client_telemetry",
    createdAt: new Date("2026-09-07T09:45:00Z"),
  },
  {
    id: "EVT-202609-00102",
    eventType: "search",
    searchTerm: "pharmacy open 24 hours bole",
    city: "Addis Ababa",
    country: "Ethiopia",
    device: "mobile",
    browser: "Chrome Mobile",
    os: "Android 15",
    registeredBy: "client_telemetry",
    createdAt: new Date("2026-09-07T09:30:00Z"),
  },
  {
    id: "EVT-202609-00103",
    eventType: "click_phone",
    businessId: "biz-1",
    businessName: "Bole Medhanialem Pharmacy",
    city: "Addis Ababa",
    country: "Ethiopia",
    device: "mobile",
    browser: "Mobile Safari",
    os: "iOS 18",
    registeredBy: "client_telemetry",
    createdAt: new Date("2026-09-07T09:22:00Z"),
  },
  {
    id: "EVT-202609-00104",
    eventType: "click_direction",
    businessId: "biz-2",
    businessName: "Kategna Traditional Restaurant",
    city: "Addis Ababa",
    country: "Ethiopia",
    device: "mobile",
    browser: "Google Maps / Chrome",
    os: "Android 14",
    registeredBy: "client_telemetry",
    createdAt: new Date("2026-09-07T09:15:00Z"),
  },
  {
    id: "EVT-202609-00105",
    eventType: "view",
    businessId: "biz-2",
    businessName: "Kategna Traditional Restaurant",
    city: "Addis Ababa",
    country: "Ethiopia",
    device: "desktop",
    browser: "Chrome",
    os: "macOS",
    duration: 88,
    registeredBy: "client_telemetry",
    createdAt: new Date("2026-09-07T09:05:00Z"),
  },
  {
    id: "EVT-202609-00106",
    eventType: "search",
    searchTerm: "authentic injera and kitfo",
    city: "Addis Ababa",
    country: "Ethiopia",
    device: "desktop",
    browser: "Firefox",
    os: "Windows 11",
    registeredBy: "client_telemetry",
    createdAt: new Date("2026-09-07T08:55:00Z"),
  },
  {
    id: "EVT-202609-00107",
    eventType: "click_website",
    businessId: "biz-3",
    businessName: "Ethiopian Skylight Hotel",
    city: "Addis Ababa",
    country: "Ethiopia",
    device: "desktop",
    browser: "Edge",
    os: "Windows 11",
    registeredBy: "client_telemetry",
    createdAt: new Date("2026-09-07T08:40:00Z"),
  },
  {
    id: "EVT-202609-00108",
    eventType: "favorite",
    businessId: "biz-3",
    businessName: "Ethiopian Skylight Hotel",
    userId: "user-204",
    userName: "Hanna Girma",
    city: "Addis Ababa",
    country: "Ethiopia",
    device: "mobile",
    browser: "Mobile Safari",
    os: "iOS 18",
    registeredBy: "client_telemetry",
    createdAt: new Date("2026-09-07T08:32:00Z"),
  },
  {
    id: "EVT-202609-00109",
    eventType: "search",
    searchTerm: "luxury hotel near airport",
    city: "Addis Ababa",
    country: "Ethiopia",
    device: "mobile",
    browser: "Chrome Mobile",
    os: "Android 15",
    registeredBy: "client_telemetry",
    createdAt: new Date("2026-09-07T08:20:00Z"),
  },
  {
    id: "EVT-202609-00110",
    eventType: "view",
    businessId: "biz-4",
    businessName: "Tomoca Coffee Piazza",
    city: "Addis Ababa",
    country: "Ethiopia",
    device: "mobile",
    browser: "Chrome Mobile",
    os: "Android 14",
    duration: 55,
    registeredBy: "client_telemetry",
    createdAt: new Date("2026-09-07T08:05:00Z"),
  },
  {
    id: "EVT-202609-00111",
    eventType: "click_direction",
    businessId: "biz-4",
    businessName: "Tomoca Coffee Piazza",
    city: "Addis Ababa",
    country: "Ethiopia",
    device: "mobile",
    browser: "Mobile Safari",
    os: "iOS 17",
    registeredBy: "client_telemetry",
    createdAt: new Date("2026-09-07T07:50:00Z"),
  },
  {
    id: "EVT-202609-00112",
    eventType: "search",
    searchTerm: "best traditional coffee shop",
    city: "Addis Ababa",
    country: "Ethiopia",
    device: "mobile",
    browser: "Mobile Safari",
    os: "iOS 18",
    registeredBy: "client_telemetry",
    createdAt: new Date("2026-09-07T07:42:00Z"),
  },
  {
    id: "EVT-202609-00113",
    eventType: "view",
    businessId: "biz-5",
    businessName: "Kuriftu Resort & Spa Bishoftu",
    city: "Bishoftu",
    country: "Ethiopia",
    device: "desktop",
    browser: "Chrome",
    os: "Windows 11",
    duration: 110,
    registeredBy: "client_telemetry",
    createdAt: new Date("2026-09-07T07:30:00Z"),
  },
  {
    id: "EVT-202609-00114",
    eventType: "click_phone",
    businessId: "biz-5",
    businessName: "Kuriftu Resort & Spa Bishoftu",
    city: "Bishoftu",
    country: "Ethiopia",
    device: "mobile",
    browser: "Chrome Mobile",
    os: "Android 14",
    registeredBy: "client_telemetry",
    createdAt: new Date("2026-09-07T07:15:00Z"),
  },
  {
    id: "EVT-202609-00115",
    eventType: "search",
    searchTerm: "weekend getaway resort with swimming pool",
    city: "Bishoftu",
    country: "Ethiopia",
    device: "desktop",
    browser: "Safari",
    os: "macOS",
    registeredBy: "client_telemetry",
    createdAt: new Date("2026-09-07T06:50:00Z"),
  },
  {
    id: "EVT-202609-00116",
    eventType: "view",
    businessId: "biz-6",
    businessName: "Awash Wine Estate Tasting Room",
    city: "Addis Ababa",
    country: "Ethiopia",
    device: "tablet",
    browser: "Safari",
    os: "iPadOS",
    duration: 62,
    registeredBy: "client_telemetry",
    createdAt: new Date("2026-09-07T06:35:00Z"),
  },
  {
    id: "EVT-202609-00117",
    eventType: "ad_click",
    businessId: "biz-6",
    businessName: "Awash Wine Estate Tasting Room",
    city: "Addis Ababa",
    country: "Ethiopia",
    device: "mobile",
    browser: "Chrome Mobile",
    os: "Android 15",
    metadata: { campaignId: "camp-001", placement: "search_top" },
    registeredBy: "client_telemetry",
    createdAt: new Date("2026-09-07T06:20:00Z"),
  },
  {
    id: "EVT-202609-00118",
    eventType: "click_website",
    businessId: "biz-7",
    businessName: "Yod Abyssinia Cultural Restaurant",
    city: "Addis Ababa",
    country: "Ethiopia",
    device: "desktop",
    browser: "Chrome",
    os: "Windows 11",
    registeredBy: "client_telemetry",
    createdAt: new Date("2026-09-07T05:55:00Z"),
  },
  {
    id: "EVT-202609-00119",
    eventType: "share",
    businessId: "biz-7",
    businessName: "Yod Abyssinia Cultural Restaurant",
    city: "Addis Ababa",
    country: "Ethiopia",
    device: "mobile",
    browser: "Mobile Safari",
    os: "iOS 18",
    registeredBy: "client_telemetry",
    createdAt: new Date("2026-09-07T05:40:00Z"),
  },
  {
    id: "EVT-202609-00120",
    eventType: "view",
    businessId: "biz-7",
    businessName: "Yod Abyssinia Cultural Restaurant",
    city: "Addis Ababa",
    country: "Ethiopia",
    device: "mobile",
    browser: "Chrome Mobile",
    os: "Android 14",
    duration: 75,
    registeredBy: "client_telemetry",
    createdAt: new Date("2026-09-07T05:30:00Z"),
  },
  {
    id: "EVT-202609-00121",
    eventType: "search",
    searchTerm: "cultural dance and dinner show",
    city: "Addis Ababa",
    country: "Ethiopia",
    device: "desktop",
    browser: "Chrome",
    os: "Windows 10",
    registeredBy: "client_telemetry",
    createdAt: new Date("2026-09-07T05:10:00Z"),
  },
  {
    id: "EVT-202609-00122",
    eventType: "click_phone",
    businessId: "biz-8",
    businessName: "Haile Resort Hawassa",
    city: "Hawassa",
    country: "Ethiopia",
    device: "mobile",
    browser: "Mobile Safari",
    os: "iOS 17",
    registeredBy: "client_telemetry",
    createdAt: new Date("2026-09-07T04:45:00Z"),
  },
  {
    id: "EVT-202609-00123",
    eventType: "view",
    businessId: "biz-8",
    businessName: "Haile Resort Hawassa",
    city: "Hawassa",
    country: "Ethiopia",
    device: "desktop",
    browser: "Chrome",
    os: "macOS",
    duration: 94,
    registeredBy: "client_telemetry",
    createdAt: new Date("2026-09-07T04:30:00Z"),
  },
  {
    id: "EVT-202609-00124",
    eventType: "search",
    searchTerm: "lake view hotel hawassa",
    city: "Hawassa",
    country: "Ethiopia",
    device: "mobile",
    browser: "Chrome Mobile",
    os: "Android 14",
    registeredBy: "client_telemetry",
    createdAt: new Date("2026-09-07T04:15:00Z"),
  },
  {
    id: "EVT-202609-00125",
    eventType: "click_direction",
    businessId: "biz-9",
    businessName: "Nairobi Java House Bole",
    city: "Addis Ababa",
    country: "Ethiopia",
    device: "mobile",
    browser: "Mobile Safari",
    os: "iOS 18",
    registeredBy: "client_telemetry",
    createdAt: new Date("2026-09-07T03:50:00Z"),
  },
  {
    id: "EVT-202609-00126",
    eventType: "view",
    businessId: "biz-9",
    businessName: "Nairobi Java House Bole",
    city: "Addis Ababa",
    country: "Ethiopia",
    device: "mobile",
    browser: "Chrome Mobile",
    os: "Android 15",
    duration: 38,
    registeredBy: "client_telemetry",
    createdAt: new Date("2026-09-07T03:30:00Z"),
  },
  {
    id: "EVT-202609-00127",
    eventType: "search",
    searchTerm: "breakfast and breakfast burritos bole",
    city: "Addis Ababa",
    country: "Ethiopia",
    device: "mobile",
    browser: "Mobile Safari",
    os: "iOS 18",
    registeredBy: "client_telemetry",
    createdAt: new Date("2026-09-07T03:10:00Z"),
  },
  {
    id: "EVT-202609-00128",
    eventType: "view",
    businessId: "biz-10",
    businessName: "Ras Amba Hotel",
    city: "Dire Dawa",
    country: "Ethiopia",
    device: "desktop",
    browser: "Edge",
    os: "Windows 11",
    duration: 48,
    registeredBy: "client_telemetry",
    createdAt: new Date("2026-09-07T02:40:00Z"),
  },
  {
    id: "EVT-202609-00129",
    eventType: "click_phone",
    businessId: "biz-10",
    businessName: "Ras Amba Hotel",
    city: "Dire Dawa",
    country: "Ethiopia",
    device: "mobile",
    browser: "Chrome Mobile",
    os: "Android 13",
    registeredBy: "client_telemetry",
    createdAt: new Date("2026-09-07T02:20:00Z"),
  },
  {
    id: "EVT-202609-00130",
    eventType: "search",
    searchTerm: "hotels in dire dawa near train station",
    city: "Dire Dawa",
    country: "Ethiopia",
    device: "mobile",
    browser: "Chrome Mobile",
    os: "Android 14",
    registeredBy: "client_telemetry",
    createdAt: new Date("2026-09-07T02:05:00Z"),
  },
  {
    id: "EVT-202609-00131",
    eventType: "view",
    businessId: "biz-11",
    businessName: "Avanti Blue Nile Hotel",
    city: "Bahir Dar",
    country: "Ethiopia",
    device: "mobile",
    browser: "Mobile Safari",
    os: "iOS 17",
    duration: 68,
    registeredBy: "client_telemetry",
    createdAt: new Date("2026-09-07T01:45:00Z"),
  },
  {
    id: "EVT-202609-00132",
    eventType: "click_direction",
    businessId: "biz-11",
    businessName: "Avanti Blue Nile Hotel",
    city: "Bahir Dar",
    country: "Ethiopia",
    device: "mobile",
    browser: "Chrome Mobile",
    os: "Android 15",
    registeredBy: "client_telemetry",
    createdAt: new Date("2026-09-07T01:25:00Z"),
  },
  {
    id: "EVT-202609-00133",
    eventType: "search",
    searchTerm: "lake tana boat tour booking",
    city: "Bahir Dar",
    country: "Ethiopia",
    device: "desktop",
    browser: "Chrome",
    os: "macOS",
    registeredBy: "client_telemetry",
    createdAt: new Date("2026-09-07T01:10:00Z"),
  },
  {
    id: "EVT-202609-00134",
    eventType: "click_website",
    businessId: "biz-12",
    businessName: "Sankara Hotel Westlands",
    city: "Nairobi",
    country: "Kenya",
    device: "desktop",
    browser: "Firefox",
    os: "Linux",
    registeredBy: "client_telemetry",
    createdAt: new Date("2026-09-07T00:50:00Z"),
  },
  {
    id: "EVT-202609-00135",
    eventType: "view",
    businessId: "biz-12",
    businessName: "Sankara Hotel Westlands",
    city: "Nairobi",
    country: "Kenya",
    device: "mobile",
    browser: "Mobile Safari",
    os: "iOS 18",
    duration: 52,
    registeredBy: "client_telemetry",
    createdAt: new Date("2026-09-07T00:30:00Z"),
  },
  {
    id: "EVT-202609-00136",
    eventType: "search",
    searchTerm: "business meeting venue westlands nairobi",
    city: "Nairobi",
    country: "Kenya",
    device: "desktop",
    browser: "Chrome",
    os: "Windows 11",
    registeredBy: "client_telemetry",
    createdAt: new Date("2026-09-07T00:15:00Z"),
  },
  {
    id: "EVT-202609-00137",
    eventType: "view",
    businessId: "biz-1",
    businessName: "Bole Medhanialem Pharmacy",
    city: "Addis Ababa",
    country: "Ethiopia",
    device: "mobile",
    browser: "Mobile Safari",
    os: "iOS 18",
    duration: 35,
    registeredBy: "client_telemetry",
    createdAt: new Date("2026-09-06T23:50:00Z"),
  },
  {
    id: "EVT-202609-00138",
    eventType: "click_phone",
    businessId: "biz-1",
    businessName: "Bole Medhanialem Pharmacy",
    city: "Addis Ababa",
    country: "Ethiopia",
    device: "mobile",
    browser: "Chrome Mobile",
    os: "Android 14",
    registeredBy: "client_telemetry",
    createdAt: new Date("2026-09-06T23:35:00Z"),
  },
  {
    id: "EVT-202609-00139",
    eventType: "search",
    searchTerm: "emergency dental clinic addis",
    city: "Addis Ababa",
    country: "Ethiopia",
    device: "mobile",
    browser: "Chrome Mobile",
    os: "Android 15",
    registeredBy: "client_telemetry",
    createdAt: new Date("2026-09-06T23:10:00Z"),
  },
  {
    id: "EVT-202609-00140",
    eventType: "view",
    businessId: "biz-2",
    businessName: "Kategna Traditional Restaurant",
    city: "Addis Ababa",
    country: "Ethiopia",
    device: "desktop",
    browser: "Chrome",
    os: "Windows 11",
    duration: 72,
    registeredBy: "client_telemetry",
    createdAt: new Date("2026-09-06T22:45:00Z"),
  },
  {
    id: "EVT-202609-00141",
    eventType: "click_direction",
    businessId: "biz-2",
    businessName: "Kategna Traditional Restaurant",
    city: "Addis Ababa",
    country: "Ethiopia",
    device: "mobile",
    browser: "Mobile Safari",
    os: "iOS 17",
    registeredBy: "client_telemetry",
    createdAt: new Date("2026-09-06T22:20:00Z"),
  },
  {
    id: "EVT-202609-00142",
    eventType: "search",
    searchTerm: "top rated restaurants in bole",
    city: "Addis Ababa",
    country: "Ethiopia",
    device: "mobile",
    browser: "Chrome Mobile",
    os: "Android 14",
    registeredBy: "client_telemetry",
    createdAt: new Date("2026-09-06T21:55:00Z"),
  },
  {
    id: "EVT-202609-00143",
    eventType: "view",
    businessId: "biz-3",
    businessName: "Ethiopian Skylight Hotel",
    city: "Addis Ababa",
    country: "Ethiopia",
    device: "mobile",
    browser: "Mobile Safari",
    os: "iOS 18",
    duration: 85,
    registeredBy: "client_telemetry",
    createdAt: new Date("2026-09-06T21:30:00Z"),
  },
  {
    id: "EVT-202609-00144",
    eventType: "click_phone",
    businessId: "biz-3",
    businessName: "Ethiopian Skylight Hotel",
    city: "Addis Ababa",
    country: "Ethiopia",
    device: "desktop",
    browser: "Edge",
    os: "Windows 11",
    registeredBy: "client_telemetry",
    createdAt: new Date("2026-09-06T21:10:00Z"),
  },
  {
    id: "EVT-202609-00145",
    eventType: "search",
    searchTerm: "conference room rental addis ababa",
    city: "Addis Ababa",
    country: "Ethiopia",
    device: "desktop",
    browser: "Chrome",
    os: "Windows 11",
    registeredBy: "client_telemetry",
    createdAt: new Date("2026-09-06T20:45:00Z"),
  },
  {
    id: "EVT-202609-00146",
    eventType: "view",
    businessId: "biz-4",
    businessName: "Tomoca Coffee Piazza",
    city: "Addis Ababa",
    country: "Ethiopia",
    device: "mobile",
    browser: "Chrome Mobile",
    os: "Android 15",
    duration: 45,
    registeredBy: "client_telemetry",
    createdAt: new Date("2026-09-06T20:20:00Z"),
  },
  {
    id: "EVT-202609-00147",
    eventType: "click_website",
    businessId: "biz-4",
    businessName: "Tomoca Coffee Piazza",
    city: "Addis Ababa",
    country: "Ethiopia",
    device: "desktop",
    browser: "Safari",
    os: "macOS",
    registeredBy: "client_telemetry",
    createdAt: new Date("2026-09-06T19:55:00Z"),
  },
  {
    id: "EVT-202609-00148",
    eventType: "search",
    searchTerm: "roast coffee beans wholesale",
    city: "Addis Ababa",
    country: "Ethiopia",
    device: "desktop",
    browser: "Firefox",
    os: "Windows 10",
    registeredBy: "client_telemetry",
    createdAt: new Date("2026-09-06T19:30:00Z"),
  },
  {
    id: "EVT-202609-00149",
    eventType: "view",
    businessId: "biz-5",
    businessName: "Kuriftu Resort & Spa Bishoftu",
    city: "Bishoftu",
    country: "Ethiopia",
    device: "mobile",
    browser: "Mobile Safari",
    os: "iOS 18",
    duration: 105,
    registeredBy: "client_telemetry",
    createdAt: new Date("2026-09-06T19:05:00Z"),
  },
  {
    id: "EVT-202609-00150",
    eventType: "click_direction",
    businessId: "biz-5",
    businessName: "Kuriftu Resort & Spa Bishoftu",
    city: "Bishoftu",
    country: "Ethiopia",
    device: "mobile",
    browser: "Google Maps",
    os: "Android 14",
    registeredBy: "client_telemetry",
    createdAt: new Date("2026-09-06T18:40:00Z"),
  },
  {
    id: "EVT-202609-00151",
    eventType: "search",
    searchTerm: "spa and massage packages",
    city: "Bishoftu",
    country: "Ethiopia",
    device: "mobile",
    browser: "Mobile Safari",
    os: "iOS 18",
    registeredBy: "client_telemetry",
    createdAt: new Date("2026-09-06T18:15:00Z"),
  },
  {
    id: "EVT-202609-00152",
    eventType: "view",
    businessId: "biz-6",
    businessName: "Awash Wine Estate Tasting Room",
    city: "Addis Ababa",
    country: "Ethiopia",
    device: "desktop",
    browser: "Chrome",
    os: "Windows 11",
    duration: 50,
    registeredBy: "client_telemetry",
    createdAt: new Date("2026-09-06T17:50:00Z"),
  },
  {
    id: "EVT-202609-00153",
    eventType: "click_phone",
    businessId: "biz-6",
    businessName: "Awash Wine Estate Tasting Room",
    city: "Addis Ababa",
    country: "Ethiopia",
    device: "mobile",
    browser: "Chrome Mobile",
    os: "Android 14",
    registeredBy: "client_telemetry",
    createdAt: new Date("2026-09-06T17:25:00Z"),
  },
  {
    id: "EVT-202609-00154",
    eventType: "search",
    searchTerm: "wine tasting tour addis ababa",
    city: "Addis Ababa",
    country: "Ethiopia",
    device: "desktop",
    browser: "Edge",
    os: "Windows 11",
    registeredBy: "client_telemetry",
    createdAt: new Date("2026-09-06T17:00:00Z"),
  },
  {
    id: "EVT-202609-00155",
    eventType: "view",
    businessId: "biz-7",
    businessName: "Yod Abyssinia Cultural Restaurant",
    city: "Addis Ababa",
    country: "Ethiopia",
    device: "mobile",
    browser: "Mobile Safari",
    os: "iOS 17",
    duration: 65,
    registeredBy: "client_telemetry",
    createdAt: new Date("2026-09-06T16:30:00Z"),
  },
  {
    id: "EVT-202609-00156",
    eventType: "click_direction",
    businessId: "biz-7",
    businessName: "Yod Abyssinia Cultural Restaurant",
    city: "Addis Ababa",
    country: "Ethiopia",
    device: "mobile",
    browser: "Chrome Mobile",
    os: "Android 15",
    registeredBy: "client_telemetry",
    createdAt: new Date("2026-09-06T16:05:00Z"),
  },
  {
    id: "EVT-202609-00157",
    eventType: "search",
    searchTerm: "live ethiopian music night club",
    city: "Addis Ababa",
    country: "Ethiopia",
    device: "mobile",
    browser: "Mobile Safari",
    os: "iOS 18",
    registeredBy: "client_telemetry",
    createdAt: new Date("2026-09-06T15:40:00Z"),
  },
  {
    id: "EVT-202609-00158",
    eventType: "view",
    businessId: "biz-8",
    businessName: "Haile Resort Hawassa",
    city: "Hawassa",
    country: "Ethiopia",
    device: "desktop",
    browser: "Chrome",
    os: "macOS",
    duration: 88,
    registeredBy: "client_telemetry",
    createdAt: new Date("2026-09-06T15:10:00Z"),
  },
  {
    id: "EVT-202609-00159",
    eventType: "click_phone",
    businessId: "biz-8",
    businessName: "Haile Resort Hawassa",
    city: "Hawassa",
    country: "Ethiopia",
    device: "mobile",
    browser: "Chrome Mobile",
    os: "Android 14",
    registeredBy: "client_telemetry",
    createdAt: new Date("2026-09-06T14:45:00Z"),
  },
  {
    id: "EVT-202609-00160",
    eventType: "search",
    searchTerm: "family resort hawassa lake",
    city: "Hawassa",
    country: "Ethiopia",
    device: "desktop",
    browser: "Firefox",
    os: "Windows 11",
    registeredBy: "client_telemetry",
    createdAt: new Date("2026-09-06T14:15:00Z"),
  },
  {
    id: "EVT-202609-00161",
    eventType: "view",
    businessId: "biz-9",
    businessName: "Nairobi Java House Bole",
    city: "Addis Ababa",
    country: "Ethiopia",
    device: "mobile",
    browser: "Mobile Safari",
    os: "iOS 18",
    duration: 40,
    registeredBy: "client_telemetry",
    createdAt: new Date("2026-09-06T13:50:00Z"),
  },
  {
    id: "EVT-202609-00162",
    eventType: "click_direction",
    businessId: "biz-9",
    businessName: "Nairobi Java House Bole",
    city: "Addis Ababa",
    country: "Ethiopia",
    device: "mobile",
    browser: "Google Maps",
    os: "Android 14",
    registeredBy: "client_telemetry",
    createdAt: new Date("2026-09-06T13:20:00Z"),
  },
  {
    id: "EVT-202609-00163",
    eventType: "search",
    searchTerm: "coffee shops with high speed wifi bole",
    city: "Addis Ababa",
    country: "Ethiopia",
    device: "mobile",
    browser: "Mobile Safari",
    os: "iOS 18",
    registeredBy: "client_telemetry",
    createdAt: new Date("2026-09-06T12:50:00Z"),
  },
  {
    id: "EVT-202609-00164",
    eventType: "view",
    businessId: "biz-10",
    businessName: "Ras Amba Hotel",
    city: "Dire Dawa",
    country: "Ethiopia",
    device: "desktop",
    browser: "Chrome",
    os: "Windows 11",
    duration: 45,
    registeredBy: "client_telemetry",
    createdAt: new Date("2026-09-06T12:20:00Z"),
  },
  {
    id: "EVT-202609-00165",
    eventType: "click_phone",
    businessId: "biz-10",
    businessName: "Ras Amba Hotel",
    city: "Dire Dawa",
    country: "Ethiopia",
    device: "mobile",
    browser: "Chrome Mobile",
    os: "Android 13",
    registeredBy: "client_telemetry",
    createdAt: new Date("2026-09-06T11:45:00Z"),
  },
];
