import { Business } from "@/types/business";
import { Review } from "@/types/review";

export const SEED_BUSINESSES: Business[] = [
  {
    id: "biz-1",
    name: "Kategna Ethiopian Restaurant",
    slug: "kategna-ethiopian-restaurant-bole",
    ownerId: "user-owner-1",
    categoryId: "cat-dining",
    categoryName: "Food & Dining",
    subcategoryId: "cat-dining-restaurants",
    subcategoryName: "Restaurants",
    subSubcategoryId: "cat-dining-ethiopian",
    subSubcategoryName: "Ethiopian Traditional",
    countryId: "loc-ethiopia",
    countryName: "Ethiopia",
    cityId: "loc-addis-ababa",
    cityName: "Addis Ababa",
    subcityId: "loc-bole",
    districtId: "loc-bole-medhanialem",
    districtName: "Bole Medhanialem",
    addressLine: "Cameroon Street, Next to Edna Mall, Bole Medhanialem",
    street: "Cameroon St",
    building: "Kategna Building, Ground Floor",
    postalCode: "1000",
    latitude: 8.9972,
    longitude: 38.7865,
    telephone: "+251 11 661 5454",
    mobile: "+251 91 123 4567",
    whatsapp: "+251911234567",
    email: "info@kategnarestaurant.com",
    website: "https://kategna.example.com",
    description:
      "Kategna is renowned for serving authentic, gourmet Ethiopian cuisine in an elegant and vibrant atmosphere. Specializing in prime cut tibs, kitfo, fasting combos (Bayenetu), and traditional coffee ceremony roasted fresh on-demand.",
    shortDescription: "Authentic gourmet Ethiopian dining with traditional coffee ceremony.",
    yearEstablished: 2008,
    status: "open",
    isVerified: true,
    isFeatured: true,
    ratingAvg: 4.8,
    reviewCount: 342,
    viewCount: 12450,
    callCount: 890,
    directionCount: 1420,
    logoUrl: "https://images.unsplash.com/photo-1555396273-367ea4eb4db5?auto=format&fit=crop&w=300&q=80",
    coverUrl: "https://images.unsplash.com/photo-1544025162-d76694265947?auto=format&fit=crop&w=1200&q=80",
    youtubeVideoId: "MhQxQ0F3e94",
    media: [
      {
        id: "m-1",
        type: "cover",
        url: "https://images.unsplash.com/photo-1544025162-d76694265947?auto=format&fit=crop&w=1200&q=80",
        title: "Main Dining Hall",
        sortOrder: 1,
        uploadedAt: "2024-01-10",
      },
      {
        id: "m-2",
        type: "interior",
        url: "https://images.unsplash.com/photo-1517248135467-4c7edcad34c4?auto=format&fit=crop&w=800&q=80",
        title: "Traditional Seating Area",
        sortOrder: 2,
        uploadedAt: "2024-01-12",
      },
      {
        id: "m-3",
        type: "menu",
        url: "https://images.unsplash.com/photo-1504674900247-0877df9cc836?auto=format&fit=crop&w=800&q=80",
        title: "Special Mixed Platter",
        sortOrder: 3,
        uploadedAt: "2024-01-15",
      },
    ],
    openingHours: [
      { dayOfWeek: 0, openTime: "07:30", closeTime: "23:00" },
      { dayOfWeek: 1, openTime: "07:30", closeTime: "23:00" },
      { dayOfWeek: 2, openTime: "07:30", closeTime: "23:00" },
      { dayOfWeek: 3, openTime: "07:30", closeTime: "23:00" },
      { dayOfWeek: 4, openTime: "07:30", closeTime: "23:30" },
      { dayOfWeek: 5, openTime: "07:30", closeTime: "23:30" },
      { dayOfWeek: 6, openTime: "07:30", closeTime: "23:30" },
    ],
    attributes: {
      delivery: true,
      takeout: true,
      parking: true,
      wifi: true,
      reservation: true,
      accessible: true,
      acceptsCards: true,
      outdoorSeating: true,
      priceTier: "$$",
    },
    services: [
      { id: "s-1", name: "Special Kitfo Platter", price: "$14.50", description: "Minced lean beef seasoned with spiced butter (niter kibbeh) and mitmita, served with ayib and gomen.", category: "Main Dishes" },
      { id: "s-2", name: "Shekla Tibs", price: "$16.00", description: "Sizzling prime beef cubes sauteed with onions, rosemary, and green chili served in a clay pot.", category: "Main Dishes" },
      { id: "s-3", name: "Full Veggie Bayenetu", price: "$12.00", description: "Array of 8 slow-cooked lentil, split pea, cabbage, and beetroot dishes served over sourdough injera.", category: "Fasting / Vegan" },
    ],
    createdAt: "2024-01-01T00:00:00Z",
    updatedAt: "2024-06-15T00:00:00Z",
  },
  {
    id: "biz-2",
    name: "Medhanialem Care Pharmacy 24/7",
    slug: "medhanialem-care-pharmacy-bole",
    ownerId: "user-owner-2",
    categoryId: "cat-health",
    categoryName: "Health & Medical",
    subcategoryId: "cat-health-pharmacy",
    subcategoryName: "Pharmacies & Drugstores",
    countryId: "loc-ethiopia",
    countryName: "Ethiopia",
    cityId: "loc-addis-ababa",
    cityName: "Addis Ababa",
    subcityId: "loc-bole",
    districtId: "loc-bole-medhanialem",
    districtName: "Bole Medhanialem",
    addressLine: "Bole Road, Opposite Brass Hospital",
    latitude: 8.9985,
    longitude: 38.7882,
    telephone: "+251 11 618 9090",
    mobile: "+251 92 333 4455",
    whatsapp: "+251923334455",
    email: "care@medhanialempharmacy.et",
    description:
      "Fully stocked 24/7 community pharmacy offering certified prescription drugs, diabetic supplies, over-the-counter medications, infant care, and blood pressure monitoring services.",
    shortDescription: "Certified 24/7 dispensary with urgent medication delivery.",
    yearEstablished: 2015,
    status: "open",
    isVerified: true,
    isFeatured: false,
    ratingAvg: 4.9,
    reviewCount: 188,
    viewCount: 8400,
    callCount: 1120,
    directionCount: 950,
    logoUrl: "https://images.unsplash.com/photo-1576602976047-174e57a47881?auto=format&fit=crop&w=300&q=80",
    coverUrl: "https://images.unsplash.com/photo-1587854692152-cbe660dbde88?auto=format&fit=crop&w=1200&q=80",
    media: [
      {
        id: "m-4",
        type: "cover",
        url: "https://images.unsplash.com/photo-1587854692152-cbe660dbde88?auto=format&fit=crop&w=1200&q=80",
        sortOrder: 1,
        uploadedAt: "2024-02-01",
      },
    ],
    openingHours: [
      { dayOfWeek: 0, openTime: "00:00", closeTime: "23:59", is24h: true },
      { dayOfWeek: 1, openTime: "00:00", closeTime: "23:59", is24h: true },
      { dayOfWeek: 2, openTime: "00:00", closeTime: "23:59", is24h: true },
      { dayOfWeek: 3, openTime: "00:00", closeTime: "23:59", is24h: true },
      { dayOfWeek: 4, openTime: "00:00", closeTime: "23:59", is24h: true },
      { dayOfWeek: 5, openTime: "00:00", closeTime: "23:59", is24h: true },
      { dayOfWeek: 6, openTime: "00:00", closeTime: "23:59", is24h: true },
    ],
    attributes: {
      delivery: true,
      parking: true,
      wifi: false,
      accessible: true,
      acceptsCards: true,
      priceTier: "$",
    },
    services: [
      { id: "s-p1", name: "Prescription Refill & Consultation", price: "Free", description: "Licensed pharmacist review of dosage and interactions.", category: "Consultation" },
      { id: "s-p2", name: "Home Emergency Drug Delivery", price: "$3.00", description: "Guaranteed 45-min delivery across Bole & Kazanchis.", category: "Delivery" },
    ],
    createdAt: "2024-02-01T00:00:00Z",
    updatedAt: "2024-06-01T00:00:00Z",
  },
  {
    id: "biz-3",
    name: "SkyLight Grand Hotel & Conference Center",
    slug: "skylight-grand-hotel-addis",
    ownerId: "user-owner-3",
    categoryId: "cat-lodging",
    categoryName: "Hotels & Travel",
    subcategoryId: "cat-lodging-luxury",
    subcategoryName: "Luxury & Business Hotels",
    countryId: "loc-ethiopia",
    countryName: "Ethiopia",
    cityId: "loc-addis-ababa",
    cityName: "Addis Ababa",
    subcityId: "loc-bole",
    districtId: "loc-bole-rwanda",
    districtName: "Bole Rwanda",
    addressLine: "Airport Ring Road, 500m from Bole International Airport",
    latitude: 8.9882,
    longitude: 38.7824,
    telephone: "+251 11 681 8181",
    email: "reservations@skylight.et",
    website: "https://skylight.example.com",
    description:
      "Premier 5-star international hotel located 5 minutes from Bole International Airport. Featuring 1024 luxury suites, 8 signature international restaurants, Olympic-size swimming pool, world-class Thai spa, and convention halls.",
    shortDescription: "5-star luxury suites, grand convention halls, and international dining.",
    yearEstablished: 2019,
    status: "open",
    isVerified: true,
    isFeatured: true,
    ratingAvg: 4.9,
    reviewCount: 512,
    viewCount: 28900,
    callCount: 1400,
    directionCount: 3200,
    logoUrl: "https://images.unsplash.com/photo-1566073771259-6a8506099945?auto=format&fit=crop&w=300&q=80",
    coverUrl: "https://images.unsplash.com/photo-1542314831-068cd1dbfeeb?auto=format&fit=crop&w=1200&q=80",
    youtubeVideoId: "dQw4w9WgXcQ",
    media: [
      {
        id: "m-5",
        type: "cover",
        url: "https://images.unsplash.com/photo-1542314831-068cd1dbfeeb?auto=format&fit=crop&w=1200&q=80",
        sortOrder: 1,
        uploadedAt: "2024-01-05",
      },
      {
        id: "m-6",
        type: "interior",
        url: "https://images.unsplash.com/photo-1582719508461-905c673771fd?auto=format&fit=crop&w=800&q=80",
        sortOrder: 2,
        uploadedAt: "2024-01-05",
      },
    ],
    openingHours: [
      { dayOfWeek: 0, openTime: "00:00", closeTime: "23:59", is24h: true },
      { dayOfWeek: 1, openTime: "00:00", closeTime: "23:59", is24h: true },
      { dayOfWeek: 2, openTime: "00:00", closeTime: "23:59", is24h: true },
      { dayOfWeek: 3, openTime: "00:00", closeTime: "23:59", is24h: true },
      { dayOfWeek: 4, openTime: "00:00", closeTime: "23:59", is24h: true },
      { dayOfWeek: 5, openTime: "00:00", closeTime: "23:59", is24h: true },
      { dayOfWeek: 6, openTime: "00:00", closeTime: "23:59", is24h: true },
    ],
    attributes: {
      parking: true,
      wifi: true,
      reservation: true,
      accessible: true,
      acceptsCards: true,
      airConditioning: true,
      priceTier: "$$$$",
    },
    services: [
      { id: "s-h1", name: "Executive King Suite", price: "$240 / night", description: "Spacious runway-view suite with jacuzzi and club lounge access.", category: "Rooms" },
      { id: "s-h2", name: "Grand Ballroom Rental", price: "Contact for Quote", description: "Capacity up to 2,000 attendees with full audiovisual production.", category: "Events" },
    ],
    createdAt: "2024-01-01T00:00:00Z",
    updatedAt: "2024-06-10T00:00:00Z",
  },
  {
    id: "biz-4",
    name: "Apex Precision Auto Works",
    slug: "apex-precision-auto-works",
    ownerId: "user-owner-4",
    categoryId: "cat-automotive",
    categoryName: "Automotive",
    subcategoryId: "cat-auto-repair",
    subcategoryName: "Auto Repair & Mechanics",
    countryId: "loc-ethiopia",
    countryName: "Ethiopia",
    cityId: "loc-addis-ababa",
    cityName: "Addis Ababa",
    subcityId: "loc-gerji",
    addressLine: "Gerji Mebrat Haile, Behind Total Energy",
    latitude: 8.9892,
    longitude: 38.8095,
    telephone: "+251 11 629 1122",
    mobile: "+251 93 456 7890",
    description:
      "Computerized computerized engine diagnostics, transmission repair, wheel alignment, brake replacement, and genuine OEM auto parts for Toyota, Hyundai, Mercedes, and Ford vehicles.",
    shortDescription: "Certified multi-brand computerized automotive repair and maintenance.",
    yearEstablished: 2012,
    status: "open",
    isVerified: true,
    isFeatured: false,
    ratingAvg: 4.7,
    reviewCount: 96,
    viewCount: 4200,
    callCount: 650,
    directionCount: 780,
    logoUrl: "https://images.unsplash.com/photo-1486006920555-c77dce18193b?auto=format&fit=crop&w=300&q=80",
    coverUrl: "https://images.unsplash.com/photo-1613214149922-f1809c99b414?auto=format&fit=crop&w=1200&q=80",
    media: [
      {
        id: "m-7",
        type: "cover",
        url: "https://images.unsplash.com/photo-1613214149922-f1809c99b414?auto=format&fit=crop&w=1200&q=80",
        sortOrder: 1,
        uploadedAt: "2024-03-01",
      },
    ],
    openingHours: [
      { dayOfWeek: 0, openTime: "", closeTime: "", isClosed: true },
      { dayOfWeek: 1, openTime: "08:00", closeTime: "18:00" },
      { dayOfWeek: 2, openTime: "08:00", closeTime: "18:00" },
      { dayOfWeek: 3, openTime: "08:00", closeTime: "18:00" },
      { dayOfWeek: 4, openTime: "08:00", closeTime: "18:00" },
      { dayOfWeek: 5, openTime: "08:00", closeTime: "18:00" },
      { dayOfWeek: 6, openTime: "08:00", closeTime: "16:00" },
    ],
    attributes: {
      parking: true,
      wifi: true,
      reservation: true,
      accessible: true,
      acceptsCards: true,
      priceTier: "$$",
    },
    services: [
      { id: "s-a1", name: "Computerized OBD2 Diagnostic Scan", price: "$25.00", description: "Full electrical, sensor, and powertrain fault analysis.", category: "Diagnostics" },
      { id: "s-a2", name: "Synthetic Oil Change & Multi-Point Inspection", price: "$65.00", description: "Mobil 1 oil with filter replacement and 30-point safety check.", category: "Maintenance" },
    ],
    createdAt: "2024-03-01T00:00:00Z",
    updatedAt: "2024-06-01T00:00:00Z",
  },
  {
    id: "biz-5",
    name: "TechHub Electronics & Apple Authorized Service",
    slug: "techhub-electronics-bole-atlas",
    ownerId: "user-owner-5",
    categoryId: "cat-shopping",
    categoryName: "Shopping & Retail",
    subcategoryId: "cat-shopping-electronics",
    subcategoryName: "Electronics & Computers",
    countryId: "loc-ethiopia",
    countryName: "Ethiopia",
    cityId: "loc-addis-ababa",
    cityName: "Addis Ababa",
    subcityId: "loc-bole",
    districtId: "loc-bole-atlas",
    districtName: "Bole Atlas",
    addressLine: "Namibia Street, Bole Atlas, 2nd Floor",
    latitude: 9.0068,
    longitude: 38.7818,
    telephone: "+251 11 663 8899",
    mobile: "+251 91 199 0011",
    email: "sales@techhub.et",
    website: "https://techhub.example.com",
    description:
      "Retailer of flagship smartphones, MacBooks, gaming laptops, 4K monitors, audio gear, and genuine accessories. Official certified repair service for Mac, iPhone, and PC.",
    shortDescription: "Latest laptops, smartphones, peripherals, and certified hardware repairs.",
    yearEstablished: 2017,
    status: "open",
    isVerified: true,
    isFeatured: true,
    ratingAvg: 4.6,
    reviewCount: 145,
    viewCount: 9200,
    callCount: 780,
    directionCount: 1100,
    logoUrl: "https://images.unsplash.com/photo-1550745165-9bc0b252726f?auto=format&fit=crop&w=300&q=80",
    coverUrl: "https://images.unsplash.com/photo-1519389950473-47ba0277781c?auto=format&fit=crop&w=1200&q=80",
    media: [
      {
        id: "m-8",
        type: "cover",
        url: "https://images.unsplash.com/photo-1519389950473-47ba0277781c?auto=format&fit=crop&w=1200&q=80",
        sortOrder: 1,
        uploadedAt: "2024-02-15",
      },
    ],
    openingHours: [
      { dayOfWeek: 0, openTime: "10:00", closeTime: "18:00" },
      { dayOfWeek: 1, openTime: "08:30", closeTime: "20:00" },
      { dayOfWeek: 2, openTime: "08:30", closeTime: "20:00" },
      { dayOfWeek: 3, openTime: "08:30", closeTime: "20:00" },
      { dayOfWeek: 4, openTime: "08:30", closeTime: "20:00" },
      { dayOfWeek: 5, openTime: "08:30", closeTime: "20:00" },
      { dayOfWeek: 6, openTime: "08:30", closeTime: "20:00" },
    ],
    attributes: {
      delivery: true,
      parking: true,
      wifi: true,
      accessible: true,
      acceptsCards: true,
      priceTier: "$$$",
    },
    services: [
      { id: "s-t1", name: "MacBook Screen & Battery Replacement", price: "From $120", description: "Original OEM Retina display and high-capacity battery install with 6-month warranty.", category: "Repairs" },
      { id: "s-t2", name: "Custom PC Gaming Rig Assembly", price: "$80", description: "Professional cable management, thermal paste, and stress testing.", category: "Custom Builds" },
    ],
    createdAt: "2024-02-15T00:00:00Z",
    updatedAt: "2024-06-05T00:00:00Z",
  },
  {
    id: "biz-6",
    name: "Tomoca Coffee Roastery & Cafe",
    slug: "tomoca-coffee-roastery-piassa",
    ownerId: "user-owner-6",
    categoryId: "cat-dining",
    categoryName: "Food & Dining",
    subcategoryId: "cat-dining-cafes",
    subcategoryName: "Cafes & Coffee Roasters",
    countryId: "loc-ethiopia",
    countryName: "Ethiopia",
    cityId: "loc-addis-ababa",
    cityName: "Addis Ababa",
    subcityId: "loc-piassa",
    addressLine: "Wavel Street, Piassa Historical Quarter",
    latitude: 9.0345,
    longitude: 38.7512,
    telephone: "+251 11 111 2515",
    website: "https://tomoca.example.com",
    description:
      "Established in 1953, TO.MO.CA is the pioneer coffee roaster in Ethiopia. Serving classic Italian-style espresso, macchiato, and freshly ground Harar and Yirgacheffe coffee beans.",
    shortDescription: "Historic 1953 Italian-Ethiopian espresso bar and premium coffee roaster.",
    yearEstablished: 1953,
    status: "open",
    isVerified: true,
    isFeatured: true,
    ratingAvg: 4.9,
    reviewCount: 680,
    viewCount: 31000,
    callCount: 420,
    directionCount: 2900,
    logoUrl: "https://images.unsplash.com/photo-1514432324607-a09d9b4aefdd?auto=format&fit=crop&w=300&q=80",
    coverUrl: "https://images.unsplash.com/photo-1495474472287-4d71bcdd2085?auto=format&fit=crop&w=1200&q=80",
    media: [
      {
        id: "m-9",
        type: "cover",
        url: "https://images.unsplash.com/photo-1495474472287-4d71bcdd2085?auto=format&fit=crop&w=1200&q=80",
        sortOrder: 1,
        uploadedAt: "2024-01-01",
      },
    ],
    openingHours: [
      { dayOfWeek: 0, openTime: "07:00", closeTime: "20:30" },
      { dayOfWeek: 1, openTime: "06:30", closeTime: "21:00" },
      { dayOfWeek: 2, openTime: "06:30", closeTime: "21:00" },
      { dayOfWeek: 3, openTime: "06:30", closeTime: "21:00" },
      { dayOfWeek: 4, openTime: "06:30", closeTime: "21:00" },
      { dayOfWeek: 5, openTime: "06:30", closeTime: "21:00" },
      { dayOfWeek: 6, openTime: "06:30", closeTime: "21:00" },
    ],
    attributes: {
      takeout: true,
      outdoorSeating: true,
      acceptsCards: true,
      priceTier: "$",
    },
    services: [
      { id: "s-c1", name: "Traditional Double Macchiato", price: "$1.50", description: "Signature rich espresso topped with textured microfoam.", category: "Beverages" },
      { id: "s-c2", name: "Roasted Yirgacheffe Whole Beans (500g)", price: "$12.00", description: "Floral notes with citrus brightness.", category: "Packaged Coffee" },
    ],
    createdAt: "2024-01-01T00:00:00Z",
    updatedAt: "2024-06-01T00:00:00Z",
  },
];

export const SEED_REVIEWS: Review[] = [
  {
    id: "rev-1",
    businessId: "biz-1",
    userId: "user-cust-1",
    userName: "Daniel Tesfaye",
    userAvatar: "https://images.unsplash.com/photo-1535713875002-d1d0cf377fde?auto=format&fit=crop&w=120&q=80",
    rating: 5,
    comment:
      "Absolutely top tier! The kitfo special with ayib and gomen was seasoned to absolute perfection. Service was rapid even on a busy Saturday evening. Highly recommend their traditional coffee roast at the end!",
    photos: [
      "https://images.unsplash.com/photo-1504674900247-0877df9cc836?auto=format&fit=crop&w=500&q=80",
    ],
    likesCount: 19,
    reply: {
      ownerId: "user-owner-1",
      ownerName: "Kategna Management",
      comment: "Thank you so much Daniel! We are honored by your kind words and look forward to welcoming you back soon.",
      createdAt: "2024-04-12T14:30:00Z",
    },
    createdAt: "2024-04-11T19:20:00Z",
  },
  {
    id: "rev-2",
    businessId: "biz-1",
    userId: "user-cust-2",
    userName: "Sarah Jenkins",
    userAvatar: "https://images.unsplash.com/photo-1494790108377-be9c29b29330?auto=format&fit=crop&w=120&q=80",
    rating: 5,
    comment:
      "Visited during my business trip to Addis Ababa. The atmosphere is warm, authentic and welcoming to foreigners. The fasting veggie platter was an explosion of unique flavors.",
    likesCount: 14,
    createdAt: "2024-05-02T20:15:00Z",
  },
  {
    id: "rev-3",
    businessId: "biz-2",
    userId: "user-cust-3",
    userName: "Marta Bekele",
    rating: 5,
    comment:
      "Lifesaver! Needed urgent pediatric fever medicine at 2:30 AM and they had it immediately available with helpful dosage instructions from the on-duty pharmacist.",
    likesCount: 27,
    createdAt: "2024-05-18T03:00:00Z",
  },
  {
    id: "rev-4",
    businessId: "biz-3",
    userId: "user-cust-4",
    userName: "Oliver Smith",
    userAvatar: "https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?auto=format&fit=crop&w=120&q=80",
    rating: 4,
    comment: "State of the art medical facility. Cleanliness is world class and the bilingual medical staff made my checkup effortless.",
    likesCount: 8,
    createdAt: "2024-05-20T10:00:00Z",
  },
  {
    id: "rev-5",
    businessId: "biz-4",
    userId: "user-cust-5",
    userName: "Fatima Al-Mansoor",
    userAvatar: "https://images.unsplash.com/photo-1567532939604-b6b5b0db2604?auto=format&fit=crop&w=120&q=80",
    rating: 5,
    comment: "The contemporary Ethiopian paintings on display are stunning. Purchased two framed originals for our gallery in Dubai.",
    likesCount: 15,
    createdAt: "2024-05-22T14:30:00Z",
  },
  {
    id: "rev-6",
    businessId: "biz-5",
    userId: "user-cust-6",
    userName: "Lucas Tremblay",
    userAvatar: "https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?auto=format&fit=crop&w=120&q=80",
    rating: 5,
    comment: "Breathtaking panoramic views of Addis Ababa from Entoto. The eco-cottages are quiet, cozy, and perfectly managed.",
    likesCount: 22,
    createdAt: "2024-05-25T16:45:00Z",
  },
  {
    id: "rev-7",
    businessId: "biz-1",
    userId: "user-cust-7",
    userName: "Kofi Mensah",
    userAvatar: "https://images.unsplash.com/photo-1522075469751-3a6694fb2f61?auto=format&fit=crop&w=120&q=80",
    rating: 4,
    comment: "Delicious shiro tagamino and fresh injera. Music was lively and authentic. Would gladly dine here every day.",
    likesCount: 9,
    createdAt: "2024-05-28T12:00:00Z",
  },
  {
    id: "rev-8",
    businessId: "biz-kenya-1",
    userId: "user-cust-8",
    userName: "Yordanos Girma",
    userAvatar: "https://images.unsplash.com/photo-1517841905240-472988babdf9?auto=format&fit=crop&w=120&q=80",
    rating: 5,
    comment: "Amazing hand-woven Maasai beaded decor and hardwood carvings in Kilimani. Fast shipping to Addis Ababa.",
    likesCount: 11,
    createdAt: "2024-06-01T11:15:00Z",
  },
  {
    id: "rev-9",
    businessId: "biz-us-1",
    userId: "user-cust-9",
    userName: "Hanna Mekonnen",
    userAvatar: "https://images.unsplash.com/photo-1544005313-94ddf0286df2?auto=format&fit=crop&w=120&q=80",
    rating: 5,
    comment: "Best bespoke East African inspired luxury apparel in Manhattan. High quality fabrics and impeccable tailoring.",
    likesCount: 17,
    createdAt: "2024-06-05T17:30:00Z",
  },
  {
    id: "rev-10",
    businessId: "biz-1",
    userId: "user-cust-10",
    userName: "Berhanu Haile",
    userAvatar: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=120&q=80",
    rating: 4,
    comment: "Great spot for business lunches in Bole. Reliable WiFi, quiet booth seating, and excellent doro wat.",
    likesCount: 6,
    createdAt: "2024-06-08T13:20:00Z",
  },
  {
    id: "rev-11",
    businessId: "biz-2",
    userId: "user-cust-11",
    userName: "Tigist Alemu",
    userAvatar: "https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?auto=format&fit=crop&w=120&q=80",
    rating: 5,
    comment: "Knowledgeable staff and great prices on prescription medicines. Very grateful for their 24/7 service.",
    likesCount: 13,
    createdAt: "2024-06-12T09:40:00Z",
  },
  {
    id: "rev-12",
    businessId: "biz-3",
    userId: "user-cust-12",
    userName: "Michael Kipchoge",
    userAvatar: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&w=120&q=80",
    rating: 5,
    comment: "Modern diagnostic equipment and minimal wait time. Doctor was thorough and kind.",
    likesCount: 7,
    createdAt: "2024-06-15T15:10:00Z",
  },
  {
    id: "rev-13",
    businessId: "biz-4",
    userId: "user-cust-13",
    userName: "Blessing Okafor",
    userAvatar: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=120&q=80",
    rating: 4,
    comment: "Inspiring collection showcasing horn of Africa artists. Curators give fantastic educational tours.",
    likesCount: 10,
    createdAt: "2024-06-18T18:00:00Z",
  },
  {
    id: "rev-14",
    businessId: "biz-5",
    userId: "user-cust-14",
    userName: "Jean-Paul Habimana",
    userAvatar: "https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?auto=format&fit=crop&w=120&q=80",
    rating: 5,
    comment: "Serene mountain retreat. The sunrise over the eucalyptus forest with Ethiopian coffee is unforgettable.",
    likesCount: 20,
    createdAt: "2024-06-22T06:30:00Z",
  },
  {
    id: "rev-15",
    businessId: "biz-1",
    userId: "user-cust-15",
    userName: "Emily Watson",
    userAvatar: "https://images.unsplash.com/photo-1494790108377-be9c29b29330?auto=format&fit=crop&w=120&q=80",
    rating: 5,
    comment: "The tibs combo platter is sensational. Best dining experience we had across our two-week Ethiopian tour!",
    likesCount: 16,
    createdAt: "2024-06-25T20:00:00Z",
  },
  {
    id: "rev-16",
    businessId: "biz-kenya-1",
    userId: "user-cust-16",
    userName: "Liam O'Connor",
    userAvatar: "https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?auto=format&fit=crop&w=120&q=80",
    rating: 4,
    comment: "Authentic Kenyan crafts and ethically sourced wooden tableware. Friendly staff and fair trade verified.",
    likesCount: 8,
    createdAt: "2024-06-28T14:20:00Z",
  },
  {
    id: "rev-17",
    businessId: "biz-2",
    userId: "user-cust-17",
    userName: "Zenebech Desta",
    userAvatar: "https://images.unsplash.com/photo-1573497019940-1c28c88b4f3e?auto=format&fit=crop&w=120&q=80",
    rating: 5,
    comment: "Prompt delivery service directly to my doorstep in Bole. Very reliable pharmacy.",
    likesCount: 12,
    createdAt: "2024-07-01T10:15:00Z",
  },
  {
    id: "rev-18",
    businessId: "biz-3",
    userId: "user-cust-18",
    userName: "Fikru Maru",
    userAvatar: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=120&q=80",
    rating: 4,
    comment: "Professional dental division with gentle hygienists and high standard sterilization.",
    likesCount: 5,
    createdAt: "2024-07-04T11:45:00Z",
  },
  {
    id: "rev-19",
    businessId: "biz-4",
    userId: "user-cust-19",
    userName: "Marta Yohannes",
    userAvatar: "https://images.unsplash.com/photo-1544005313-94ddf0286df2?auto=format&fit=crop&w=120&q=80",
    rating: 5,
    comment: "Exquisite handmade leather accessories and bronze sculptures. A cultural treasure in Addis.",
    likesCount: 14,
    createdAt: "2024-07-08T16:00:00Z",
  },
  {
    id: "rev-20",
    businessId: "biz-5",
    userId: "user-cust-20",
    userName: "Ahmed Hassan",
    userAvatar: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&w=120&q=80",
    rating: 5,
    comment: "Superb hospitality and mountain trekking guides. Our family had a memorable weekend stay.",
    likesCount: 18,
    createdAt: "2024-07-12T18:30:00Z",
  },
  {
    id: "rev-21",
    businessId: "biz-1",
    userId: "user-cust-21",
    userName: "Semhar Tedros",
    userAvatar: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=120&q=80",
    rating: 4,
    comment: "Fresh ingredients, generous portions, and very courteous waitstaff. Always consistent.",
    likesCount: 7,
    createdAt: "2024-07-15T13:00:00Z",
  },
  {
    id: "rev-22",
    businessId: "biz-kenya-1",
    userId: "user-cust-22",
    userName: "David Kimani",
    userAvatar: "https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?auto=format&fit=crop&w=120&q=80",
    rating: 5,
    comment: "Terrific artisan gifts. Found unique carved soapstone sculptures that make great corporate gifts.",
    likesCount: 11,
    createdAt: "2024-07-18T15:20:00Z",
  },
  {
    id: "rev-23",
    businessId: "biz-us-1",
    userId: "user-cust-23",
    userName: "Grace Adebayo",
    userAvatar: "https://images.unsplash.com/photo-1567532939604-b6b5b0db2604?auto=format&fit=crop&w=120&q=80",
    rating: 5,
    comment: "Loved the silk printed scarves and tailored jackets. Received compliments at every gala event.",
    likesCount: 21,
    createdAt: "2024-07-22T19:10:00Z",
  },
  {
    id: "rev-24",
    businessId: "biz-2",
    userId: "user-cust-24",
    userName: "Alexander Fischer",
    userAvatar: "https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?auto=format&fit=crop&w=120&q=80",
    rating: 4,
    comment: "Convenient location near Bole international airport with quick OTC consultation.",
    likesCount: 6,
    createdAt: "2024-07-25T11:00:00Z",
  },
  {
    id: "rev-25",
    businessId: "biz-5",
    userId: "user-cust-25",
    userName: "Almaz Kebede",
    userAvatar: "https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?auto=format&fit=crop&w=120&q=80",
    rating: 5,
    comment: "The campfire evenings under the stars with traditional acoustic Masenqo music were magical.",
    likesCount: 23,
    createdAt: "2024-07-28T21:00:00Z",
  },
];
