import { INotification } from "@/types/notification";

export const SEED_NOTIFICATIONS: INotification[] = [
  {
    id: "notif-001",
    title: "🚨 Urgent: Scheduled Maintenance Window",
    body: "Platform core database cluster upgrade and security kernel patch will take place tonight from 02:00 to 03:30 AM EAT. Directory search will remain read-only.",
    target: "global",
    status: "Delivered",
    priority: "critical",
    sentBy: "Alex Rivera (Super Admin)",
    type: "system",
    link: "/admin",
    readBy: [],
    createdAt: new Date("2026-09-09T09:30:00Z"),
  },
  {
    id: "notif-002",
    title: "🎉 Business Verification Approved: Abyssinia Gourmet Cafe",
    body: "Congratulations! Your municipal trade license and TIN certification have been verified. The official verified badge is now active on your public profile.",
    target: "business",
    targetBusinessId: "biz-1",
    status: "Delivered",
    priority: "high",
    sentBy: "Verification Desk",
    type: "verification",
    link: "/business/abyssinia-gourmet-cafe",
    readBy: [],
    createdAt: new Date("2026-09-09T08:15:00Z"),
  },
  {
    id: "notif-003",
    title: "💰 Telebirr Settlement Confirmed (1,499 ETB)",
    body: "Monthly Pro Tier Business Subscription renewal payment via Telebirr SuperApp has been successfully settled and booked to your ledger balance.",
    target: "business",
    targetBusinessId: "biz-1",
    status: "Delivered",
    priority: "medium",
    sentBy: "Telebirr Gateway",
    type: "payment",
    link: "/dashboard",
    readBy: ["user_admin_01"],
    createdAt: new Date("2026-09-08T18:40:00Z"),
  },
  {
    id: "notif-004",
    title: "⭐ New 5-Star Customer Review on Bole Branch",
    body: "Helen T. left a verified 5-star review: 'Best traditional macchiato in Bole! Wonderful customer hospitality and ultra-fast Wi-Fi.'",
    target: "business",
    targetBusinessId: "biz-1",
    status: "Delivered",
    priority: "medium",
    sentBy: "Customer Feedback Engine",
    type: "review",
    link: "/dashboard",
    readBy: [],
    createdAt: new Date("2026-09-08T15:20:00Z"),
  },
  {
    id: "notif-005",
    title: "🛡️ Suspicious Login Attempt Blocked",
    body: "An anomalous login attempt from an unrecognized IP address in Frankfurt (IP: 185.220.101.4) was intercepted and challenged with 2-Factor Authentication.",
    target: "user",
    status: "Delivered",
    priority: "critical",
    sentBy: "Security Shield",
    type: "security",
    readBy: [],
    createdAt: new Date("2026-09-08T12:10:00Z"),
  },
  {
    id: "notif-006",
    title: "🚀 New Feature: 360° Virtual Tour & Real-Time Open/Closed Engine",
    body: "Listing profiles now support 360-degree panoramic media uploads and automatic live opening hour status badges with prayer/holiday schedule overrides.",
    target: "global",
    status: "Delivered",
    priority: "low",
    sentBy: "Product Engineering",
    type: "broadcast",
    link: "/dashboard",
    readBy: ["user_admin_01"],
    createdAt: new Date("2026-09-07T16:00:00Z"),
  },
  {
    id: "notif-007",
    title: "⚖️ Dispute Case Opened: Duplicate Listing Infringement",
    body: "Administrative case #REP-2026-004 has been registered regarding unverified duplicate location claim on Kazanchis Street. Compliance triage is underway.",
    target: "admin",
    status: "Delivered",
    priority: "high",
    sentBy: "Trust & Safety Team",
    type: "dispute",
    link: "/admin",
    readBy: [],
    createdAt: new Date("2026-09-07T11:45:00Z"),
  },
  {
    id: "notif-008",
    title: "📢 Meskel Holiday Business Promotion Festival Live",
    body: "Join over 450 participating retailers across Addis Ababa and Hawassa offering exclusive festive discounts. Featured search placements now 30% off.",
    target: "business",
    status: "Delivered",
    priority: "medium",
    sentBy: "Marketing Partnerships",
    type: "promo",
    link: "/dashboard",
    readBy: [],
    createdAt: new Date("2026-09-06T14:30:00Z"),
  },
  {
    id: "notif-009",
    title: "📍 Geo-Admin Territorial Jurisdiction Assigned",
    body: "You have been assigned administrative oversight for Hawassa City Region, covering 12 sub-districts and municipal trade directory compliance.",
    target: "admin",
    status: "Delivered",
    priority: "high",
    sentBy: "Alex Rivera (Super Admin)",
    type: "system",
    link: "/admin",
    readBy: ["user_admin_01"],
    createdAt: new Date("2026-09-06T09:00:00Z"),
  },
  {
    id: "notif-010",
    title: "💳 CBE Birr Direct QR Payout Settled (3,850 ETB)",
    body: "Commercial Bank of Ethiopia (CBE Birr) settlement for weekly table reservations and voucher redemption has been transferred to account ending in 4102.",
    target: "business",
    targetBusinessId: "biz-1",
    status: "Delivered",
    priority: "medium",
    sentBy: "CBE Clearing Hub",
    type: "payment",
    link: "/dashboard",
    readBy: [],
    createdAt: new Date("2026-09-05T17:15:00Z"),
  },
  {
    id: "notif-011",
    title: "📋 Document Expiry Notice: Food Hygiene Certificate",
    body: "Your municipal sanitation compliance certificate will expire in 14 days. Please upload renewed documentation via your dashboard to avoid verification suspension.",
    target: "business",
    targetBusinessId: "biz-2",
    status: "Delivered",
    priority: "high",
    sentBy: "Compliance Audit Desk",
    type: "verification",
    link: "/dashboard",
    readBy: [],
    createdAt: new Date("2026-09-05T10:00:00Z"),
  },
  {
    id: "notif-012",
    title: "💬 New Customer In-App Inquiry Received",
    body: "Samuel Worku sent an inquiry regarding private banquet hall rental for 50 people on Saturday evening. Check messages to respond within SLA.",
    target: "business",
    targetBusinessId: "biz-1",
    status: "Delivered",
    priority: "medium",
    sentBy: "Lead Messaging Hub",
    type: "review",
    link: "/dashboard",
    readBy: ["user_admin_01"],
    createdAt: new Date("2026-09-04T13:40:00Z"),
  },
  {
    id: "notif-013",
    title: "🛡️ Automated Spam Review Defense Triggered",
    body: "6 duplicate negative reviews originating from a single VPN subnet were flagged and placed in quarantine pending manual moderator inspection.",
    target: "admin",
    status: "Delivered",
    priority: "high",
    sentBy: "Automated Fraud Shield",
    type: "security",
    link: "/admin",
    readBy: [],
    createdAt: new Date("2026-09-04T08:25:00Z"),
  },
  {
    id: "notif-014",
    title: "🌟 Congratulations on Reaching 10,000 Profile Views!",
    body: "Your business listing reached a major milestone this month with over 10,000 unique local customer impressions across directory search.",
    target: "business",
    targetBusinessId: "biz-1",
    status: "Delivered",
    priority: "low",
    sentBy: "BizFinder Insights",
    type: "broadcast",
    link: "/dashboard",
    readBy: ["user_admin_01"],
    createdAt: new Date("2026-09-03T16:50:00Z"),
  },
  {
    id: "notif-015",
    title: "🔔 Platform Terms of Service & Privacy Policy Updated",
    body: "We have updated our Data Privacy & Cookie Governance Framework in compliance with national digital commerce regulations. Review the summary of changes.",
    target: "global",
    status: "Delivered",
    priority: "low",
    sentBy: "Legal & Compliance",
    type: "system",
    link: "/terms",
    readBy: [],
    createdAt: new Date("2026-09-03T11:00:00Z"),
  },
  {
    id: "notif-016",
    title: "⚡ Search Rank Boost Activated: Top Placement Live",
    body: "Your sponsored search ad campaign 'Weekend Coffee Spotlight' has been activated and is now serving top-of-search banners in Bole and Kazanchis.",
    target: "business",
    targetBusinessId: "biz-1",
    status: "Delivered",
    priority: "medium",
    sentBy: "Ad Engine",
    type: "promo",
    link: "/dashboard",
    readBy: [],
    createdAt: new Date("2026-09-02T14:15:00Z"),
  },
  {
    id: "notif-017",
    title: "⚠️ Unresolved Support Escalation: SLA Warning",
    body: "Support Ticket #1001 (Listing verification appeal) has exceeded the standard 24-hour response target. Reassigned to Senior Admin Marcus Vance.",
    target: "admin",
    status: "Delivered",
    priority: "critical",
    sentBy: "Helpdesk SLA Monitor",
    type: "dispute",
    link: "/admin",
    readBy: [],
    createdAt: new Date("2026-09-02T09:30:00Z"),
  },
  {
    id: "notif-018",
    title: "💳 Chapa Payment Gateway Settlement (850 ETB)",
    body: "Instant checkout transaction via Chapa multi-bank rail has settled successfully. Invoice receipt #INV-2026-081 is generated and downloadable.",
    target: "business",
    targetBusinessId: "biz-1",
    status: "Delivered",
    priority: "medium",
    sentBy: "Chapa Payment Gateway",
    type: "payment",
    link: "/dashboard",
    readBy: ["user_admin_01"],
    createdAt: new Date("2026-09-01T15:10:00Z"),
  },
  {
    id: "notif-019",
    title: "📱 New Mobile App Update Available (v2.4.0)",
    body: "A new version of BizFinder for Android and iOS is now available on Google Play & App Store with offline bookmarks and turn-by-turn map navigation.",
    target: "global",
    status: "Delivered",
    priority: "low",
    sentBy: "Mobile Release Team",
    type: "system",
    readBy: [],
    createdAt: new Date("2026-09-01T10:00:00Z"),
  },
  {
    id: "notif-020",
    title: "🏢 Business Claim Verified: Kuriftu Resort & Spa Bishoftu",
    body: "Owner identity credentials and official corporate email verification have been authenticated. Administrative controls transferred to verified management.",
    target: "admin",
    status: "Delivered",
    priority: "high",
    sentBy: "Claims Verification Bureau",
    type: "verification",
    link: "/admin",
    readBy: [],
    createdAt: new Date("2026-08-31T17:20:00Z"),
  },
  {
    id: "notif-021",
    title: "⭐ Customer Feedback Milestone: 4.8 Star Aggregate",
    body: "Your profile has maintained a 4.8 average star rating across 45 verified reviews. You are now eligible for the 'Top Rated Business 2026' badge.",
    target: "business",
    targetBusinessId: "biz-1",
    status: "Delivered",
    priority: "medium",
    sentBy: "Merchant Growth Desk",
    type: "review",
    link: "/dashboard",
    readBy: [],
    createdAt: new Date("2026-08-30T11:45:00Z"),
  },
  {
    id: "notif-022",
    title: "🔒 Mandatory Two-Factor Authentication for Administrators",
    body: "In accordance with updated security compliance guidelines, 2FA enforcement is now mandatory for all Country and City Administrator accounts.",
    target: "admin",
    status: "Delivered",
    priority: "critical",
    sentBy: "Chief Information Security Officer",
    type: "security",
    link: "/admin",
    readBy: ["user_admin_01"],
    createdAt: new Date("2026-08-29T14:00:00Z"),
  },
  {
    id: "notif-023",
    title: "🌍 Regional Expansion: 15 New Cities Indexed",
    body: "BizFinder directory coverage has officially expanded into Bahir Dar, Gondar, Mekelle, and Dire Dawa with over 1,200 newly indexed municipal businesses.",
    target: "global",
    status: "Delivered",
    priority: "low",
    sentBy: "Ecosystem Operations",
    type: "broadcast",
    link: "/search",
    readBy: [],
    createdAt: new Date("2026-08-28T09:15:00Z"),
  },
  {
    id: "notif-024",
    title: "💳 International Card Settlement ($120 USD)",
    body: "Annual Pro Directory Listing subscription paid via Visa card (Stripe Gateway) has settled. Payout converted and booked to your currency ledger.",
    target: "business",
    targetBusinessId: "biz-1",
    status: "Delivered",
    priority: "medium",
    sentBy: "Stripe International",
    type: "payment",
    link: "/dashboard",
    readBy: [],
    createdAt: new Date("2026-08-27T16:30:00Z"),
  },
  {
    id: "notif-025",
    title: "🚨 Copyright Infringement Notice: Image Removal Required",
    body: "A takedown request was submitted regarding an uncredited promotional photograph on Listing #biz-8. Moderator review has temporarily hidden the asset.",
    target: "admin",
    status: "Delivered",
    priority: "high",
    sentBy: "Copyright & IP Agent",
    type: "dispute",
    link: "/admin",
    readBy: [],
    createdAt: new Date("2026-08-26T13:00:00Z"),
  },
  {
    id: "notif-026",
    title: "✨ Welcome to BizFinder Directory Ecosystem!",
    body: "Thank you for joining Ethiopia's premier verified business discovery and lead generation network. Explore verified local services and bookmark favorites.",
    target: "global",
    status: "Delivered",
    priority: "low",
    sentBy: "BizFinder Community",
    type: "broadcast",
    link: "/",
    readBy: ["user_admin_01"],
    createdAt: new Date("2026-08-25T10:00:00Z"),
  },
];
