import { IPayment } from "@/types/payment";

export const SEED_PAYMENTS: IPayment[] = [
  {
    id: "TX-TEL-901842",
    businessId: "biz-1",
    businessName: "Kategna Ethiopian Restaurant",
    countryName: "Ethiopia",
    cityName: "Addis Ababa",
    payerName: "Kassahun Tadesse",
    payerEmail: "kassahun@kategna.et",
    payerPhone: "+251911223344",
    amount: 1499,
    currency: "ETB",
    provider: "telebirr",
    paymentType: "subscription",
    status: "completed",
    reference: "TB-20260907-88219",
    description: "Business Pro Tier Monthly Subscription - Bole Branch",
    registeredBy: "Alex Rivera (Super Admin)",
    createdAt: new Date("2026-09-07T08:30:00Z").toISOString(),
    updatedAt: new Date("2026-09-07T08:30:00Z").toISOString(),
  },
  {
    id: "TX-CBE-894102",
    businessId: "biz-2",
    businessName: "Lucy Lounge & Restaurant",
    countryName: "Ethiopia",
    cityName: "Addis Ababa",
    payerName: "Sara Mengistu",
    payerEmail: "sara@lucylounge.com",
    payerPhone: "+251922334455",
    amount: 3200,
    currency: "ETB",
    provider: "cbebirr",
    paymentType: "advertisement",
    status: "completed",
    reference: "CBE-TX-9932014",
    description: "Top Banner 14-Day Sponsored Placement (Addis Ababa Dining)",
    registeredBy: "Marcus Vance (Admin)",
    createdAt: new Date("2026-09-07T06:15:00Z").toISOString(),
    updatedAt: new Date("2026-09-07T06:15:00Z").toISOString(),
  },
  {
    id: "TX-STR-772190",
    businessId: "biz-3",
    businessName: "Hyatt Regency Addis Ababa",
    countryName: "Ethiopia",
    cityName: "Addis Ababa",
    payerName: "Michael Solomon",
    payerEmail: "billing@hyattaddis.com",
    payerPhone: "+251911556677",
    amount: 199,
    currency: "USD",
    provider: "card",
    paymentType: "subscription",
    status: "completed",
    reference: "ch_3N8201xX982Lko",
    description: "Enterprise Multi-Location Corporate Plan (Annual)",
    registeredBy: "Alex Rivera (Super Admin)",
    createdAt: new Date("2026-09-06T18:45:00Z").toISOString(),
    updatedAt: new Date("2026-09-06T18:45:00Z").toISOString(),
  },
  {
    id: "TX-MPE-651094",
    businessId: "biz-4",
    businessName: "Carnivore Restaurant & Bar",
    countryName: "Kenya",
    cityName: "Nairobi",
    payerName: "David Ochieng",
    payerEmail: "accounts@carnivore.co.ke",
    payerPhone: "+254712345678",
    amount: 4500,
    currency: "ETB",
    provider: "mpesa",
    paymentType: "featured_listing",
    status: "completed",
    reference: "QA88219901M",
    description: "Spotlight Pin & Priority Search Index for Nairobi Visitors",
    registeredBy: "system",
    createdAt: new Date("2026-09-06T14:20:00Z").toISOString(),
    updatedAt: new Date("2026-09-06T14:20:00Z").toISOString(),
  },
  {
    id: "TX-CHP-549102",
    businessId: "biz-5",
    businessName: "Kuriftu Resort & Spa Bishoftu",
    countryName: "Ethiopia",
    cityName: "Bishoftu",
    payerName: "Tadios Getachew",
    payerEmail: "tadios@kurifturesorts.com",
    payerPhone: "+251911440011",
    amount: 8500,
    currency: "ETB",
    provider: "chapa",
    paymentType: "advertisement",
    status: "completed",
    reference: "CHP-REF-8831002",
    description: "Weekend Getaways Featured Carousel Campaign",
    registeredBy: "system",
    createdAt: new Date("2026-09-06T10:00:00Z").toISOString(),
    updatedAt: new Date("2026-09-06T10:00:00Z").toISOString(),
  },
  {
    id: "TX-BNK-441209",
    businessId: "biz-6",
    businessName: "Abyssinia Specialty Coffee",
    countryName: "Ethiopia",
    cityName: "Addis Ababa",
    payerName: "Abebe Bikila",
    payerEmail: "abebe@abyssiniacoffee.et",
    payerPhone: "+251911778899",
    amount: 1500,
    currency: "ETB",
    provider: "bank_transfer",
    paymentType: "verification",
    status: "pending",
    reference: "CBE-DEP-4019284",
    description: "Official Business Verification Badge & Audit Certificate",
    registeredBy: "Marcus Vance (Admin)",
    createdAt: new Date("2026-09-05T16:10:00Z").toISOString(),
    updatedAt: new Date("2026-09-05T16:10:00Z").toISOString(),
  },
  {
    id: "TX-TEL-330198",
    businessId: "biz-7",
    businessName: "Bole Rock Wellness & Fitness",
    countryName: "Ethiopia",
    cityName: "Addis Ababa",
    payerName: "Hanna Girma",
    payerEmail: "hanna@bolerock.et",
    payerPhone: "+251912334455",
    amount: 1499,
    currency: "ETB",
    provider: "telebirr",
    paymentType: "subscription",
    status: "completed",
    reference: "TB-20260905-11928",
    description: "Pro Tier Monthly Auto-Renewal",
    registeredBy: "system",
    createdAt: new Date("2026-09-05T12:00:00Z").toISOString(),
    updatedAt: new Date("2026-09-05T12:00:00Z").toISOString(),
  },
  {
    id: "TX-CBE-229104",
    businessId: "biz-8",
    businessName: "Tomoca Coffee Kazanchis",
    countryName: "Ethiopia",
    cityName: "Addis Ababa",
    payerName: "Wondwossen Mesfin",
    payerEmail: "accounts@tomoca.et",
    payerPhone: "+251911990011",
    amount: 2800,
    currency: "ETB",
    provider: "cbebirr",
    paymentType: "advertisement",
    status: "completed",
    reference: "CBE-TX-4401923",
    description: "Coffee Shops Category Sponsored Ad & Social Boost",
    registeredBy: "system",
    createdAt: new Date("2026-09-04T15:30:00Z").toISOString(),
    updatedAt: new Date("2026-09-04T15:30:00Z").toISOString(),
  },
  {
    id: "TX-CSH-118273",
    businessId: "biz-9",
    businessName: "Merkato Wholesale Spices",
    countryName: "Ethiopia",
    cityName: "Addis Ababa",
    payerName: "Jemal Kedir",
    payerPhone: "+251933445566",
    amount: 2000,
    currency: "ETB",
    provider: "cash",
    paymentType: "verification",
    status: "completed",
    reference: "RCPT-OFFICE-8812",
    description: "Cash Receipt at Head Office - Physical Store Verification",
    registeredBy: "Marcus Vance (Admin)",
    createdAt: new Date("2026-09-04T11:20:00Z").toISOString(),
    updatedAt: new Date("2026-09-04T11:20:00Z").toISOString(),
  },
  {
    id: "TX-TEL-009182",
    businessId: "biz-10",
    businessName: "Sabahar Artisan Textiles",
    countryName: "Ethiopia",
    cityName: "Addis Ababa",
    payerName: "Judy Frater",
    payerEmail: "info@sabahar.com",
    payerPhone: "+251911667788",
    amount: 3500,
    currency: "ETB",
    provider: "telebirr",
    paymentType: "featured_listing",
    status: "completed",
    reference: "TB-20260904-77291",
    description: "Handicrafts & Souvenirs Top Featured Spot",
    registeredBy: "system",
    createdAt: new Date("2026-09-04T09:40:00Z").toISOString(),
    updatedAt: new Date("2026-09-04T09:40:00Z").toISOString(),
  },
  {
    id: "TX-STR-991823",
    businessId: "biz-11",
    businessName: "Sheraton Addis Luxury Hotel",
    countryName: "Ethiopia",
    cityName: "Addis Ababa",
    payerName: "Elena Rostova",
    payerEmail: "billing@sheratonaddis.com",
    amount: 350,
    currency: "USD",
    provider: "card",
    paymentType: "advertisement",
    status: "completed",
    reference: "ch_9X10992Lz11A",
    description: "Luxury Stays Global Search Ad Banner (30 Days)",
    registeredBy: "Alex Rivera (Super Admin)",
    createdAt: new Date("2026-09-03T17:15:00Z").toISOString(),
    updatedAt: new Date("2026-09-03T17:15:00Z").toISOString(),
  },
  {
    id: "TX-TEL-882719",
    businessId: "biz-12",
    businessName: "Yod Abyssinia Cultural Restaurant",
    countryName: "Ethiopia",
    cityName: "Addis Ababa",
    payerName: "Dawit Kebede",
    payerEmail: "dawit@yodabyssinia.et",
    payerPhone: "+251911335577",
    amount: 1499,
    currency: "ETB",
    provider: "telebirr",
    paymentType: "subscription",
    status: "completed",
    reference: "TB-20260903-55102",
    description: "Pro Tier Monthly Plan",
    registeredBy: "system",
    createdAt: new Date("2026-09-03T13:00:00Z").toISOString(),
    updatedAt: new Date("2026-09-03T13:00:00Z").toISOString(),
  },
  {
    id: "TX-CBE-771920",
    businessId: "biz-13",
    businessName: "Haile Resort Hawassa Lakefront",
    countryName: "Ethiopia",
    cityName: "Hawassa",
    payerName: "Haile Hospitality Group",
    payerEmail: "accounts@hailehotels.et",
    payerPhone: "+251911880022",
    amount: 6000,
    currency: "ETB",
    provider: "cbebirr",
    paymentType: "featured_listing",
    status: "completed",
    reference: "CBE-TX-3391024",
    description: "Hotels & Lodging Top Tier Pin & Priority Placement in Hawassa",
    registeredBy: "Marcus Vance (Admin)",
    createdAt: new Date("2026-09-02T16:45:00Z").toISOString(),
    updatedAt: new Date("2026-09-02T16:45:00Z").toISOString(),
  },
  {
    id: "TX-MPE-660192",
    businessId: "biz-14",
    businessName: "Nairobi Java House (Addis)",
    countryName: "Kenya",
    cityName: "Nairobi",
    payerName: "Kevin Mwangi",
    payerEmail: "kevin@javahouseafrica.com",
    payerPhone: "+254722998877",
    amount: 1499,
    currency: "ETB",
    provider: "mpesa",
    paymentType: "subscription",
    status: "completed",
    reference: "QK99210492P",
    description: "Monthly Pro Subscription",
    registeredBy: "system",
    createdAt: new Date("2026-09-02T11:10:00Z").toISOString(),
    updatedAt: new Date("2026-09-02T11:10:00Z").toISOString(),
  },
  {
    id: "TX-CHP-552019",
    businessId: "biz-15",
    businessName: "Castelli Italian Restaurant",
    countryName: "Ethiopia",
    cityName: "Addis Ababa",
    payerName: "Paolo Castelli",
    payerEmail: "info@castelliet.com",
    payerPhone: "+251911443322",
    amount: 2500,
    currency: "ETB",
    provider: "chapa",
    paymentType: "advertisement",
    status: "completed",
    reference: "CHP-TX-229104",
    description: "Fine Dining Piazza Spotlight Ad",
    registeredBy: "system",
    createdAt: new Date("2026-09-01T15:20:00Z").toISOString(),
    updatedAt: new Date("2026-09-01T15:20:00Z").toISOString(),
  },
  {
    id: "TX-TEL-441092",
    businessId: "biz-16",
    businessName: "Entoto Park Adventure Center",
    countryName: "Ethiopia",
    cityName: "Addis Ababa",
    payerName: "Selamawit Bekele",
    payerEmail: "selam@entotopark.et",
    payerPhone: "+251912998877",
    amount: 4000,
    currency: "ETB",
    provider: "telebirr",
    paymentType: "advertisement",
    status: "completed",
    reference: "TB-20260901-44019",
    description: "Outdoor & Recreation Featured Banner",
    registeredBy: "system",
    createdAt: new Date("2026-09-01T09:30:00Z").toISOString(),
    updatedAt: new Date("2026-09-01T09:30:00Z").toISOString(),
  },
  {
    id: "TX-BNK-330918",
    businessId: "biz-17",
    businessName: "Ethio Telecom Flagship Churchill",
    countryName: "Ethiopia",
    cityName: "Addis Ababa",
    payerName: "Samuel Tefera",
    payerEmail: "samuel.t@ethiotelecom.et",
    payerPhone: "+251911001122",
    amount: 12000,
    currency: "ETB",
    provider: "bank_transfer",
    paymentType: "subscription",
    status: "completed",
    reference: "CBE-WIRE-9921004",
    description: "Annual Corporate Directory Listing (Multiple Outlets)",
    registeredBy: "Alex Rivera (Super Admin)",
    createdAt: new Date("2026-08-31T14:15:00Z").toISOString(),
    updatedAt: new Date("2026-08-31T14:15:00Z").toISOString(),
  },
  {
    id: "TX-STR-229018",
    businessId: "biz-18",
    businessName: "Radisson Blu Hotel Addis Ababa",
    countryName: "Ethiopia",
    cityName: "Addis Ababa",
    payerName: "Henok Wolde",
    payerEmail: "henok@radissonblu.com",
    amount: 199,
    currency: "USD",
    provider: "card",
    paymentType: "subscription",
    status: "completed",
    reference: "ch_22904811aZ",
    description: "Monthly Pro Tier Subscription",
    registeredBy: "system",
    createdAt: new Date("2026-08-30T16:50:00Z").toISOString(),
    updatedAt: new Date("2026-08-30T16:50:00Z").toISOString(),
  },
  {
    id: "TX-TEL-118290",
    businessId: "biz-19",
    businessName: "Mafi City Center Mall",
    countryName: "Ethiopia",
    cityName: "Addis Ababa",
    payerName: "Mesfin Solomon",
    payerEmail: "mesfin@maficity.com",
    payerPhone: "+251911554433",
    amount: 5000,
    currency: "ETB",
    provider: "telebirr",
    paymentType: "featured_listing",
    status: "completed",
    reference: "TB-20260830-22104",
    description: "Shopping Malls Priority Spotlight",
    registeredBy: "system",
    createdAt: new Date("2026-08-30T10:15:00Z").toISOString(),
    updatedAt: new Date("2026-08-30T10:15:00Z").toISOString(),
  },
  {
    id: "TX-CBE-007192",
    businessId: "biz-20",
    businessName: "Bati Traditional Cuisine",
    countryName: "Ethiopia",
    cityName: "Dire Dawa",
    payerName: "Tirhas Hagos",
    payerEmail: "tirhas@bati.et",
    payerPhone: "+251922446688",
    amount: 1499,
    currency: "ETB",
    provider: "cbebirr",
    paymentType: "subscription",
    status: "completed",
    reference: "CBE-TX-1182944",
    description: "Pro Tier Monthly Plan - Dire Dawa Central",
    registeredBy: "system",
    createdAt: new Date("2026-08-29T14:00:00Z").toISOString(),
    updatedAt: new Date("2026-08-29T14:00:00Z").toISOString(),
  },
  {
    id: "TX-TEL-996501",
    businessId: "biz-21",
    businessName: "Skylight Hotel Addis Ababa",
    countryName: "Ethiopia",
    cityName: "Addis Ababa",
    payerName: "Ethiopian Airlines Hospitality",
    payerEmail: "billing@ethiopianskylighthotel.com",
    payerPhone: "+251911229988",
    amount: 7500,
    currency: "ETB",
    provider: "telebirr",
    paymentType: "advertisement",
    status: "completed",
    reference: "TB-20260829-99412",
    description: "Airport Vicinity Spotlight Billboard Ad",
    registeredBy: "Alex Rivera (Super Admin)",
    createdAt: new Date("2026-08-29T08:30:00Z").toISOString(),
    updatedAt: new Date("2026-08-29T08:30:00Z").toISOString(),
  },
  {
    id: "TX-CHP-885412",
    businessId: "biz-22",
    businessName: "Moyos Ethiopian Cafe",
    countryName: "Ethiopia",
    cityName: "Adama",
    payerName: "Moyo Teshome",
    payerEmail: "moyo@moyoscafe.com",
    payerPhone: "+251911445566",
    amount: 1499,
    currency: "ETB",
    provider: "chapa",
    paymentType: "subscription",
    status: "completed",
    reference: "CHP-TX-884102",
    description: "Monthly Pro Subscription - Adama Express Highway branch",
    registeredBy: "system",
    createdAt: new Date("2026-08-28T17:00:00Z").toISOString(),
    updatedAt: new Date("2026-08-28T17:00:00Z").toISOString(),
  },
  {
    id: "TX-TEL-774321",
    businessId: "biz-23",
    businessName: "Dimitri Greek Restaurant",
    countryName: "Ethiopia",
    cityName: "Addis Ababa",
    payerName: "Nikos Dimitri",
    payerEmail: "nikos@dimitrigreek.com",
    payerPhone: "+251911883311",
    amount: 2200,
    currency: "ETB",
    provider: "telebirr",
    paymentType: "advertisement",
    status: "refunded",
    reference: "TB-20260828-44120",
    description: "Refunded: Campaign rescheduled due to renovation",
    registeredBy: "Alex Rivera (Super Admin)",
    createdAt: new Date("2026-08-28T11:40:00Z").toISOString(),
    updatedAt: new Date("2026-08-28T15:10:00Z").toISOString(),
  },
  {
    id: "TX-CBE-663210",
    businessId: "biz-24",
    businessName: "Gusto Italian Restaurant Bole",
    countryName: "Ethiopia",
    cityName: "Addis Ababa",
    payerName: "Giorgio Bianchi",
    payerEmail: "info@gustoaddis.com",
    payerPhone: "+251911994422",
    amount: 1499,
    currency: "ETB",
    provider: "cbebirr",
    paymentType: "subscription",
    status: "completed",
    reference: "CBE-TX-7739102",
    description: "Pro Tier Monthly Plan",
    registeredBy: "system",
    createdAt: new Date("2026-08-27T16:15:00Z").toISOString(),
    updatedAt: new Date("2026-08-27T16:15:00Z").toISOString(),
  },
  {
    id: "TX-BNK-552109",
    businessId: "biz-25",
    businessName: "Century Mall Gurd Shola",
    countryName: "Ethiopia",
    cityName: "Addis Ababa",
    payerName: "Kassahun Wondimu",
    payerEmail: "kassahun@centurymall.et",
    payerPhone: "+251911332211",
    amount: 15000,
    currency: "ETB",
    provider: "bank_transfer",
    paymentType: "advertisement",
    status: "completed",
    reference: "CBE-SLIP-884019",
    description: "Full Mall Spotlight Banner & Push Promotion",
    registeredBy: "Marcus Vance (Admin)",
    createdAt: new Date("2026-08-27T09:00:00Z").toISOString(),
    updatedAt: new Date("2026-08-27T09:00:00Z").toISOString(),
  },
  {
    id: "TX-MPE-441098",
    businessId: "biz-26",
    businessName: "Safari Park Hotel Agency",
    countryName: "Kenya",
    cityName: "Nairobi",
    payerName: "George Kamau",
    payerEmail: "george@safaripark.co.ke",
    payerPhone: "+254733112233",
    amount: 3200,
    currency: "ETB",
    provider: "mpesa",
    paymentType: "featured_listing",
    status: "completed",
    reference: "QZ77291048K",
    description: "Cross-Border Tourism Listing Spotlight",
    registeredBy: "system",
    createdAt: new Date("2026-08-26T14:30:00Z").toISOString(),
    updatedAt: new Date("2026-08-26T14:30:00Z").toISOString(),
  },
  {
    id: "TX-STR-330987",
    businessId: "biz-27",
    businessName: "Golden Tulip Addis Ababa",
    countryName: "Ethiopia",
    cityName: "Addis Ababa",
    payerName: "Tarekegn Haile",
    payerEmail: "tarekegn@goldentulipaddis.com",
    amount: 99,
    currency: "USD",
    provider: "card",
    paymentType: "subscription",
    status: "completed",
    reference: "ch_110948XalM",
    description: "Pro Tier Monthly Plan",
    registeredBy: "system",
    createdAt: new Date("2026-08-26T10:10:00Z").toISOString(),
    updatedAt: new Date("2026-08-26T10:10:00Z").toISOString(),
  },
  {
    id: "TX-TEL-229876",
    businessId: "biz-28",
    businessName: "Tana View Lakeside Resort",
    countryName: "Ethiopia",
    cityName: "Bahir Dar",
    payerName: "Yohannes Alemu",
    payerEmail: "tanaview@ethionet.et",
    payerPhone: "+251918440099",
    amount: 1499,
    currency: "ETB",
    provider: "telebirr",
    paymentType: "subscription",
    status: "completed",
    reference: "TB-20260825-77201",
    description: "Pro Tier Monthly Plan - Lake Tana Waterfront",
    registeredBy: "system",
    createdAt: new Date("2026-08-25T15:45:00Z").toISOString(),
    updatedAt: new Date("2026-08-25T15:45:00Z").toISOString(),
  },
  {
    id: "TX-CBE-118765",
    businessId: "biz-29",
    businessName: "Edna Mall Entertainment",
    countryName: "Ethiopia",
    cityName: "Addis Ababa",
    payerName: "Yared Wolde",
    payerEmail: "yared@ednamall.et",
    payerPhone: "+251911221100",
    amount: 4500,
    currency: "ETB",
    provider: "cbebirr",
    paymentType: "advertisement",
    status: "completed",
    reference: "CBE-TX-6620194",
    description: "Cinema & Family Fun Category Top Billboard",
    registeredBy: "Marcus Vance (Admin)",
    createdAt: new Date("2026-08-25T11:20:00Z").toISOString(),
    updatedAt: new Date("2026-08-25T11:20:00Z").toISOString(),
  },
  {
    id: "TX-TEL-007654",
    businessId: "biz-30",
    businessName: "Fendika Cultural Center",
    countryName: "Ethiopia",
    cityName: "Addis Ababa",
    payerName: "Melaku Belay",
    payerEmail: "fendika@culturalcenter.org",
    payerPhone: "+251911552233",
    amount: 1200,
    currency: "ETB",
    provider: "telebirr",
    paymentType: "verification",
    status: "completed",
    reference: "TB-20260824-33291",
    description: "Cultural Landmark Verification & Verified Gold Badge",
    registeredBy: "Alex Rivera (Super Admin)",
    createdAt: new Date("2026-08-24T16:00:00Z").toISOString(),
    updatedAt: new Date("2026-08-24T16:00:00Z").toISOString(),
  },
  {
    id: "TX-CHP-996543",
    businessId: "biz-31",
    businessName: "Kaldi's Coffee Bole Medhanialem",
    countryName: "Ethiopia",
    cityName: "Addis Ababa",
    payerName: "Tseday Asrat",
    payerEmail: "finance@kaldiscoffee.com",
    payerPhone: "+251911663300",
    amount: 6000,
    currency: "ETB",
    provider: "chapa",
    paymentType: "featured_listing",
    status: "completed",
    reference: "CHP-TX-992014",
    description: "Coffee Shops Priority Map Spotlight (1 Month)",
    registeredBy: "system",
    createdAt: new Date("2026-08-24T09:15:00Z").toISOString(),
    updatedAt: new Date("2026-08-24T09:15:00Z").toISOString(),
  },
  {
    id: "TX-TEL-885432",
    businessId: "biz-32",
    businessName: "Black Rose Bar & Lounge",
    countryName: "Ethiopia",
    cityName: "Addis Ababa",
    payerName: "Elias Worku",
    payerEmail: "elias@blackrose.et",
    payerPhone: "+251912554433",
    amount: 1499,
    currency: "ETB",
    provider: "telebirr",
    paymentType: "subscription",
    status: "pending",
    reference: "TB-20260823-11204",
    description: "Awaiting telebirr authorization confirmation",
    registeredBy: "system",
    createdAt: new Date("2026-08-23T19:30:00Z").toISOString(),
    updatedAt: new Date("2026-08-23T19:30:00Z").toISOString(),
  },
  {
    id: "TX-CBE-774321",
    businessId: "biz-33",
    businessName: "Dashen Traditional Restaurant Gondar",
    countryName: "Ethiopia",
    cityName: "Gondar",
    payerName: "Almaz Kebede",
    payerEmail: "almaz@dashenresto.et",
    payerPhone: "+251918330044",
    amount: 1499,
    currency: "ETB",
    provider: "cbebirr",
    paymentType: "subscription",
    status: "completed",
    reference: "CBE-TX-5510293",
    description: "Pro Tier Monthly Plan - Fasil Ghebbi Historic Quarter",
    registeredBy: "system",
    createdAt: new Date("2026-08-23T12:00:00Z").toISOString(),
    updatedAt: new Date("2026-08-23T12:00:00Z").toISOString(),
  },
  {
    id: "TX-TEL-663210",
    businessId: "biz-34",
    businessName: "Dembel City Center Bole Road",
    countryName: "Ethiopia",
    cityName: "Addis Ababa",
    payerName: "Dembel Leasing Office",
    payerEmail: "leasing@dembelcenter.com",
    payerPhone: "+251911776655",
    amount: 9500,
    currency: "ETB",
    provider: "telebirr",
    paymentType: "advertisement",
    status: "completed",
    reference: "TB-20260822-66102",
    description: "Addis Commercial Real Estate Header Banner Ad",
    registeredBy: "Alex Rivera (Super Admin)",
    createdAt: new Date("2026-08-22T14:20:00Z").toISOString(),
    updatedAt: new Date("2026-08-22T14:20:00Z").toISOString(),
  },
  {
    id: "TX-STR-552109",
    businessId: "biz-35",
    businessName: "Elilly International Hotel Kazanchis",
    countryName: "Ethiopia",
    cityName: "Addis Ababa",
    payerName: "Elilly Accounts Dept",
    payerEmail: "accounting@elillyhotel.com",
    amount: 199,
    currency: "USD",
    provider: "card",
    paymentType: "subscription",
    status: "completed",
    reference: "ch_55201948LlZ",
    description: "Enterprise Monthly Plan",
    registeredBy: "system",
    createdAt: new Date("2026-08-22T09:45:00Z").toISOString(),
    updatedAt: new Date("2026-08-22T09:45:00Z").toISOString(),
  },
  {
    id: "TX-TEL-449911",
    businessId: "biz-36",
    businessName: "Mekelle Highland Tech Solutions",
    countryName: "Ethiopia",
    cityName: "Mekelle",
    payerName: "Berhane Gebre",
    payerEmail: "berhane@mekelletech.et",
    payerPhone: "+251914332211",
    amount: 2400,
    currency: "ETB",
    provider: "telebirr",
    paymentType: "subscription",
    status: "completed",
    reference: "TB-20260821-99014",
    description: "Enterprise Listing Package - Mekelle Tech Hub",
    registeredBy: "system",
    createdAt: new Date("2026-08-21T11:30:00Z").toISOString(),
    updatedAt: new Date("2026-08-21T11:30:00Z").toISOString(),
  },
  {
    id: "TX-BNK-338822",
    businessId: "biz-37",
    businessName: "Hawassa Lake Breeze Fish & Dining",
    countryName: "Ethiopia",
    cityName: "Hawassa",
    payerName: "Mesele Tadesse",
    payerEmail: "info@lakebreeze.et",
    payerPhone: "+251916554433",
    amount: 1800,
    currency: "ETB",
    provider: "bank_transfer",
    paymentType: "verification",
    status: "pending",
    reference: "CBE-DEP-773910",
    description: "Lake Hawassa Tourism Verified Partner Inspection Fee",
    registeredBy: "Marcus Vance (Admin)",
    createdAt: new Date("2026-08-20T15:10:00Z").toISOString(),
    updatedAt: new Date("2026-08-20T15:10:00Z").toISOString(),
  },
  {
    id: "TX-STR-227733",
    businessId: "biz-38",
    businessName: "Habesha Gourmet Lounge Dubai",
    countryName: "United Arab Emirates",
    cityName: "Dubai",
    payerName: "Kidanemariam Wolde",
    payerEmail: "billing@habeshadubai.ae",
    payerPhone: "+971501234567",
    amount: 299,
    currency: "USD",
    provider: "card",
    paymentType: "subscription",
    status: "completed",
    reference: "ch_dxb_8820194",
    description: "International Global Directory Pro Plan - Downtown Dubai",
    registeredBy: "Alex Rivera (Super Admin)",
    createdAt: new Date("2026-08-19T13:40:00Z").toISOString(),
    updatedAt: new Date("2026-08-19T13:40:00Z").toISOString(),
  },
  {
    id: "TX-STR-116644",
    businessId: "biz-39",
    businessName: "Little Ethiopia Cultural Cafe New York",
    countryName: "United States",
    cityName: "New York",
    payerName: "Senait Gebremariam",
    payerEmail: "senait@littleethiopianyc.com",
    payerPhone: "+12125559876",
    amount: 199,
    currency: "USD",
    provider: "card",
    paymentType: "subscription",
    status: "completed",
    reference: "ch_nyc_993014",
    description: "US Diaspora Business Featured Monthly Package",
    registeredBy: "Alex Rivera (Super Admin)",
    createdAt: new Date("2026-08-18T18:25:00Z").toISOString(),
    updatedAt: new Date("2026-08-18T18:25:00Z").toISOString(),
  },
  {
    id: "TX-TEL-005533",
    businessId: "biz-40",
    businessName: "Adama Rift Valley Motors",
    countryName: "Ethiopia",
    cityName: "Adama",
    payerName: "Gemechu Desta",
    payerEmail: "gemechu@rvmotors.et",
    payerPhone: "+251911449988",
    amount: 3500,
    currency: "ETB",
    provider: "telebirr",
    paymentType: "featured_listing",
    status: "failed",
    reference: "TB-20260817-55012",
    description: "Failed: Insufficient Telebirr wallet balance at transaction time",
    registeredBy: "system",
    createdAt: new Date("2026-08-17T08:15:00Z").toISOString(),
    updatedAt: new Date("2026-08-17T08:16:00Z").toISOString(),
  },
];
