import { IReport } from "@/types/report";

export const SEED_REPORTS: IReport[] = [
  {
    id: "REP-2026-001",
    type: "business",
    title: "Fake Business Profile: bole-crypto-exchange",
    reason: "Fraud / Unlicensed Financial Scam",
    details:
      "Listing claims to be a licensed National Bank crypto exchange offering 80% daily returns. Multiple user complaints received regarding wire advance fraud.",
    targetId: "biz-fake-1",
    targetName: "Bole Crypto & Forex Trade Hub",
    targetType: "business",
    reporterName: "Abebe Tadesse",
    reporterEmail: "abebe.t@gmail.com",
    reporterId: "user-cust-1",
    reporterRole: "user",
    status: "under_review",
    priority: "critical",
    city: "Addis Ababa",
    country: "Ethiopia",
    evidenceUrls: ["https://images.unsplash.com/photo-1621416894569-0f39ed31d247?w=600"],
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 4).toISOString(), // 4 hours ago
    updatedAt: new Date(Date.now() - 1000 * 60 * 60 * 2).toISOString(),
  },
  {
    id: "REP-2026-002",
    type: "review",
    title: "Offensive Competitor Defamation on Kategna Restaurant",
    reason: "Competitor abusive defamation",
    details:
      "Account registered 10 minutes ago posted copy-pasted medical claims accusing food poisoning without dining evidence to boost neighboring eatery.",
    targetId: "rev-flag-102",
    targetName: "Kategna Restaurant Review #102",
    targetType: "review",
    reporterName: "Samuel Kebede",
    reporterEmail: "samuel@kategnarestaurant.com",
    reporterId: "user-owner-1",
    reporterRole: "owner",
    status: "investigating",
    priority: "high",
    city: "Addis Ababa",
    country: "Ethiopia",
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 18).toISOString(), // 18 hours ago
    updatedAt: new Date(Date.now() - 1000 * 60 * 60 * 6).toISOString(),
  },
  {
    id: "REP-2026-003",
    type: "user",
    title: "User spam account: spam_seller_001",
    reason: "Mass spam DMs to business owners",
    details:
      "Automated bot user sending unsolicited Telegram bot links and fake bank slips to verified businesses in Bole and Kazanchis.",
    targetId: "usr-bot-991",
    targetName: "spam_seller_001 (Telegram Promo Bot)",
    targetType: "user",
    reporterName: "Sara Konjit",
    reporterEmail: "sara.k@gmail.com",
    reporterId: "user-cust-4",
    reporterRole: "user",
    status: "under_review",
    priority: "high",
    city: "Addis Ababa",
    country: "Ethiopia",
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 28).toISOString(), // 1 day ago
    updatedAt: new Date(Date.now() - 1000 * 60 * 60 * 20).toISOString(),
  },
  {
    id: "REP-2026-004",
    type: "business",
    title: "Duplicate listing: Addis Continental Hotel x3",
    reason: "Duplicate or cloned business listing",
    details:
      "Three separate listings created with slight variations in phone numbers, confusing tourists and booking inquiries.",
    targetId: "biz-dup-301",
    targetName: "Addis Continental Hotel Branch B",
    targetType: "business",
    reporterName: "Dawit Haile",
    reporterEmail: "dawit.h@addishotels.et",
    reporterId: "user-owner-2",
    reporterRole: "owner",
    status: "investigating",
    priority: "medium",
    city: "Addis Ababa",
    country: "Ethiopia",
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 36).toISOString(),
    updatedAt: new Date(Date.now() - 1000 * 60 * 60 * 12).toISOString(),
  },
  {
    id: "REP-2026-005",
    type: "media",
    title: "Copyright Infringement: Uncredited Commercial Photo",
    reason: "Copyright / Intellectual Property Violation",
    details:
      "Photographer portfolio watermarked image uploaded by third-party without commercial licensing permission.",
    targetId: "med-copy-501",
    targetName: "Kuriftu Resort Aerial Panorama.jpg",
    targetType: "media",
    reporterName: "Yonas Belete (Lens Creative)",
    reporterEmail: "yonas@lenscreative.et",
    reporterId: "user-cust-9",
    reporterRole: "user",
    status: "pending",
    priority: "medium",
    city: "Bishoftu",
    country: "Ethiopia",
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 48).toISOString(), // 2 days ago
    updatedAt: new Date(Date.now() - 1000 * 60 * 60 * 48).toISOString(),
  },
  {
    id: "REP-2026-006",
    type: "review",
    title: "Hate Speech & Profanity in Lucy Lounge Review",
    reason: "Hate Speech and Harassment",
    details:
      "Review contains discriminatory slurs targeting staff members. Directly violates Community Guidelines Section 4.2.",
    targetId: "rev-hate-04",
    targetName: "Lucy Lounge Review #581",
    targetType: "review",
    reporterName: "Hanna Girma",
    reporterEmail: "hanna@lucylounge.com",
    reporterId: "user-owner-4",
    reporterRole: "owner",
    status: "pending",
    priority: "critical",
    city: "Addis Ababa",
    country: "Ethiopia",
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 52).toISOString(),
    updatedAt: new Date(Date.now() - 1000 * 60 * 60 * 52).toISOString(),
  },
  {
    id: "REP-2026-007",
    type: "business",
    title: "Permanently Closed Pharmacy Still Operating Listing",
    reason: "Incorrect Information / Outdated Closed Establishment",
    details:
      "Bethel Pharmacy on ring road closed 6 months ago; emergency patients arriving at locked premises late at night.",
    targetId: "biz-closed-12",
    targetName: "Bethel Emergency Pharmacy",
    targetType: "business",
    reporterName: "Dr. Meron Assefa",
    reporterEmail: "meron@healthnet.et",
    reporterId: "user-cust-12",
    reporterRole: "user",
    status: "under_review",
    priority: "high",
    city: "Addis Ababa",
    country: "Ethiopia",
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 70).toISOString(),
    updatedAt: new Date(Date.now() - 1000 * 60 * 60 * 30).toISOString(),
  },
  {
    id: "REP-2026-008",
    type: "user",
    title: "Aggressive Extortion via Direct Messaging",
    reason: "Extortion / Blackmail Threats",
    details:
      "User threatening cafe owners with coordinated 1-star review floods unless given free catering discounts.",
    targetId: "usr-extort-88",
    targetName: "AddisReviewKing_99",
    targetType: "user",
    reporterName: "Blen Wondimu",
    reporterEmail: "blen@kaldiscoffee.et",
    reporterId: "user-owner-6",
    reporterRole: "owner",
    status: "investigating",
    priority: "critical",
    city: "Addis Ababa",
    country: "Ethiopia",
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 85).toISOString(),
    updatedAt: new Date(Date.now() - 1000 * 60 * 60 * 15).toISOString(),
  },
  {
    id: "REP-2026-009",
    type: "media",
    title: "Misleading Low-Res Stock Photo as Local Facility",
    reason: "Misleading / Deceptive Visuals",
    details:
      "Listing using luxury Swiss dental clinic photo claiming it is their local dental room in Merkato.",
    targetId: "med-stock-22",
    targetName: "Luxury Clinic Operatory Room 1.jpg",
    targetType: "media",
    reporterName: "Kidus Solomon",
    reporterEmail: "kidus.s@gmail.com",
    reporterId: "user-cust-15",
    reporterRole: "user",
    status: "pending",
    priority: "low",
    city: "Addis Ababa",
    country: "Ethiopia",
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 96).toISOString(),
    updatedAt: new Date(Date.now() - 1000 * 60 * 60 * 96).toISOString(),
  },
  {
    id: "REP-2026-010",
    type: "business",
    title: "Counterfeit Brand Impersonation: Nike Store Bole",
    reason: "Impersonation / Unauthorized Trademark Usage",
    details:
      "Store using official Nike swoosh branding and logos without authorization selling gray market footwear.",
    targetId: "biz-fake-nike",
    targetName: "Nike Outlet Ethiopia Official",
    targetType: "business",
    reporterName: "Legal Counsel East Africa",
    reporterEmail: "ip-enforce@brandprotect.com",
    reporterId: "user-legal-1",
    reporterRole: "user",
    status: "investigating",
    priority: "high",
    city: "Addis Ababa",
    country: "Ethiopia",
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 110).toISOString(),
    updatedAt: new Date(Date.now() - 1000 * 60 * 60 * 40).toISOString(),
  },
  {
    id: "REP-2026-011",
    type: "review",
    title: "Promotional Affiliate Link Spam in Reviews",
    reason: "Spam / Third-Party Commercial Promotion",
    details:
      "Reviewer posted external WhatsApp link and loan referral codes in Ethiopian Airlines ticket office listing.",
    targetId: "rev-spam-77",
    targetName: "Ethiopian Airlines Ticket Office Review",
    targetType: "review",
    reporterName: "Marta Teshome",
    reporterEmail: "marta.t@ethiopianairlines.com",
    reporterId: "user-owner-8",
    reporterRole: "owner",
    status: "resolved",
    priority: "medium",
    resolutionNotes: "Review deleted and sender account restricted from posting comments for 14 days.",
    resolvedBy: "Alex Rivera (Super Admin)",
    resolvedAt: new Date(Date.now() - 1000 * 60 * 60 * 24).toISOString(),
    actionTaken: "content_removed",
    city: "Addis Ababa",
    country: "Ethiopia",
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 120).toISOString(),
    updatedAt: new Date(Date.now() - 1000 * 60 * 60 * 24).toISOString(),
  },
  {
    id: "REP-2026-012",
    type: "business",
    title: "Suspicious Telebirr Payment Number in Description",
    reason: "Fraudulent Payment Solicitation",
    details:
      "Unauthorized editor inserted personal Telebirr phone number inside business profile asking deposit for room reservations.",
    targetId: "biz-tele-scam",
    targetName: "Bishoftu Lake View Villa",
    targetType: "business",
    reporterName: "Solomon Getachew",
    reporterEmail: "solomon.g@gmail.com",
    reporterId: "user-cust-21",
    reporterRole: "user",
    status: "resolved",
    priority: "critical",
    resolutionNotes: "Number removed, listing rolled back to verified owner version, and security warning dispatched.",
    resolvedBy: "Marcus Vance (Admin)",
    resolvedAt: new Date(Date.now() - 1000 * 60 * 60 * 32).toISOString(),
    actionTaken: "penalty_applied",
    city: "Bishoftu",
    country: "Ethiopia",
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 130).toISOString(),
    updatedAt: new Date(Date.now() - 1000 * 60 * 60 * 32).toISOString(),
  },
  {
    id: "REP-2026-013",
    type: "user",
    title: "Fictitious Review Generation Ring",
    reason: "Coordinated Review Manipulation",
    details:
      "Cluster of 5 user accounts operating from identical IP address posting identical 5-star reviews within 3 minutes.",
    targetId: "usr-ring-01",
    targetName: "Cluster of 5 Bot Accounts (Lead: aster_k99)",
    targetType: "user",
    reporterName: "System Automated Moderation Sentinel",
    reporterEmail: "sentinel@bizfinder.et",
    reporterId: "system-sentinel",
    reporterRole: "admin",
    status: "resolved",
    priority: "high",
    resolutionNotes: "All 5 bot accounts suspended and 18 fake reviews purged from search index.",
    resolvedBy: "Alex Rivera (Super Admin)",
    resolvedAt: new Date(Date.now() - 1000 * 60 * 60 * 48).toISOString(),
    actionTaken: "user_suspended",
    city: "Addis Ababa",
    country: "Ethiopia",
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 150).toISOString(),
    updatedAt: new Date(Date.now() - 1000 * 60 * 60 * 48).toISOString(),
  },
  {
    id: "REP-2026-014",
    type: "review",
    title: "Unfounded Health Violation Claim",
    reason: "Defamation / False Claim",
    details:
      "Review claiming food hygiene violation at Golden Plate was investigated alongside local health board inspection which passed 100%.",
    targetId: "rev-golden-plate",
    targetName: "Golden Plate Diner Review",
    targetType: "review",
    reporterName: "Natnael Demissie",
    reporterEmail: "natnael@goldenplate.et",
    reporterId: "user-owner-10",
    reporterRole: "owner",
    status: "dismissed",
    priority: "low",
    resolutionNotes: "Review dismissed after mutual mediation and clarification update posted by reviewer.",
    resolvedBy: "Marcus Vance (Admin)",
    resolvedAt: new Date(Date.now() - 1000 * 60 * 60 * 60).toISOString(),
    actionTaken: "dismissed",
    city: "Addis Ababa",
    country: "Ethiopia",
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 170).toISOString(),
    updatedAt: new Date(Date.now() - 1000 * 60 * 60 * 60).toISOString(),
  },
  {
    id: "REP-2026-015",
    type: "business",
    title: "Unlicensed Medical Clinic Advertising Surgery",
    reason: "Regulatory Compliance Violation",
    details:
      "Facility advertised invasive cosmetic procedures without valid Ministry of Health operating accreditation.",
    targetId: "biz-unlicensed-med",
    targetName: "Addis Glow Cosmetic Clinic",
    targetType: "business",
    reporterName: "Regulatory Oversight Bureau",
    reporterEmail: "health-inspection@moh.gov.et",
    reporterId: "user-gov-1",
    reporterRole: "admin",
    status: "under_review",
    priority: "critical",
    city: "Addis Ababa",
    country: "Ethiopia",
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 180).toISOString(),
    updatedAt: new Date(Date.now() - 1000 * 60 * 60 * 72).toISOString(),
  },
  {
    id: "REP-2026-016",
    type: "media",
    title: "Inappropriate Graphic Media on Restaurant Page",
    reason: "Explicit / Inappropriate Content",
    details:
      "Customer uploaded graphic photo accidentally tagged as food item on public cafe gallery.",
    targetId: "med-inapp-9",
    targetName: "Customer Upload Gallery Asset #892",
    targetType: "media",
    reporterName: "Feven Berhanu",
    reporterEmail: "feven@roastandco.et",
    reporterId: "user-owner-12",
    reporterRole: "owner",
    status: "resolved",
    priority: "critical",
    resolutionNotes: "Asset immediately unlinked from CDN and permanently quarantined.",
    resolvedBy: "Alex Rivera (Super Admin)",
    resolvedAt: new Date(Date.now() - 1000 * 60 * 60 * 10).toISOString(),
    actionTaken: "content_removed",
    city: "Addis Ababa",
    country: "Ethiopia",
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 190).toISOString(),
    updatedAt: new Date(Date.now() - 1000 * 60 * 60 * 10).toISOString(),
  },
];
