import { ISecurityEvent } from "@/types/security";

export const SEED_SECURITY_EVENTS: ISecurityEvent[] = [
  {
    id: "sec-001",
    eventType: "brute_force_blocked",
    severity: "critical",
    status: "blocked",
    title: "Brute-force Login Attack Throttled",
    description: "Repeated 45 failed login attempts targeting root super_admin account within 60 seconds. Origin IP placed in 24h jail.",
    actorName: "Automated Botnet Vector",
    actorEmail: "admin@bizfinder.et",
    actorRole: "anonymous",
    targetResource: "/admin/sign-in",
    ipAddress: "196.188.12.94",
    city: "Addis Ababa",
    country: "Ethiopia",
    device: "Bot",
    browser: "Python-Requests/2.31",
    os: "Linux x86_64",
    actionTaken: "blocked",
    metadata: { failedAttempts: 45, jailDurationHours: 24, userAgent: "python-requests/2.31.0" },
    isFlagged: true,
    resolvedBy: "Security Automation Daemon",
    createdAt: new Date(Date.now() - 1000 * 60 * 12).toISOString(),
  },
  {
    id: "sec-002",
    eventType: "role_elevated",
    severity: "high",
    status: "resolved",
    title: "Territory Admin Privilege Granted",
    description: "Super Admin Alex Rivera granted Country Main Admin permissions to Dawit Tsegaye for Ethiopia jurisdiction.",
    actorId: "user_superadmin_01",
    actorName: "Alex Rivera",
    actorEmail: "alex.rivera@bizfinder.et",
    actorRole: "super_admin",
    targetResource: "/api/admin/admins",
    ipAddress: "197.156.104.12",
    city: "Addis Ababa",
    country: "Ethiopia",
    device: "Desktop",
    browser: "Chrome 128",
    os: "macOS Sonoma",
    actionTaken: "allowed",
    metadata: { targetAdmin: "Dawit Tsegaye", targetRole: "country_admin", assignedCountry: "Ethiopia" },
    isFlagged: false,
    resolvedBy: "Alex Rivera",
    createdAt: new Date(Date.now() - 1000 * 60 * 45).toISOString(),
  },
  {
    id: "sec-003",
    eventType: "two_factor_enabled",
    severity: "info",
    status: "logged",
    title: "2-Factor Authentication Activated",
    description: "Time-based OTP authenticator successfully paired and verified with Clerk authentication security.",
    actorId: "user_owner_01",
    actorName: "Sara Hailu",
    actorEmail: "sara@kategna.et",
    actorRole: "owner",
    targetResource: "/dashboard/settings/security",
    ipAddress: "197.156.77.201",
    city: "Bole, Addis Ababa",
    country: "Ethiopia",
    device: "Mobile",
    browser: "Mobile Safari 18",
    os: "iOS 18",
    actionTaken: "allowed",
    metadata: { authProvider: "TOTP Authenticator", backupCodesGenerated: 10 },
    createdAt: new Date(Date.now() - 1000 * 60 * 95).toISOString(),
  },
  {
    id: "sec-004",
    eventType: "unauthorized_access_attempt",
    severity: "critical",
    status: "investigating",
    title: "Restricted Financial Ledger Access Probed",
    description: "Unauthenticated request attempting path traversal on /api/payments/export-raw without Bearer JWT session.",
    actorName: "Anonymous External IP",
    actorRole: "anonymous",
    targetResource: "/api/payments/export-raw",
    ipAddress: "45.133.1.88",
    city: "Frankfurt",
    country: "Germany",
    device: "Bot",
    browser: "Go-http-client/1.1",
    os: "Unknown",
    actionTaken: "blocked",
    metadata: { httpMethod: "GET", attemptedPath: "/api/payments/export-raw?token=../", statusCode: 401 },
    isFlagged: true,
    createdAt: new Date(Date.now() - 1000 * 60 * 140).toISOString(),
  },
  {
    id: "sec-005",
    eventType: "login_success",
    severity: "info",
    status: "logged",
    title: "Super Admin Authentication Successful",
    description: "Alex Rivera logged into the Central Admin Control Panel from primary secure workstation.",
    actorId: "user_superadmin_01",
    actorName: "Alex Rivera",
    actorEmail: "alex.rivera@bizfinder.et",
    actorRole: "super_admin",
    targetResource: "/admin",
    ipAddress: "197.156.104.12",
    city: "Addis Ababa",
    country: "Ethiopia",
    device: "Desktop",
    browser: "Chrome 128",
    os: "macOS Sonoma",
    actionTaken: "allowed",
    metadata: { sessionExpiryMinutes: 120, mfaVerified: true },
    createdAt: new Date(Date.now() - 1000 * 60 * 180).toISOString(),
  },
  {
    id: "sec-006",
    eventType: "api_key_generated",
    severity: "medium",
    status: "logged",
    title: "Production Merchant API Key Issued",
    description: "Generated read-write API key for Telebirr automated billing verification integration.",
    actorId: "user_superadmin_01",
    actorName: "Alex Rivera",
    actorEmail: "alex.rivera@bizfinder.et",
    actorRole: "super_admin",
    targetResource: "/api/admin/settings",
    ipAddress: "197.156.104.12",
    city: "Addis Ababa",
    country: "Ethiopia",
    device: "Desktop",
    browser: "Chrome 128",
    os: "macOS Sonoma",
    actionTaken: "allowed",
    metadata: { keyScope: ["payments.verify", "invoices.read"], keyName: "Telebirr Gateway Webhook" },
    createdAt: new Date(Date.now() - 1000 * 60 * 240).toISOString(),
  },
  {
    id: "sec-007",
    eventType: "ip_blocked",
    severity: "high",
    status: "blocked",
    title: "Malicious IP Banned by Admin",
    description: "Permanent firewall blacklist added for repeat SQL injection probe pattern against search API.",
    actorId: "user_admin_02",
    actorName: "Elena Vance",
    actorEmail: "elena.vance@bizfinder.et",
    actorRole: "admin",
    targetResource: "/api/search",
    ipAddress: "185.220.101.5",
    city: "Tor Exit Node",
    country: "Netherlands",
    device: "Bot",
    browser: "curl/7.88.1",
    os: "Linux",
    actionTaken: "quarantined",
    metadata: { ruleType: "CIDR Ban", expires: "Never", reason: "Automated exploit payload detected" },
    isFlagged: true,
    resolvedBy: "Elena Vance",
    createdAt: new Date(Date.now() - 1000 * 60 * 310).toISOString(),
  },
  {
    id: "sec-008",
    eventType: "password_changed",
    severity: "low",
    status: "logged",
    title: "Account Password Updated",
    description: "Business owner Bethlehem Alemu reset account password following security protocol recommendation.",
    actorId: "user_owner_02",
    actorName: "Bethlehem Alemu",
    actorEmail: "bethlehem@solerebel.et",
    actorRole: "owner",
    targetResource: "/dashboard/settings/security",
    ipAddress: "196.188.44.15",
    city: "Kirkos, Addis Ababa",
    country: "Ethiopia",
    device: "Desktop",
    browser: "Firefox 129",
    os: "Windows 11",
    actionTaken: "allowed",
    metadata: { passwordStrength: "Strong (16 chars)", previousSessionsTerminated: true },
    createdAt: new Date(Date.now() - 1000 * 60 * 390).toISOString(),
  },
  {
    id: "sec-009",
    eventType: "session_revoked",
    severity: "medium",
    status: "resolved",
    title: "Remote Active Session Terminated",
    description: "Owner Marcus Vance revoked 2 stale mobile sessions from unrecognized device signature.",
    actorId: "user_owner_03",
    actorName: "Marcus Vance",
    actorEmail: "marcus@vancegroup.et",
    actorRole: "owner",
    targetResource: "/dashboard/settings/security",
    ipAddress: "197.156.88.33",
    city: "Hawassa",
    country: "Ethiopia",
    device: "Desktop",
    browser: "Chrome 128",
    os: "Windows 11",
    actionTaken: "session_terminated",
    metadata: { terminatedCount: 2, remainingActiveCount: 1 },
    createdAt: new Date(Date.now() - 1000 * 60 * 480).toISOString(),
  },
  {
    id: "sec-010",
    eventType: "ddos_mitigated",
    severity: "high",
    status: "blocked",
    title: "Edge Layer Rate Limit Mitigated Flood",
    description: "Surge of 3,200 HTTP GET requests in 10s against /api/categories throttled by Cloudflare edge barrier.",
    actorName: "Distributed Client Cluster",
    actorRole: "system",
    targetResource: "/api/categories",
    ipAddress: "103.145.22.0/24",
    city: "Global Subnet",
    country: "Singapore",
    device: "Bot",
    browser: "Custom Python Scraper",
    os: "Linux",
    actionTaken: "blocked",
    metadata: { peakRps: 320, normalThresholdRps: 50, mitigationWindowSec: 300 },
    isFlagged: true,
    createdAt: new Date(Date.now() - 1000 * 60 * 550).toISOString(),
  },
  {
    id: "sec-011",
    eventType: "sensitive_data_export",
    severity: "medium",
    status: "logged",
    title: "Platform Financial Ledger Exported",
    description: "Super Admin Alex Rivera generated and exported full encrypted CSV report of transactions for Q3 accounting.",
    actorId: "user_superadmin_01",
    actorName: "Alex Rivera",
    actorEmail: "alex.rivera@bizfinder.et",
    actorRole: "super_admin",
    targetResource: "/admin/payments",
    ipAddress: "197.156.104.12",
    city: "Addis Ababa",
    country: "Ethiopia",
    device: "Desktop",
    browser: "Chrome 128",
    os: "macOS Sonoma",
    actionTaken: "allowed",
    metadata: { exportedRecordCount: 340, exportFormat: "CSV", integrityChecksum: "sha256-a9b3c4" },
    createdAt: new Date(Date.now() - 1000 * 60 * 620).toISOString(),
  },
  {
    id: "sec-012",
    eventType: "login_failed",
    severity: "low",
    status: "logged",
    title: "Invalid Password Submitted",
    description: "Single failed login attempt on registered business owner account. Correct credentials submitted on retry.",
    actorName: "Yonas Mekonnen",
    actorEmail: "yonas@addiscraft.et",
    actorRole: "owner",
    targetResource: "/sign-in",
    ipAddress: "196.188.9.110",
    city: "Nifas Silk-Lafto, Addis Ababa",
    country: "Ethiopia",
    device: "Mobile",
    browser: "Chrome Mobile 127",
    os: "Android 14",
    actionTaken: "allowed",
    metadata: { failureReason: "invalid_password", attemptNumber: 1 },
    createdAt: new Date(Date.now() - 1000 * 60 * 700).toISOString(),
  },
  {
    id: "sec-013",
    eventType: "firewall_rule_added",
    severity: "high",
    status: "resolved",
    title: "Geo-Firewall WAF Policy Updated",
    description: "Added strict challenge inspection on legacy TLS 1.0/1.1 handshakes across all 195 regional gateways.",
    actorId: "user_superadmin_01",
    actorName: "Alex Rivera",
    actorEmail: "alex.rivera@bizfinder.et",
    actorRole: "super_admin",
    targetResource: "/admin/settings",
    ipAddress: "197.156.104.12",
    city: "Addis Ababa",
    country: "Ethiopia",
    device: "Desktop",
    browser: "Chrome 128",
    os: "macOS Sonoma",
    actionTaken: "allowed",
    metadata: { enforcedProtocol: "TLS 1.3 Minimum", affectedGateways: 195 },
    createdAt: new Date(Date.now() - 1000 * 60 * 790).toISOString(),
  },
  {
    id: "sec-014",
    eventType: "login_success",
    severity: "info",
    status: "logged",
    title: "City Admin Access Authorized",
    description: "City Administrator Kebede Tadesse authenticated for Dire Dawa regional operations oversight.",
    actorId: "user_admin_diredawa",
    actorName: "Kebede Tadesse",
    actorEmail: "kebede@bizfinder.et",
    actorRole: "city_admin",
    targetResource: "/admin",
    ipAddress: "196.189.20.15",
    city: "Dire Dawa",
    country: "Ethiopia",
    device: "Desktop",
    browser: "Edge 128",
    os: "Windows 11",
    actionTaken: "allowed",
    metadata: { assignedCity: "Dire Dawa", assignedCountry: "Ethiopia" },
    createdAt: new Date(Date.now() - 1000 * 60 * 870).toISOString(),
  },
  {
    id: "sec-015",
    eventType: "brute_force_blocked",
    severity: "high",
    status: "blocked",
    title: "Credential Stuffing Pattern Blocked",
    description: "Detected dictionary attack attempting common passwords against customer accounts. Immediate IP block issued.",
    actorName: "Proxy Node #88",
    actorRole: "anonymous",
    targetResource: "/sign-in",
    ipAddress: "91.240.118.42",
    city: "Bucharest",
    country: "Romania",
    device: "Bot",
    browser: "HeadlessChrome",
    os: "Linux",
    actionTaken: "blocked",
    metadata: { accountsTargeted: 18, requestFingerprint: "ja3-fingerprint-a87b" },
    isFlagged: true,
    createdAt: new Date(Date.now() - 1000 * 60 * 950).toISOString(),
  },
  {
    id: "sec-016",
    eventType: "api_key_revoked",
    severity: "medium",
    status: "resolved",
    title: "Deprecated Integration API Key Terminated",
    description: "Revoked legacy staging webhook token following migration to production SSL endpoint.",
    actorId: "user_superadmin_01",
    actorName: "Alex Rivera",
    actorEmail: "alex.rivera@bizfinder.et",
    actorRole: "super_admin",
    targetResource: "/api/admin/settings",
    ipAddress: "197.156.104.12",
    city: "Addis Ababa",
    country: "Ethiopia",
    device: "Desktop",
    browser: "Chrome 128",
    os: "macOS Sonoma",
    actionTaken: "allowed",
    metadata: { keyPrefix: "bf_live_stg_", activeLifespanDays: 45 },
    createdAt: new Date(Date.now() - 1000 * 60 * 1050).toISOString(),
  },
  {
    id: "sec-017",
    eventType: "maintenance_triggered",
    severity: "critical",
    status: "resolved",
    title: "Emergency Maintenance Simulation Run",
    description: "Super Admin executed scheduled rehearsal test of emergency maintenance lock mode.",
    actorId: "user_superadmin_01",
    actorName: "Alex Rivera",
    actorEmail: "alex.rivera@bizfinder.et",
    actorRole: "super_admin",
    targetResource: "/admin/settings",
    ipAddress: "197.156.104.12",
    city: "Addis Ababa",
    country: "Ethiopia",
    device: "Desktop",
    browser: "Chrome 128",
    os: "macOS Sonoma",
    actionTaken: "allowed",
    metadata: { durationSeconds: 60, systemServicesNominal: true },
    isFlagged: true,
    createdAt: new Date(Date.now() - 1000 * 60 * 1150).toISOString(),
  },
  {
    id: "sec-018",
    eventType: "login_success",
    severity: "info",
    status: "logged",
    title: "Business Owner Mobile Login",
    description: "Owner Dawit Solomon logged into Business Owner Portal via mobile app biometric session.",
    actorId: "user_owner_04",
    actorName: "Dawit Solomon",
    actorEmail: "owner@bizfinder.et",
    actorRole: "owner",
    targetResource: "/dashboard",
    ipAddress: "197.156.104.22",
    city: "Addis Ababa",
    country: "Ethiopia",
    device: "Mobile",
    browser: "Safari iOS",
    os: "iOS 17.6",
    actionTaken: "allowed",
    metadata: { deviceTrust: "Verified Device", faceIdVerified: true },
    createdAt: new Date(Date.now() - 1000 * 60 * 1250).toISOString(),
  },
  {
    id: "sec-019",
    eventType: "ip_whitelisted",
    severity: "low",
    status: "resolved",
    title: "Corporate HQ Static IP Whitelisted",
    description: "Whitelisted primary Ethio Telecom fiber gateway IP for friction-free admin workstation access.",
    actorId: "user_superadmin_01",
    actorName: "Alex Rivera",
    actorEmail: "alex.rivera@bizfinder.et",
    actorRole: "super_admin",
    targetResource: "/admin/settings",
    ipAddress: "197.156.104.12",
    city: "Bole Medhanialem, Addis Ababa",
    country: "Ethiopia",
    device: "Desktop",
    browser: "Chrome 128",
    os: "macOS Sonoma",
    actionTaken: "allowed",
    metadata: { label: "BizFinder Headquarters Fiber #1", bypass2faGracePeriodHours: 72 },
    createdAt: new Date(Date.now() - 1000 * 60 * 1350).toISOString(),
  },
  {
    id: "sec-020",
    eventType: "two_factor_disabled",
    severity: "medium",
    status: "investigating",
    title: "2FA Disabled by User",
    description: "User disabled SMS OTP authentication. System automatically notified user via recovery email.",
    actorId: "user_reg_88",
    actorName: "Abebe Bikila",
    actorEmail: "abebe@gmail.com",
    actorRole: "user",
    targetResource: "/profile/security",
    ipAddress: "196.188.33.71",
    city: "Addis Ababa",
    country: "Ethiopia",
    device: "Mobile",
    browser: "Samsung Internet 24",
    os: "Android 13",
    actionTaken: "allowed",
    metadata: { alertEmailSent: true, recommendedAction: "Re-enable Authenticator App" },
    isFlagged: false,
    createdAt: new Date(Date.now() - 1000 * 60 * 1450).toISOString(),
  },

  // ─── PAGE 2 SEED RECORDS (Items 21 to 40) ──────────────────────────────────
  {
    id: "sec-021",
    eventType: "unauthorized_access_attempt",
    severity: "high",
    status: "blocked",
    title: "Direct Database Seed Route Probed",
    description: "Public client triggered POST /api/seed without administrative master token.",
    actorName: "External Scanner",
    actorRole: "anonymous",
    targetResource: "/api/seed",
    ipAddress: "104.28.244.11",
    city: "London",
    country: "United Kingdom",
    device: "Bot",
    browser: "Mozilla/5.0 (Windows NT 10.0; Win64; x64)",
    os: "Windows 10",
    actionTaken: "blocked",
    metadata: { responseCode: 403, error: "Unauthorized access: master seed requires Super Admin privilege" },
    isFlagged: true,
    createdAt: new Date(Date.now() - 1000 * 60 * 1550).toISOString(),
  },
  {
    id: "sec-022",
    eventType: "login_success",
    severity: "info",
    status: "logged",
    title: "Customer Support Staff Login",
    description: "Staff moderator Miriam Yohannes signed into verification triage queue.",
    actorId: "user_staff_01",
    actorName: "Miriam Yohannes",
    actorEmail: "miriam@bizfinder.et",
    actorRole: "admin",
    targetResource: "/admin/support",
    ipAddress: "197.156.12.80",
    city: "Addis Ababa",
    country: "Ethiopia",
    device: "Desktop",
    browser: "Chrome 127",
    os: "Windows 11",
    actionTaken: "allowed",
    metadata: { department: "Moderation & Verification" },
    createdAt: new Date(Date.now() - 1000 * 60 * 1650).toISOString(),
  },
  {
    id: "sec-023",
    eventType: "brute_force_blocked",
    severity: "critical",
    status: "blocked",
    title: "SSH Gateway Port Scan Isolated",
    description: "Automated port scanner hitting perimeter firewall port 22 and 2222. Blocked at VPC security layer.",
    actorName: "Malicious IP Shodan Probe",
    actorRole: "anonymous",
    targetResource: "Perimeter VPC Firewall",
    ipAddress: "198.235.24.19",
    city: "Ashburn",
    country: "United States",
    device: "Server",
    browser: "Nmap Scripting Engine",
    os: "Linux",
    actionTaken: "blocked",
    metadata: { targetPorts: [22, 2222, 27017], protocol: "TCP SYN" },
    isFlagged: true,
    createdAt: new Date(Date.now() - 1000 * 60 * 1750).toISOString(),
  },
  {
    id: "sec-024",
    eventType: "role_elevated",
    severity: "high",
    status: "resolved",
    title: "City Admin Jurisdiction Assigned",
    description: "Country Admin Dawit Tsegaye designated Selamawit Assefa as City Admin for Hawassa.",
    actorId: "user_country_eth",
    actorName: "Dawit Tsegaye",
    actorEmail: "dawit.t@bizfinder.et",
    actorRole: "country_admin",
    targetResource: "/api/admin/geo-admins",
    ipAddress: "197.156.88.45",
    city: "Hawassa",
    country: "Ethiopia",
    device: "Desktop",
    browser: "Firefox 128",
    os: "Ubuntu Linux",
    actionTaken: "allowed",
    metadata: { appointee: "Selamawit Assefa", assignedCity: "Hawassa", assignedCountry: "Ethiopia" },
    resolvedBy: "Dawit Tsegaye",
    createdAt: new Date(Date.now() - 1000 * 60 * 1850).toISOString(),
  },
  {
    id: "sec-025",
    eventType: "password_changed",
    severity: "low",
    status: "logged",
    title: "Admin Password Rotation Complete",
    description: "Elena Vance completed mandatory 90-day administrative credential renewal.",
    actorId: "user_admin_02",
    actorName: "Elena Vance",
    actorEmail: "elena.vance@bizfinder.et",
    actorRole: "admin",
    targetResource: "/admin/settings",
    ipAddress: "196.188.22.8",
    city: "Addis Ababa",
    country: "Ethiopia",
    device: "Desktop",
    browser: "Firefox 129",
    os: "Windows 11",
    actionTaken: "allowed",
    metadata: { entropyScore: 92, satisfiesComplexityRules: true },
    createdAt: new Date(Date.now() - 1000 * 60 * 1950).toISOString(),
  },
  {
    id: "sec-026",
    eventType: "login_failed",
    severity: "low",
    status: "logged",
    title: "Failed MFA Verification Code",
    description: "User entered expired 6-digit TOTP code during sign-in challenge. Second attempt succeeded.",
    actorId: "user_owner_05",
    actorName: "Tewodros Kassahun",
    actorEmail: "teddy@musicland.et",
    actorRole: "owner",
    targetResource: "/sign-in/factor-two",
    ipAddress: "196.188.101.4",
    city: "Arada, Addis Ababa",
    country: "Ethiopia",
    device: "Mobile",
    browser: "Chrome Mobile 128",
    os: "Android 14",
    actionTaken: "2fa_challenged",
    metadata: { timeDriftSeconds: 45, retryAllowed: true },
    createdAt: new Date(Date.now() - 1000 * 60 * 2050).toISOString(),
  },
  {
    id: "sec-027",
    eventType: "ip_blocked",
    severity: "medium",
    status: "blocked",
    title: "Commercial Web Scraper Throttled",
    description: "Aggressive crawler extracting phone directory data at 120 requests/sec added to temporary rate limiter quarantine.",
    actorName: "Unregistered Search Bot",
    actorRole: "anonymous",
    targetResource: "/search",
    ipAddress: "141.98.11.200",
    city: "Vilnius",
    country: "Lithuania",
    device: "Bot",
    browser: "Scrapy/2.11.0",
    os: "Linux",
    actionTaken: "blocked",
    metadata: { violation: "Rate limit exceeded (120 req/s)", quotaEtb: 0 },
    isFlagged: true,
    createdAt: new Date(Date.now() - 1000 * 60 * 2150).toISOString(),
  },
  {
    id: "sec-028",
    eventType: "two_factor_enabled",
    severity: "info",
    status: "logged",
    title: "Hardware Security Key Registered",
    description: "Super Admin Alex Rivera registered physical FIDO2 / WebAuthn YubiKey 5C NFC for hardware-grade access.",
    actorId: "user_superadmin_01",
    actorName: "Alex Rivera",
    actorEmail: "alex.rivera@bizfinder.et",
    actorRole: "super_admin",
    targetResource: "/admin/settings/security",
    ipAddress: "197.156.104.12",
    city: "Addis Ababa",
    country: "Ethiopia",
    device: "Desktop",
    browser: "Chrome 128",
    os: "macOS Sonoma",
    actionTaken: "allowed",
    metadata: { keyModel: "Yubico YubiKey 5C NFC", aaguid: "cb69481e-8ff7-4039-93ec-0a2f3a9e2f49" },
    createdAt: new Date(Date.now() - 1000 * 60 * 2250).toISOString(),
  },
  {
    id: "sec-029",
    eventType: "login_success",
    severity: "info",
    status: "logged",
    title: "Regional Country Lead Authentication",
    description: "Kenya Regional Director Jomo Mwangi logged into Nairobi territory supervision dashboard.",
    actorId: "user_admin_kenya",
    actorName: "Jomo Mwangi",
    actorEmail: "jomo@bizfinder.ke",
    actorRole: "country_admin",
    targetResource: "/admin",
    ipAddress: "105.160.44.18",
    city: "Nairobi",
    country: "Kenya",
    device: "Desktop",
    browser: "Chrome 128",
    os: "Windows 11",
    actionTaken: "allowed",
    metadata: { jurisdiction: "Kenya (KE)", activeListingsNairobi: 420 },
    createdAt: new Date(Date.now() - 1000 * 60 * 2350).toISOString(),
  },
  {
    id: "sec-030",
    eventType: "unauthorized_access_attempt",
    severity: "high",
    status: "blocked",
    title: "CSRF Header Mismatch Detected",
    description: "Cross-site request forgery attempt blocked on business update endpoint. Missing valid CSRF origin token.",
    actorName: "Untrusted Web Client",
    actorRole: "user",
    targetResource: "/api/businesses/biz-1",
    ipAddress: "196.188.50.21",
    city: "Addis Ababa",
    country: "Ethiopia",
    device: "Desktop",
    browser: "Unknown Web Client",
    os: "Windows 10",
    actionTaken: "blocked",
    metadata: { originHeader: "http://malicious-redirect-site.com", expectedOrigin: "https://bizfinder.et" },
    isFlagged: true,
    createdAt: new Date(Date.now() - 1000 * 60 * 2450).toISOString(),
  },
  {
    id: "sec-031",
    eventType: "sensitive_data_export",
    severity: "medium",
    status: "logged",
    title: "Business Directory Backup Snapshot Taken",
    description: "System database automated cron generated encrypted Gzip backup archive of 48,920 business records.",
    actorName: "System Automated Cron",
    actorRole: "system",
    targetResource: "MongoDB Backup Engine",
    ipAddress: "127.0.0.1",
    city: "Internal Cluster",
    country: "Ethiopia",
    device: "Server",
    browser: "Antigravity Backup Runner",
    os: "Linux",
    actionTaken: "allowed",
    metadata: { backupSizeMb: 52.4, compression: "GZIP", storageBucket: "s3://bizfinder-backups-secure/daily" },
    createdAt: new Date(Date.now() - 1000 * 60 * 2550).toISOString(),
  },
  {
    id: "sec-032",
    eventType: "login_success",
    severity: "info",
    status: "logged",
    title: "Registered User Mobile App Sign-In",
    description: "Verified customer authenticated via Google OAuth SSO on BizFinder mobile directory.",
    actorId: "user_cust_104",
    actorName: "Genet Asrat",
    actorEmail: "genet.asrat@gmail.com",
    actorRole: "user",
    targetResource: "/sign-in",
    ipAddress: "196.188.18.99",
    city: "Yeka, Addis Ababa",
    country: "Ethiopia",
    device: "Mobile",
    browser: "Chrome Mobile 128",
    os: "Android 14",
    actionTaken: "allowed",
    metadata: { oauthProvider: "Google", verifiedEmail: true },
    createdAt: new Date(Date.now() - 1000 * 60 * 2650).toISOString(),
  },
  {
    id: "sec-033",
    eventType: "session_revoked",
    severity: "low",
    status: "resolved",
    title: "Owner Logout & Token Invalidation",
    description: "Business owner cleanly signed out of portal, flushing Clerk JWT session and local storage cache.",
    actorId: "user_owner_06",
    actorName: "Aster Aweke",
    actorEmail: "aster@awashcoffee.et",
    actorRole: "owner",
    targetResource: "/dashboard",
    ipAddress: "197.156.90.11",
    city: "Bole, Addis Ababa",
    country: "Ethiopia",
    device: "Desktop",
    browser: "Safari 17",
    os: "macOS Sonoma",
    actionTaken: "session_terminated",
    metadata: { voluntaryLogout: true },
    createdAt: new Date(Date.now() - 1000 * 60 * 2750).toISOString(),
  },
  {
    id: "sec-034",
    eventType: "api_key_generated",
    severity: "low",
    status: "logged",
    title: "Developer Read-Only API Key Issued",
    description: "Public directory integration API key issued for mobile app client analytics sync.",
    actorId: "user_superadmin_01",
    actorName: "Alex Rivera",
    actorEmail: "alex.rivera@bizfinder.et",
    actorRole: "super_admin",
    targetResource: "/api/admin/settings",
    ipAddress: "197.156.104.12",
    city: "Addis Ababa",
    country: "Ethiopia",
    device: "Desktop",
    browser: "Chrome 128",
    os: "macOS Sonoma",
    actionTaken: "allowed",
    metadata: { scope: ["directory.read"], rateLimitRpm: 600 },
    createdAt: new Date(Date.now() - 1000 * 60 * 2850).toISOString(),
  },
  {
    id: "sec-035",
    eventType: "login_failed",
    severity: "low",
    status: "logged",
    title: "Suspended Account Login Attempt",
    description: "Suspended spam user account attempted sign-in. Access politely denied with moderation reason.",
    actorName: "Blacklisted Spammer",
    actorEmail: "spammer@temporarymail.com",
    actorRole: "user",
    targetResource: "/sign-in",
    ipAddress: "194.26.29.11",
    city: "Moscow",
    country: "Russia",
    device: "Desktop",
    browser: "Chrome 126",
    os: "Windows 10",
    actionTaken: "account_locked",
    metadata: { banReason: "Repeated fraudulent business submission", banStatus: "permanent" },
    isFlagged: true,
    createdAt: new Date(Date.now() - 1000 * 60 * 2950).toISOString(),
  },
  {
    id: "sec-036",
    eventType: "firewall_rule_added",
    severity: "medium",
    status: "resolved",
    title: "SQL Injection Filter Rule Deployed",
    description: "Enhanced regular expression rule detecting UNION SELECT / OR 1=1 payloads in URL search query strings.",
    actorId: "user_admin_02",
    actorName: "Elena Vance",
    actorEmail: "elena.vance@bizfinder.et",
    actorRole: "admin",
    targetResource: "API Gateway WAF",
    ipAddress: "196.188.22.8",
    city: "Addis Ababa",
    country: "Ethiopia",
    device: "Desktop",
    browser: "Firefox 129",
    os: "Windows 11",
    actionTaken: "allowed",
    metadata: { ruleId: "WAF-SQLI-004", matchTarget: "queryString" },
    createdAt: new Date(Date.now() - 1000 * 60 * 3050).toISOString(),
  },
  {
    id: "sec-037",
    eventType: "brute_force_blocked",
    severity: "high",
    status: "blocked",
    title: "Password Reset Abuse Mitigated",
    description: "Triggered rate limiter on 'Forgot Password' endpoint after 20 emails dispatched to single domain in 2 minutes.",
    actorName: "Anonymous Mail Spammer",
    actorRole: "anonymous",
    targetResource: "/sign-in/reset-password",
    ipAddress: "45.154.255.80",
    city: "Kyiv",
    country: "Ukraine",
    device: "Bot",
    browser: "Python aiohttp",
    os: "Linux",
    actionTaken: "blocked",
    metadata: { attemptsCount: 20, throttleDurationMins: 60 },
    isFlagged: true,
    createdAt: new Date(Date.now() - 1000 * 60 * 3150).toISOString(),
  },
  {
    id: "sec-038",
    eventType: "login_success",
    severity: "info",
    status: "logged",
    title: "UK Regional City Admin Session",
    description: "London City Lead Arthur Pendelton authenticated to supervise UK directory listings.",
    actorId: "user_admin_london",
    actorName: "Arthur Pendelton",
    actorEmail: "arthur@bizfinder.co.uk",
    actorRole: "city_admin",
    targetResource: "/admin",
    ipAddress: "82.165.197.1",
    city: "London",
    country: "United Kingdom",
    device: "Desktop",
    browser: "Safari 17.5",
    os: "macOS Sonoma",
    actionTaken: "allowed",
    metadata: { city: "London", country: "United Kingdom" },
    createdAt: new Date(Date.now() - 1000 * 60 * 3250).toISOString(),
  },
  {
    id: "sec-039",
    eventType: "ddos_mitigated",
    severity: "medium",
    status: "blocked",
    title: "SYN Flood Suppressed at Gateway",
    description: "Perimeter load balancer automatically absorbed and dropped 12,000 invalid TCP SYN packets.",
    actorName: "Mirai Botnet Fragment",
    actorRole: "system",
    targetResource: "Core Reverse Proxy",
    ipAddress: "193.106.191.0/24",
    city: "Distributed Subnet",
    country: "Global",
    device: "Bot",
    browser: "Raw Socket",
    os: "Unknown",
    actionTaken: "blocked",
    metadata: { droppedPackets: 12000, bandwidthPeakMbps: 85 },
    isFlagged: true,
    createdAt: new Date(Date.now() - 1000 * 60 * 3350).toISOString(),
  },
  {
    id: "sec-040",
    eventType: "role_elevated",
    severity: "high",
    status: "resolved",
    title: "Support Agent Granted Ticket Resolver Role",
    description: "Granted senior tier permission to resolve reported business claims and disputed reviews.",
    actorId: "user_superadmin_01",
    actorName: "Alex Rivera",
    actorEmail: "alex.rivera@bizfinder.et",
    actorRole: "super_admin",
    targetResource: "/admin/support",
    ipAddress: "197.156.104.12",
    city: "Addis Ababa",
    country: "Ethiopia",
    device: "Desktop",
    browser: "Chrome 128",
    os: "macOS Sonoma",
    actionTaken: "allowed",
    metadata: { assignedAgent: "Hanna Girma", newScope: "support.resolve_claims" },
    resolvedBy: "Alex Rivera",
    createdAt: new Date(Date.now() - 1000 * 60 * 3450).toISOString(),
  },

  // ─── PAGE 3 SEED RECORDS (Items 41 to 52) ──────────────────────────────────
  {
    id: "sec-041",
    eventType: "login_success",
    severity: "info",
    status: "logged",
    title: "Business Owner Storefront Update Session",
    description: "Owner of Bole Medhanialem Pharmacy accessed listing manager to update 24/7 night shift schedule.",
    actorId: "user_owner_07",
    actorName: "Dr. Henok Tadesse",
    actorEmail: "henok@bolepharmacy.et",
    actorRole: "owner",
    targetResource: "/dashboard/management/hours",
    ipAddress: "196.188.75.14",
    city: "Bole, Addis Ababa",
    country: "Ethiopia",
    device: "Desktop",
    browser: "Chrome 128",
    os: "Windows 11",
    actionTaken: "allowed",
    metadata: { businessName: "Bole Medhanialem Pharmacy" },
    createdAt: new Date(Date.now() - 1000 * 60 * 3550).toISOString(),
  },
  {
    id: "sec-042",
    eventType: "unauthorized_access_attempt",
    severity: "critical",
    status: "blocked",
    title: "Cross-Tenant Business Claim Hijack Prevented",
    description: "Unverified user submitted fraudulent ownership claim payload attempting to hijack verified brand listing.",
    actorId: "user_malicious_claim",
    actorName: "Falsified Claimant",
    actorEmail: "claimant@phishmail.org",
    actorRole: "user",
    targetResource: "/api/claims",
    ipAddress: "197.156.32.90",
    city: "Addis Ababa",
    country: "Ethiopia",
    device: "Desktop",
    browser: "Chrome 127",
    os: "Windows 10",
    actionTaken: "flagged",
    metadata: { targetBusiness: "Commercial Bank of Ethiopia Main Branch", flagReason: "No trade license proof" },
    isFlagged: true,
    resolvedBy: "Security Automation",
    createdAt: new Date(Date.now() - 1000 * 60 * 3650).toISOString(),
  },
  {
    id: "sec-043",
    eventType: "password_changed",
    severity: "low",
    status: "logged",
    title: "Customer Profile Password Updated",
    description: "Customer completed routine security password change via profile settings.",
    actorId: "user_cust_209",
    actorName: "Almaz Kebede",
    actorEmail: "almaz.kebede@yahoo.com",
    actorRole: "user",
    targetResource: "/profile",
    ipAddress: "196.188.14.82",
    city: "Hawassa",
    country: "Ethiopia",
    device: "Mobile",
    browser: "Safari iOS 17",
    os: "iOS 17",
    actionTaken: "allowed",
    metadata: { authStrength: "Satisfactory" },
    createdAt: new Date(Date.now() - 1000 * 60 * 3750).toISOString(),
  },
  {
    id: "sec-044",
    eventType: "two_factor_enabled",
    severity: "info",
    status: "logged",
    title: "SMS Multi-Factor Backup Channel Added",
    description: "Added verified phone number +251 91 100 2233 as fallback security verification channel.",
    actorId: "user_owner_08",
    actorName: "Kassahun Desta",
    actorEmail: "kassahun@habeshahotel.et",
    actorRole: "owner",
    targetResource: "/dashboard/settings/security",
    ipAddress: "197.156.99.12",
    city: "Addis Ababa",
    country: "Ethiopia",
    device: "Desktop",
    browser: "Chrome 128",
    os: "Windows 11",
    actionTaken: "allowed",
    metadata: { carrier: "Ethio Telecom", verifiedSmsCode: true },
    createdAt: new Date(Date.now() - 1000 * 60 * 3850).toISOString(),
  },
  {
    id: "sec-045",
    eventType: "ip_blocked",
    severity: "high",
    status: "blocked",
    title: "Spam Bot Farm Subnet Blacklisted",
    description: "Banned IP range generating 500+ fake review spam submissions across multiple restaurants.",
    actorName: "Automated Review Spammer",
    actorRole: "anonymous",
    targetResource: "/api/reviews",
    ipAddress: "185.191.171.0/24",
    city: "Prague",
    country: "Czechia",
    device: "Bot",
    browser: "Headless Selenium",
    os: "Linux",
    actionTaken: "quarantined",
    metadata: { spamReviewsIntercepted: 520, autoDeleted: true },
    isFlagged: true,
    resolvedBy: "Security Automation",
    createdAt: new Date(Date.now() - 1000 * 60 * 3950).toISOString(),
  },
  {
    id: "sec-046",
    eventType: "login_success",
    severity: "info",
    status: "logged",
    title: "Super Admin Terminal CLI Session",
    description: "Alex Rivera authenticated via SSH key to manage database indexing and deployment maintenance.",
    actorId: "user_superadmin_01",
    actorName: "Alex Rivera",
    actorEmail: "alex.rivera@bizfinder.et",
    actorRole: "super_admin",
    targetResource: "Core Terminal API",
    ipAddress: "197.156.104.12",
    city: "Addis Ababa",
    country: "Ethiopia",
    device: "Desktop",
    browser: "OpenSSH_9.6p1",
    os: "macOS Sonoma",
    actionTaken: "allowed",
    metadata: { keyAlgorithm: "ED25519", authMethod: "Public Key" },
    createdAt: new Date(Date.now() - 1000 * 60 * 4050).toISOString(),
  },
  {
    id: "sec-047",
    eventType: "brute_force_blocked",
    severity: "medium",
    status: "blocked",
    title: "Admin Panel URL Path Probing Blocked",
    description: "Client systematically probing legacy paths: /wp-admin, /phpmyadmin, /env. Throttled and quarantined.",
    actorName: "Generic Internet Scanner",
    actorRole: "anonymous",
    targetResource: "/wp-admin",
    ipAddress: "80.94.95.88",
    city: "Amsterdam",
    country: "Netherlands",
    device: "Bot",
    browser: "Zgrab/0.x",
    os: "Linux",
    actionTaken: "blocked",
    metadata: { probePaths: ["/wp-admin", "/phpmyadmin", "/.env", "/backup.sql"] },
    isFlagged: true,
    createdAt: new Date(Date.now() - 1000 * 60 * 4150).toISOString(),
  },
  {
    id: "sec-048",
    eventType: "sensitive_data_export",
    severity: "low",
    status: "logged",
    title: "User Profile GDPR Archive Exported",
    description: "Verified customer requested complete data takeaway archive under platform privacy transparency rules.",
    actorId: "user_cust_311",
    actorName: "Solomon Getachew",
    actorEmail: "solomon.g@gmail.com",
    actorRole: "user",
    targetResource: "/profile/privacy",
    ipAddress: "196.188.40.19",
    city: "Addis Ababa",
    country: "Ethiopia",
    device: "Desktop",
    browser: "Chrome 128",
    os: "Windows 11",
    actionTaken: "allowed",
    metadata: { archiveFormat: "JSON", deliveredViaEmail: true },
    createdAt: new Date(Date.now() - 1000 * 60 * 4250).toISOString(),
  },
  {
    id: "sec-049",
    eventType: "login_success",
    severity: "info",
    status: "logged",
    title: "City Admin Logged In: Bahir Dar",
    description: "Bahir Dar City Admin Hailemariam Desalegn connected to review verified lakefront resort listings.",
    actorId: "user_admin_bahirdar",
    actorName: "Hailemariam Desalegn",
    actorEmail: "hailemariam@bizfinder.et",
    actorRole: "city_admin",
    targetResource: "/admin",
    ipAddress: "196.188.62.77",
    city: "Bahir Dar",
    country: "Ethiopia",
    device: "Desktop",
    browser: "Firefox 128",
    os: "Windows 10",
    actionTaken: "allowed",
    metadata: { city: "Bahir Dar", state: "Amhara" },
    createdAt: new Date(Date.now() - 1000 * 60 * 4350).toISOString(),
  },
  {
    id: "sec-050",
    eventType: "two_factor_enabled",
    severity: "info",
    status: "logged",
    title: "Staff Member Mandatory 2FA Enforced",
    description: "Support staff member completed mandatory 2FA enrollment required by Super Admin platform policy.",
    actorId: "user_staff_02",
    actorName: "Senait Gebre",
    actorEmail: "senait@bizfinder.et",
    actorRole: "admin",
    targetResource: "/admin/settings",
    ipAddress: "197.156.12.82",
    city: "Addis Ababa",
    country: "Ethiopia",
    device: "Desktop",
    browser: "Chrome 128",
    os: "Windows 11",
    actionTaken: "allowed",
    metadata: { policyEnforcedBy: "Platform Security Standard v2.4" },
    createdAt: new Date(Date.now() - 1000 * 60 * 4450).toISOString(),
  },
  {
    id: "sec-051",
    eventType: "session_revoked",
    severity: "medium",
    status: "resolved",
    title: "All Stale Sessions Terminated",
    description: "User triggered 'Sign out of all other devices' after detecting unrecognized login notification.",
    actorId: "user_owner_09",
    actorName: "Lidya Mesfin",
    actorEmail: "lidya@addisfood.et",
    actorRole: "owner",
    targetResource: "/dashboard/settings/security",
    ipAddress: "197.156.104.55",
    city: "Bole, Addis Ababa",
    country: "Ethiopia",
    device: "Desktop",
    browser: "Chrome 128",
    os: "macOS",
    actionTaken: "session_terminated",
    metadata: { revokedCount: 3, securityNoticeSent: true },
    createdAt: new Date(Date.now() - 1000 * 60 * 4550).toISOString(),
  },
  {
    id: "sec-052",
    eventType: "firewall_rule_added",
    severity: "low",
    status: "resolved",
    title: "Security Shield Health Verification Nominal",
    description: "Automated end-to-end security audit passed. 0 critical vulnerabilities detected. Shield status: 100% Active.",
    actorName: "BizFinder Security Engine",
    actorRole: "system",
    targetResource: "System Integrity Monitor",
    ipAddress: "127.0.0.1",
    city: "Addis Ababa",
    country: "Ethiopia",
    device: "Server",
    browser: "Security Probe",
    os: "Linux",
    actionTaken: "allowed",
    metadata: { passedChecks: 38, zeroDayAlerts: 0, complianceRate: "100%" },
    createdAt: new Date(Date.now() - 1000 * 60 * 4650).toISOString(),
  },
];
