import { ISupportTicket } from "@/types/ticket";

export const SEED_TICKETS: ISupportTicket[] = [
  {
    id: "TCK-9001",
    subject: "Fast-track municipal business license verification",
    category: "verification",
    priority: "high",
    status: "open",
    userId: "user_owner_dawit",
    userName: "Dawit Solomon",
    userEmail: "dawit@abyssiniacatering.et",
    userPhone: "+251 91 123 4567",
    userRole: "owner",
    businessId: "biz-1",
    businessName: "Abyssinia Gourmet Cafe & Roastery",
    assignedAdmin: "Admin Elena",
    assignedAdminId: "admin_elena",
    tags: ["license", "verification", "urgent"],
    messages: [
      {
        id: "msg-9001-1",
        senderId: "user_owner_dawit",
        senderName: "Dawit Solomon",
        senderRole: "owner",
        message:
          "Hello Support Team, we recently renewed our trade certificate and TIN registration with the Addis Ababa Bureau of Trade. We submitted the PDF certificate yesterday, could you please verify and update our verified checkmark?",
        createdAt: "2026-09-08T09:15:00.000Z",
      },
    ],
    lastReply: "Dawit Solomon: Hello Support Team, we recently renewed our trade certificate...",
    lastReplyAt: "2026-09-08T09:15:00.000Z",
    city: "Addis Ababa",
    country: "Ethiopia",
    createdAt: "2026-09-08T09:15:00.000Z",
    updatedAt: "2026-09-08T09:15:00.000Z",
  },
  {
    id: "TCK-9002",
    subject: "Telebirr merchant QR settlement delay inquiry",
    category: "billing",
    priority: "high",
    status: "in_progress",
    userId: "user_owner_sara",
    userName: "Sara Alemayehu",
    userEmail: "sara@lucyrestaurant.et",
    userPhone: "+251 92 345 6789",
    userRole: "owner",
    businessId: "biz-2",
    businessName: "Lucy Traditional Dining",
    assignedAdmin: "Admin Marcus",
    assignedAdminId: "admin_marcus",
    tags: ["telebirr", "settlement", "finance"],
    messages: [
      {
        id: "msg-9002-1",
        senderId: "user_owner_sara",
        senderName: "Sara Alemayehu",
        senderRole: "owner",
        message:
          "Good afternoon. Our weekend QR transactions from Sept 5-6 haven't appeared in our direct bank disbursement account yet. Could you check the transaction status on your gateway side?",
        createdAt: "2026-09-07T11:20:00.000Z",
      },
      {
        id: "msg-9002-2",
        senderId: "admin_marcus",
        senderName: "Marcus Vance",
        senderRole: "admin",
        message:
          "Hi Sara, we have contacted Ethio Telecom's Telebirr integration switch. Batches for transaction references TB-99481 to TB-99512 are being cleared today at 14:00 EAT.",
        createdAt: "2026-09-07T13:45:00.000Z",
      },
    ],
    lastReply: "Marcus Vance: Hi Sara, we have contacted Ethio Telecom's Telebirr integration...",
    lastReplyAt: "2026-09-07T13:45:00.000Z",
    city: "Addis Ababa",
    country: "Ethiopia",
    createdAt: "2026-09-07T11:20:00.000Z",
    updatedAt: "2026-09-07T13:45:00.000Z",
  },
  {
    id: "TCK-9003",
    subject: "Duplicate business listing merge request",
    category: "listing",
    priority: "medium",
    status: "waiting_on_customer",
    userId: "user_owner_tamrat",
    userName: "Tamrat Bekele",
    userEmail: "tamrat@redseaimport.et",
    userPhone: "+251 91 888 1234",
    userRole: "owner",
    businessId: "biz-3",
    businessName: "Red Sea Logistics & Forwarding",
    assignedAdmin: "Admin Elena",
    assignedAdminId: "admin_elena",
    tags: ["merge", "duplicate", "listing"],
    messages: [
      {
        id: "msg-9003-1",
        senderId: "user_owner_tamrat",
        senderName: "Tamrat Bekele",
        senderRole: "owner",
        message:
          "We found another older listing under 'Red Sea Forwarding PLC' in Kirkos subcity that was created before our claim. Can you merge the reviews into our official verified profile?",
        createdAt: "2026-09-06T08:30:00.000Z",
      },
      {
        id: "msg-9003-2",
        senderId: "admin_elena",
        senderName: "Elena Rostova",
        senderRole: "admin",
        message:
          "Hello Tamrat, we can certainly merge them. Please provide the business registration number matching both addresses or reply with confirmation that both phone numbers belong to your office.",
        createdAt: "2026-09-06T10:15:00.000Z",
      },
    ],
    lastReply: "Elena Rostova: Hello Tamrat, we can certainly merge them. Please provide...",
    lastReplyAt: "2026-09-06T10:15:00.000Z",
    city: "Addis Ababa",
    country: "Ethiopia",
    createdAt: "2026-09-06T08:30:00.000Z",
    updatedAt: "2026-09-06T10:15:00.000Z",
  },
  {
    id: "TCK-9004",
    subject: "Google Maps GPS coordinates pin fine-tuning",
    category: "technical",
    priority: "low",
    status: "resolved",
    userId: "user_owner_marta",
    userName: "Marta Haile",
    userEmail: "marta@entotolodge.et",
    userPhone: "+251 93 456 7890",
    userRole: "owner",
    businessId: "biz-4",
    businessName: "Entoto Mountain Resort Lodge",
    assignedAdmin: "Admin Marcus",
    assignedAdminId: "admin_marcus",
    tags: ["maps", "gps", "pin"],
    messages: [
      {
        id: "msg-9004-1",
        senderId: "user_owner_marta",
        senderName: "Marta Haile",
        senderRole: "owner",
        message:
          "Our map pin is positioned slightly off by 200 meters near the park entrance instead of the main lodge gate. Lat 9.0821, Lng 38.7490. Can this be updated?",
        createdAt: "2026-09-05T14:10:00.000Z",
      },
      {
        id: "msg-9004-2",
        senderId: "admin_marcus",
        senderName: "Marcus Vance",
        senderRole: "admin",
        message:
          "Hi Marta! Coordinates have been updated in the master geospatial index and cached tiles have been purged. You can verify on your profile page.",
        createdAt: "2026-09-05T15:20:00.000Z",
      },
    ],
    lastReply: "Marcus Vance: Hi Marta! Coordinates have been updated in the master...",
    lastReplyAt: "2026-09-05T15:20:00.000Z",
    city: "Addis Ababa",
    country: "Ethiopia",
    createdAt: "2026-09-05T14:10:00.000Z",
    updatedAt: "2026-09-05T15:20:00.000Z",
  },
  {
    id: "TCK-9005",
    subject: "Spam review removal appeal with CCTV evidence",
    category: "dispute",
    priority: "critical",
    status: "in_progress",
    userId: "user_owner_kassahun",
    userName: "Kassahun Tadesse",
    userEmail: "kassahun@baleecotours.et",
    userPhone: "+251 94 567 8901",
    userRole: "owner",
    businessId: "biz-5",
    businessName: "Bale Mountain Eco Tours",
    assignedAdmin: "Alex Rivera (Super Admin)",
    assignedAdminId: "admin_super",
    tags: ["moderation", "dispute", "cctv"],
    messages: [
      {
        id: "msg-9005-1",
        senderId: "user_owner_kassahun",
        senderName: "Kassahun Tadesse",
        senderRole: "owner",
        message:
          "A competitor account posted 4 identical 1-star reviews within 5 minutes claiming non-existent booking dates. We have full booking logs attached for your moderation team.",
        createdAt: "2026-09-04T16:00:00.000Z",
      },
      {
        id: "msg-9005-2",
        senderId: "admin_super",
        senderName: "Alex Rivera",
        senderRole: "super_admin",
        message:
          "Thank you Kassahun. Our fraud heuristics confirmed all 4 accounts originated from the same foreign proxy IP. The reviews have been placed in quarantine pending permanent removal.",
        createdAt: "2026-09-04T17:30:00.000Z",
      },
    ],
    lastReply: "Alex Rivera: Thank you Kassahun. Our fraud heuristics confirmed...",
    lastReplyAt: "2026-09-04T17:30:00.000Z",
    city: "Robe",
    country: "Ethiopia",
    createdAt: "2026-09-04T16:00:00.000Z",
    updatedAt: "2026-09-04T17:30:00.000Z",
  },
  {
    id: "TCK-9006",
    subject: "Request for custom subcategory: Specialty Green Coffee Exporter",
    category: "general",
    priority: "low",
    status: "closed",
    userId: "user_owner_biruk",
    userName: "Biruk Mengistu",
    userEmail: "biruk@sidamacoffee.et",
    userPhone: "+251 91 333 4455",
    userRole: "owner",
    businessId: "biz-6",
    businessName: "Sidama Highland Coffee Union",
    assignedAdmin: "Admin Elena",
    assignedAdminId: "admin_elena",
    tags: ["category", "coffee", "export"],
    messages: [
      {
        id: "msg-9006-1",
        senderId: "user_owner_biruk",
        senderName: "Biruk Mengistu",
        senderRole: "owner",
        message:
          "Could we add a dedicated subcategory for 'Specialty Green Coffee Exporters' under Agriculture & Agro-processing? It will help international buyers find certified washing stations.",
        createdAt: "2026-09-03T10:00:00.000Z",
      },
      {
        id: "msg-9006-2",
        senderId: "admin_elena",
        senderName: "Elena Rostova",
        senderRole: "admin",
        message:
          "Great suggestion! We have created the subcategory under Agriculture → Coffee & Tea Exports. You can now reclassify your listing.",
        createdAt: "2026-09-03T11:45:00.000Z",
      },
    ],
    lastReply: "Elena Rostova: Great suggestion! We have created the subcategory...",
    lastReplyAt: "2026-09-03T11:45:00.000Z",
    city: "Hawassa",
    country: "Ethiopia",
    createdAt: "2026-09-03T10:00:00.000Z",
    updatedAt: "2026-09-03T11:45:00.000Z",
  },
  {
    id: "TCK-9007",
    subject: "Annual Pro Tier subscription invoice VAT receipt issuance",
    category: "billing",
    priority: "medium",
    status: "resolved",
    userId: "user_owner_dawit",
    userName: "Dawit Solomon",
    userEmail: "dawit@abyssiniacatering.et",
    userPhone: "+251 91 123 4567",
    userRole: "owner",
    businessId: "biz-1",
    businessName: "Abyssinia Gourmet Cafe & Roastery",
    assignedAdmin: "Admin Marcus",
    assignedAdminId: "admin_marcus",
    tags: ["invoice", "vat", "tax"],
    messages: [
      {
        id: "msg-9007-1",
        senderId: "user_owner_dawit",
        senderName: "Dawit Solomon",
        senderRole: "owner",
        message:
          "We need an official VAT withholder invoice receipt with BizFinder's Ethiopian TIN for our annual accounting closure.",
        createdAt: "2026-09-02T13:00:00.000Z",
      },
      {
        id: "msg-9007-2",
        senderId: "admin_marcus",
        senderName: "Marcus Vance",
        senderRole: "admin",
        message:
          "Official stamped PDF invoice INV-2026-089 has been attached and emailed to your accounting department.",
        createdAt: "2026-09-02T14:30:00.000Z",
      },
    ],
    lastReply: "Marcus Vance: Official stamped PDF invoice INV-2026-089 has been...",
    lastReplyAt: "2026-09-02T14:30:00.000Z",
    city: "Addis Ababa",
    country: "Ethiopia",
    createdAt: "2026-09-02T13:00:00.000Z",
    updatedAt: "2026-09-02T14:30:00.000Z",
  },
  {
    id: "TCK-9008",
    subject: "Multi-branch synchronization for Bole and Kazanchis locations",
    category: "technical",
    priority: "medium",
    status: "open",
    userId: "user_owner_samson",
    userName: "Samson Girma",
    userEmail: "samson@habeshapharma.et",
    userPhone: "+251 92 111 2233",
    userRole: "owner",
    businessId: "biz-8",
    businessName: "Habesha Chain Pharmacies",
    assignedAdmin: "Unassigned",
    tags: ["branches", "sync", "multilocation"],
    messages: [
      {
        id: "msg-9008-1",
        senderId: "user_owner_samson",
        senderName: "Samson Girma",
        senderRole: "owner",
        message:
          "We operate 5 branches in Addis Ababa. When we update night-shift duty hours for Bole branch, does it override the Kazanchis 24/7 hours?",
        createdAt: "2026-09-02T09:00:00.000Z",
      },
    ],
    lastReply: "Samson Girma: We operate 5 branches in Addis Ababa. When we update...",
    lastReplyAt: "2026-09-02T09:00:00.000Z",
    city: "Addis Ababa",
    country: "Ethiopia",
    createdAt: "2026-09-02T09:00:00.000Z",
    updatedAt: "2026-09-02T09:00:00.000Z",
  },
  {
    id: "TCK-9009",
    subject: "Two-factor authentication phone reset assistance",
    category: "account",
    priority: "high",
    status: "in_progress",
    userId: "user_owner_yared",
    userName: "Yared Tesfaye",
    userEmail: "yared@bluenilecrafts.et",
    userPhone: "+251 91 999 8877",
    userRole: "owner",
    businessId: "biz-9",
    businessName: "Blue Nile Artisan Crafts",
    assignedAdmin: "Admin Elena",
    assignedAdminId: "admin_elena",
    tags: ["2fa", "security", "login"],
    messages: [
      {
        id: "msg-9009-1",
        senderId: "user_owner_yared",
        senderName: "Yared Tesfaye",
        senderRole: "owner",
        message:
          "I changed my primary Safaricom SIM card and cannot receive the SMS verification code for my business dashboard login.",
        createdAt: "2026-09-01T15:40:00.000Z",
      },
      {
        id: "msg-9009-2",
        senderId: "admin_elena",
        senderName: "Elena Rostova",
        senderRole: "admin",
        message:
          "Identity verification initiated via backup email. Please check your inbox for a one-time cryptographic authorization link.",
        createdAt: "2026-09-01T16:10:00.000Z",
      },
    ],
    lastReply: "Elena Rostova: Identity verification initiated via backup email...",
    lastReplyAt: "2026-09-01T16:10:00.000Z",
    city: "Bahir Dar",
    country: "Ethiopia",
    createdAt: "2026-09-01T15:40:00.000Z",
    updatedAt: "2026-09-01T16:10:00.000Z",
  },
  {
    id: "TCK-9010",
    subject: "Sponsored search banner placement timing clarification",
    category: "billing",
    priority: "low",
    status: "resolved",
    userId: "user_owner_selam",
    userName: "Selamawit Desta",
    userEmail: "selam@zenithspa.et",
    userPhone: "+251 91 222 3344",
    userRole: "owner",
    businessId: "biz-10",
    businessName: "Zenith Wellness & Spa",
    assignedAdmin: "Admin Marcus",
    assignedAdminId: "admin_marcus",
    tags: ["ad", "banner", "campaign"],
    messages: [
      {
        id: "msg-9010-1",
        senderId: "user_owner_selam",
        senderName: "Selamawit Desta",
        senderRole: "owner",
        message:
          "Our campaign 'Meskel Holiday Spa Packages' was approved. Does the banner rotate every 10 seconds or on page reloads?",
        createdAt: "2026-09-01T08:15:00.000Z",
      },
      {
        id: "msg-9010-2",
        senderId: "admin_marcus",
        senderName: "Marcus Vance",
        senderRole: "admin",
        message:
          "Hello Selamawit! Spotlight banners rotate based on user search category relevance with a 12-second carousel cadence.",
        createdAt: "2026-09-01T09:30:00.000Z",
      },
    ],
    lastReply: "Marcus Vance: Hello Selamawit! Spotlight banners rotate based on...",
    lastReplyAt: "2026-09-01T09:30:00.000Z",
    city: "Addis Ababa",
    country: "Ethiopia",
    createdAt: "2026-09-01T08:15:00.000Z",
    updatedAt: "2026-09-01T09:30:00.000Z",
  },
  {
    id: "TCK-9011",
    subject: "High-resolution 4K menu photo upload error (HTTP 413)",
    category: "technical",
    priority: "medium",
    status: "resolved",
    userId: "user_owner_dawit",
    userName: "Dawit Solomon",
    userEmail: "dawit@abyssiniacatering.et",
    userPhone: "+251 91 123 4567",
    userRole: "owner",
    businessId: "biz-1",
    businessName: "Abyssinia Gourmet Cafe & Roastery",
    assignedAdmin: "Admin Marcus",
    assignedAdminId: "admin_marcus",
    tags: ["upload", "photo", "filesize"],
    messages: [
      {
        id: "msg-9011-1",
        senderId: "user_owner_dawit",
        senderName: "Dawit Solomon",
        senderRole: "owner",
        message:
          "When uploading our 12MB panoramic terrace photo, the media uploader returned 'File too large'. What is the current limit?",
        createdAt: "2026-08-31T14:00:00.000Z",
      },
      {
        id: "msg-9011-2",
        senderId: "admin_marcus",
        senderName: "Marcus Vance",
        senderRole: "admin",
        message:
          "The limit has been updated to 25MB with automatic WebP compression on ingest. You can re-upload your photo now!",
        createdAt: "2026-08-31T15:10:00.000Z",
      },
    ],
    lastReply: "Marcus Vance: The limit has been updated to 25MB with automatic...",
    lastReplyAt: "2026-08-31T15:10:00.000Z",
    city: "Addis Ababa",
    country: "Ethiopia",
    createdAt: "2026-08-31T14:00:00.000Z",
    updatedAt: "2026-08-31T15:10:00.000Z",
  },
  {
    id: "TCK-9012",
    subject: "Trademark infringement claim on business branding",
    category: "dispute",
    priority: "critical",
    status: "in_progress",
    userId: "user_owner_fasil",
    userName: "Fasil Kebede",
    userEmail: "fasil@habeshagrill.et",
    userPhone: "+251 92 777 6655",
    userRole: "owner",
    businessId: "biz-12",
    businessName: "Habesha National Grill",
    assignedAdmin: "Alex Rivera (Super Admin)",
    assignedAdminId: "admin_super",
    tags: ["trademark", "legal", "compliance"],
    messages: [
      {
        id: "msg-9012-1",
        senderId: "user_owner_fasil",
        senderName: "Fasil Kebede",
        senderRole: "owner",
        message:
          "A competitor in Dire Dawa registered an identical trademark name and copied our logo. We have registered our IP with EIPO.",
        createdAt: "2026-08-30T10:20:00.000Z",
      },
      {
        id: "msg-9012-2",
        senderId: "admin_super",
        senderName: "Alex Rivera",
        senderRole: "super_admin",
        message:
          "Case referred to platform legal counsel. We have requested trademark registration documents from the infringing party with a 48-hour response window.",
        createdAt: "2026-08-30T12:00:00.000Z",
      },
    ],
    lastReply: "Alex Rivera: Case referred to platform legal counsel. We have...",
    lastReplyAt: "2026-08-30T12:00:00.000Z",
    city: "Dire Dawa",
    country: "Ethiopia",
    createdAt: "2026-08-30T10:20:00.000Z",
    updatedAt: "2026-08-30T12:00:00.000Z",
  },
  {
    id: "TCK-9013",
    subject: "International credit card payment gateway decline",
    category: "billing",
    priority: "medium",
    status: "waiting_on_customer",
    userId: "user_owner_john",
    userName: "Johnathan Smith",
    userEmail: "jsmith@nairobiexplore.com",
    userPhone: "+254 71 234 5678",
    userRole: "owner",
    businessId: "biz-13",
    businessName: "East Africa Safaris Ltd",
    assignedAdmin: "Admin Elena",
    assignedAdminId: "admin_elena",
    tags: ["stripe", "visa", "usd"],
    messages: [
      {
        id: "msg-9013-1",
        senderId: "user_owner_john",
        senderName: "Johnathan Smith",
        senderRole: "owner",
        message:
          "Our UK Visa corporate card was declined when purchasing the regional East Africa directory highlight. Does the gateway support 3D Secure v2?",
        createdAt: "2026-08-29T16:45:00.000Z",
      },
      {
        id: "msg-9013-2",
        senderId: "admin_elena",
        senderName: "Elena Rostova",
        senderRole: "admin",
        message:
          "Yes, 3DS v2 is fully supported via Stripe. The decline code indicates 'do_not_honor' from your card issuing bank for international transactions. Please authorize African regional transactions with your bank.",
        createdAt: "2026-08-29T17:30:00.000Z",
      },
    ],
    lastReply: "Elena Rostova: Yes, 3DS v2 is fully supported via Stripe. The decline...",
    lastReplyAt: "2026-08-29T17:30:00.000Z",
    city: "Nairobi",
    country: "Kenya",
    createdAt: "2026-08-29T16:45:00.000Z",
    updatedAt: "2026-08-29T17:30:00.000Z",
  },
  {
    id: "TCK-9014",
    subject: "Staff manager role delegation without full financial access",
    category: "account",
    priority: "low",
    status: "resolved",
    userId: "user_owner_sara",
    userName: "Sara Alemayehu",
    userEmail: "sara@lucyrestaurant.et",
    userPhone: "+251 92 345 6789",
    userRole: "owner",
    businessId: "biz-2",
    businessName: "Lucy Traditional Dining",
    assignedAdmin: "Admin Marcus",
    assignedAdminId: "admin_marcus",
    tags: ["roles", "staff", "permissions"],
    messages: [
      {
        id: "msg-9014-1",
        senderId: "user_owner_sara",
        senderName: "Sara Alemayehu",
        senderRole: "owner",
        message:
          "Can our head chef respond to customer reviews without having permission to view revenue analytics or change bank settlement details?",
        createdAt: "2026-08-28T11:00:00.000Z",
      },
      {
        id: "msg-9014-2",
        senderId: "admin_marcus",
        senderName: "Marcus Vance",
        senderRole: "admin",
        message:
          "Yes! In your Dashboard → Settings → Team, invite them with the 'Community Manager' role which restricts billing and banking.",
        createdAt: "2026-08-28T12:15:00.000Z",
      },
    ],
    lastReply: "Marcus Vance: Yes! In your Dashboard → Settings → Team, invite them...",
    lastReplyAt: "2026-08-28T12:15:00.000Z",
    city: "Addis Ababa",
    country: "Ethiopia",
    createdAt: "2026-08-28T11:00:00.000Z",
    updatedAt: "2026-08-28T12:15:00.000Z",
  },
  {
    id: "TCK-9015",
    subject: "Webhook delivery failure for lead inquiry notifications",
    category: "technical",
    priority: "high",
    status: "open",
    userId: "user_owner_tariku",
    userName: "Tariku Wolde",
    userEmail: "tariku@ethiofintech.et",
    userPhone: "+251 91 555 6677",
    userRole: "owner",
    businessId: "biz-15",
    businessName: "EthioFintech Solutions",
    assignedAdmin: "Unassigned",
    tags: ["webhook", "api", "leads"],
    messages: [
      {
        id: "msg-9015-1",
        senderId: "user_owner_tariku",
        senderName: "Tariku Wolde",
        senderRole: "owner",
        message:
          "Our CRM webhook endpoint received HTTP 504 gateway timeout when leads were forwarded on Sept 7th. Could you retry the failed webhook delivery queue?",
        createdAt: "2026-08-27T14:20:00.000Z",
      },
    ],
    lastReply: "Tariku Wolde: Our CRM webhook endpoint received HTTP 504 gateway...",
    lastReplyAt: "2026-08-27T14:20:00.000Z",
    city: "Addis Ababa",
    country: "Ethiopia",
    createdAt: "2026-08-27T14:20:00.000Z",
    updatedAt: "2026-08-27T14:20:00.000Z",
  },
  {
    id: "TCK-9016",
    subject: "Business category change from Fast Food to Fine Dining Bistro",
    category: "listing",
    priority: "low",
    status: "closed",
    userId: "user_owner_helen",
    userName: "Helen Teshome",
    userEmail: "helen@oasisbistro.et",
    userPhone: "+251 91 789 0123",
    userRole: "owner",
    businessId: "biz-16",
    businessName: "Oasis Continental Bistro",
    assignedAdmin: "Admin Elena",
    assignedAdminId: "admin_elena",
    tags: ["category", "rebranding", "listing"],
    messages: [
      {
        id: "msg-9016-1",
        senderId: "user_owner_helen",
        senderName: "Helen Teshome",
        senderRole: "owner",
        message:
          "We renovated our premises and shifted our concept to Fine Dining. Could our primary directory tag be updated accordingly?",
        createdAt: "2026-08-26T09:30:00.000Z",
      },
      {
        id: "msg-9016-2",
        senderId: "admin_elena",
        senderName: "Elena Rostova",
        senderRole: "admin",
        message:
          "Listing category updated to 'Fine Dining & Bistro'. Your profile now reflects the updated tags.",
        createdAt: "2026-08-26T10:15:00.000Z",
      },
    ],
    lastReply: "Elena Rostova: Listing category updated to 'Fine Dining & Bistro'...",
    lastReplyAt: "2026-08-26T10:15:00.000Z",
    city: "Addis Ababa",
    country: "Ethiopia",
    createdAt: "2026-08-26T09:30:00.000Z",
    updatedAt: "2026-08-26T10:15:00.000Z",
  },
  {
    id: "TCK-9017",
    subject: "Account email address modification after corporate acquisition",
    category: "account",
    priority: "medium",
    status: "resolved",
    userId: "user_owner_berhanu",
    userName: "Berhanu Assefa",
    userEmail: "berhanu@riftvalleyagro.et",
    userPhone: "+251 92 654 3210",
    userRole: "owner",
    businessId: "biz-17",
    businessName: "Rift Valley Agribusiness",
    assignedAdmin: "Admin Marcus",
    assignedAdminId: "admin_marcus",
    tags: ["email", "acquisition", "account"],
    messages: [
      {
        id: "msg-9017-1",
        senderId: "user_owner_berhanu",
        senderName: "Berhanu Assefa",
        senderRole: "owner",
        message:
          "Our corporate group was acquired by Nile Holdings. We need to transition the primary login email from info@riftvalley.com to admin@nileholdings.et.",
        createdAt: "2026-08-25T11:45:00.000Z",
      },
      {
        id: "msg-9017-2",
        senderId: "admin_marcus",
        senderName: "Marcus Vance",
        senderRole: "admin",
        message:
          "Clerk user credentials updated with verification audit logged. Confirmation email sent to both addresses.",
        createdAt: "2026-08-25T13:20:00.000Z",
      },
    ],
    lastReply: "Marcus Vance: Clerk user credentials updated with verification audit...",
    lastReplyAt: "2026-08-25T13:20:00.000Z",
    city: "Adama",
    country: "Ethiopia",
    createdAt: "2026-08-25T11:45:00.000Z",
    updatedAt: "2026-08-25T13:20:00.000Z",
  },
  {
    id: "TCK-9018",
    subject: "CBE Birr merchant API integration documentation request",
    category: "billing",
    priority: "low",
    status: "closed",
    userId: "user_owner_nati",
    userName: "Natnael Habtu",
    userEmail: "nati@shegertech.et",
    userPhone: "+251 93 123 7890",
    userRole: "owner",
    businessId: "biz-18",
    businessName: "Sheger Tech Hardware",
    assignedAdmin: "Admin Elena",
    assignedAdminId: "admin_elena",
    tags: ["cbe", "api", "docs"],
    messages: [
      {
        id: "msg-9018-1",
        senderId: "user_owner_nati",
        senderName: "Natnael Habtu",
        senderRole: "owner",
        message:
          "Where can we find the CBE Birr payment callback schema documentation for direct customer invoice reconciliation?",
        createdAt: "2026-08-24T16:10:00.000Z",
      },
      {
        id: "msg-9018-2",
        senderId: "admin_elena",
        senderName: "Elena Rostova",
        senderRole: "admin",
        message:
          "The API documentation is accessible at developers.bizfinder.et/payments/cbe-birr. Detailed payload samples are included.",
        createdAt: "2026-08-24T17:00:00.000Z",
      },
    ],
    lastReply: "Elena Rostova: The API documentation is accessible at developers...",
    lastReplyAt: "2026-08-24T17:00:00.000Z",
    city: "Addis Ababa",
    country: "Ethiopia",
    createdAt: "2026-08-24T16:10:00.000Z",
    updatedAt: "2026-08-24T17:00:00.000Z",
  },
  {
    id: "TCK-9019",
    subject: "Holiday seasonal operating hours banner setup assistance",
    category: "general",
    priority: "low",
    status: "resolved",
    userId: "user_owner_dawit",
    userName: "Dawit Solomon",
    userEmail: "dawit@abyssiniacatering.et",
    userPhone: "+251 91 123 4567",
    userRole: "owner",
    businessId: "biz-1",
    businessName: "Abyssinia Gourmet Cafe & Roastery",
    assignedAdmin: "Admin Marcus",
    assignedAdminId: "admin_marcus",
    tags: ["holiday", "hours", "banner"],
    messages: [
      {
        id: "msg-9019-1",
        senderId: "user_owner_dawit",
        senderName: "Dawit Solomon",
        senderRole: "owner",
        message:
          "We will have special opening hours during Ethiopian New Year (Enkutatash). How can we display an urgent banner on our profile?",
        createdAt: "2026-08-23T10:00:00.000Z",
      },
      {
        id: "msg-9019-2",
        senderId: "admin_marcus",
        senderName: "Marcus Vance",
        senderRole: "admin",
        message:
          "You can go to Management → Hours and toggle 'Special Holiday Schedule' which displays a vibrant celebration alert banner on your listing.",
        createdAt: "2026-08-23T11:15:00.000Z",
      },
    ],
    lastReply: "Marcus Vance: You can go to Management → Hours and toggle 'Special...",
    lastReplyAt: "2026-08-23T11:15:00.000Z",
    city: "Addis Ababa",
    country: "Ethiopia",
    createdAt: "2026-08-23T10:00:00.000Z",
    updatedAt: "2026-08-23T11:15:00.000Z",
  },
  {
    id: "TCK-9020",
    subject: "Analytics dashboard visitor unique session count discrepancy",
    category: "technical",
    priority: "medium",
    status: "in_progress",
    userId: "user_owner_yohannes",
    userName: "Yohannes Alemu",
    userEmail: "yohannes@flamingohotel.et",
    userPhone: "+251 91 444 3322",
    userRole: "owner",
    businessId: "biz-20",
    businessName: "Flamingo Grand Hotel & Spa",
    assignedAdmin: "Admin Marcus",
    assignedAdminId: "admin_marcus",
    tags: ["analytics", "telemetry", "views"],
    messages: [
      {
        id: "msg-9020-1",
        senderId: "user_owner_yohannes",
        senderName: "Yohannes Alemu",
        senderRole: "owner",
        message:
          "Our Google Analytics reports 2,400 referral sessions from BizFinder, but our internal analytics tab shows 1,980. Are bot sessions filtered?",
        createdAt: "2026-08-22T13:40:00.000Z",
      },
      {
        id: "msg-9020-2",
        senderId: "admin_marcus",
        senderName: "Marcus Vance",
        senderRole: "admin",
        message:
          "Yes, BizFinder uses IAB/ABC bot filtering to strip crawlers and pre-fetch pings so your metrics reflect genuine human consumer interactions.",
        createdAt: "2026-08-22T15:00:00.000Z",
      },
    ],
    lastReply: "Marcus Vance: Yes, BizFinder uses IAB/ABC bot filtering to strip...",
    lastReplyAt: "2026-08-22T15:00:00.000Z",
    city: "Hawassa",
    country: "Ethiopia",
    createdAt: "2026-08-22T13:40:00.000Z",
    updatedAt: "2026-08-22T15:00:00.000Z",
  },
  // ─── PAGE 2 SEED TICKETS (Items 21 to 32) ──────────────────────────────
  {
    id: "TCK-9021",
    subject: "Chapa Payment Gateway refund request for cancelled banquet",
    category: "billing",
    priority: "high",
    status: "open",
    userId: "user_owner_sara",
    userName: "Sara Alemayehu",
    userEmail: "sara@lucyrestaurant.et",
    userPhone: "+251 92 345 6789",
    userRole: "owner",
    businessId: "biz-2",
    businessName: "Lucy Traditional Dining",
    assignedAdmin: "Admin Marcus",
    assignedAdminId: "admin_marcus",
    tags: ["refund", "chapa", "banquet"],
    messages: [
      {
        id: "msg-9021-1",
        senderId: "user_owner_sara",
        senderName: "Sara Alemayehu",
        senderRole: "owner",
        message:
          "Customer deposit TX-88712 for 15,000 ETB needs partial refund of 5,000 ETB due to group size change. Please authorize Chapa refund reverse.",
        createdAt: "2026-08-21T10:00:00.000Z",
      },
    ],
    lastReply: "Sara Alemayehu: Customer deposit TX-88712 for 15,000 ETB needs...",
    lastReplyAt: "2026-08-21T10:00:00.000Z",
    city: "Addis Ababa",
    country: "Ethiopia",
    createdAt: "2026-08-21T10:00:00.000Z",
    updatedAt: "2026-08-21T10:00:00.000Z",
  },
  {
    id: "TCK-9022",
    subject: "Emergency listing suspension appeal after security audit",
    category: "account",
    priority: "critical",
    status: "in_progress",
    userId: "user_owner_kassahun",
    userName: "Kassahun Tadesse",
    userEmail: "kassahun@baleecotours.et",
    userPhone: "+251 94 567 8901",
    userRole: "owner",
    businessId: "biz-5",
    businessName: "Bale Mountain Eco Tours",
    assignedAdmin: "Alex Rivera (Super Admin)",
    assignedAdminId: "admin_super",
    tags: ["appeal", "suspension", "urgent"],
    messages: [
      {
        id: "msg-9022-1",
        senderId: "user_owner_kassahun",
        senderName: "Kassahun Tadesse",
        senderRole: "owner",
        message:
          "Our listing was flagged by automated bot during a credential stuffing wave. We have reset all staff passwords and enabled Google Authenticator.",
        createdAt: "2026-08-20T16:30:00.000Z",
      },
      {
        id: "msg-9022-2",
        senderId: "admin_super",
        senderName: "Alex Rivera",
        senderRole: "super_admin",
        message:
          "Security logs reviewed. 2FA confirmed active. Listing status restored to Verified Active.",
        createdAt: "2026-08-20T17:15:00.000Z",
      },
    ],
    lastReply: "Alex Rivera: Security logs reviewed. 2FA confirmed active. Listing...",
    lastReplyAt: "2026-08-20T17:15:00.000Z",
    city: "Robe",
    country: "Ethiopia",
    createdAt: "2026-08-20T16:30:00.000Z",
    updatedAt: "2026-08-20T17:15:00.000Z",
  },
  {
    id: "TCK-9023",
    subject: "Bulk CSV product inventory upload formatting guide",
    category: "technical",
    priority: "low",
    status: "resolved",
    userId: "user_owner_samson",
    userName: "Samson Girma",
    userEmail: "samson@habeshapharma.et",
    userPhone: "+251 92 111 2233",
    userRole: "owner",
    businessId: "biz-8",
    businessName: "Habesha Chain Pharmacies",
    assignedAdmin: "Admin Elena",
    assignedAdminId: "admin_elena",
    tags: ["csv", "inventory", "bulk"],
    messages: [
      {
        id: "msg-9023-1",
        senderId: "user_owner_samson",
        senderName: "Samson Girma",
        senderRole: "owner",
        message:
          "We have 450 OTC pharmacy items to upload. Is there a template CSV file with SKU, currency, and stock headers?",
        createdAt: "2026-08-19T09:10:00.000Z",
      },
      {
        id: "msg-9023-2",
        senderId: "admin_elena",
        senderName: "Elena Rostova",
        senderRole: "admin",
        message:
          "Yes! You can download the official CSV template directly from Management → Products Catalog → 'Download CSV Template'.",
        createdAt: "2026-08-19T10:00:00.000Z",
      },
    ],
    lastReply: "Elena Rostova: Yes! You can download the official CSV template...",
    lastReplyAt: "2026-08-19T10:00:00.000Z",
    city: "Addis Ababa",
    country: "Ethiopia",
    createdAt: "2026-08-19T09:10:00.000Z",
    updatedAt: "2026-08-19T10:00:00.000Z",
  },
  {
    id: "TCK-9024",
    subject: "Listing address update following municipal subcity rezoning",
    category: "listing",
    priority: "medium",
    status: "open",
    userId: "user_owner_tamrat",
    userName: "Tamrat Bekele",
    userEmail: "tamrat@redseaimport.et",
    userPhone: "+251 91 888 1234",
    userRole: "owner",
    businessId: "biz-3",
    businessName: "Red Sea Logistics & Forwarding",
    assignedAdmin: "Admin Elena",
    assignedAdminId: "admin_elena",
    tags: ["address", "rezoning", "subcity"],
    messages: [
      {
        id: "msg-9024-1",
        senderId: "user_owner_tamrat",
        senderName: "Tamrat Bekele",
        senderRole: "owner",
        message:
          "Our street was renamed from Bole Medhanialem Street to Africa Avenue West. Can we update without triggering full re-verification?",
        createdAt: "2026-08-18T14:00:00.000Z",
      },
    ],
    lastReply: "Tamrat Bekele: Our street was renamed from Bole Medhanialem Street...",
    lastReplyAt: "2026-08-18T14:00:00.000Z",
    city: "Addis Ababa",
    country: "Ethiopia",
    createdAt: "2026-08-18T14:00:00.000Z",
    updatedAt: "2026-08-18T14:00:00.000Z",
  },
  {
    id: "TCK-9025",
    subject: "Review dispute regarding unverified third-party delivery service",
    category: "dispute",
    priority: "medium",
    status: "waiting_on_customer",
    userId: "user_owner_dawit",
    userName: "Dawit Solomon",
    userEmail: "dawit@abyssiniacatering.et",
    userPhone: "+251 91 123 4567",
    userRole: "owner",
    businessId: "biz-1",
    businessName: "Abyssinia Gourmet Cafe & Roastery",
    assignedAdmin: "Admin Marcus",
    assignedAdminId: "admin_marcus",
    tags: ["review", "delivery", "dispute"],
    messages: [
      {
        id: "msg-9025-1",
        senderId: "user_owner_dawit",
        senderName: "Dawit Solomon",
        senderRole: "owner",
        message:
          "A customer gave 2 stars because their third-party courier arrived cold after 2 hours. We don't operate our own delivery. Can this review be flagged?",
        createdAt: "2026-08-17T11:20:00.000Z",
      },
      {
        id: "msg-9025-2",
        senderId: "admin_marcus",
        senderName: "Marcus Vance",
        senderRole: "admin",
        message:
          "Platform guidelines require reviews to pertain to the merchant's food and service. Please submit the customer's order receipt so we can verify third-party delivery attribution.",
        createdAt: "2026-08-17T12:45:00.000Z",
      },
    ],
    lastReply: "Marcus Vance: Platform guidelines require reviews to pertain to...",
    lastReplyAt: "2026-08-17T12:45:00.000Z",
    city: "Addis Ababa",
    country: "Ethiopia",
    createdAt: "2026-08-17T11:20:00.000Z",
    updatedAt: "2026-08-17T12:45:00.000Z",
  },
  {
    id: "TCK-9026",
    subject: "City Admin permission scope test inquiry for Hawassa region",
    category: "general",
    priority: "low",
    status: "closed",
    userId: "admin_hawassa_lead",
    userName: "Bereket Tilahun",
    userEmail: "bereket@hawassa.bizfinder.et",
    userPhone: "+251 92 888 9900",
    userRole: "admin",
    assignedAdmin: "Alex Rivera (Super Admin)",
    assignedAdminId: "admin_super",
    tags: ["geo", "hawassa", "permissions"],
    messages: [
      {
        id: "msg-9026-1",
        senderId: "admin_hawassa_lead",
        senderName: "Bereket Tilahun",
        senderRole: "admin",
        message:
          "As City Admin for Hawassa, can I approve business verification documents directly without waiting for Country Lead approval?",
        createdAt: "2026-08-16T15:00:00.000Z",
      },
      {
        id: "msg-9026-2",
        senderId: "admin_super",
        senderName: "Alex Rivera",
        senderRole: "super_admin",
        message:
          "Yes Bereket! City Admins possess full jurisdiction to approve and verify listings situated inside their municipality boundaries.",
        createdAt: "2026-08-16T16:20:00.000Z",
      },
    ],
    lastReply: "Alex Rivera: Yes Bereket! City Admins possess full jurisdiction...",
    lastReplyAt: "2026-08-16T16:20:00.000Z",
    city: "Hawassa",
    country: "Ethiopia",
    createdAt: "2026-08-16T15:00:00.000Z",
    updatedAt: "2026-08-16T16:20:00.000Z",
  },
  {
    id: "TCK-9027",
    subject: "Direct customer telephone lead click tracking audit",
    category: "technical",
    priority: "medium",
    status: "resolved",
    userId: "user_owner_selam",
    userName: "Selamawit Desta",
    userEmail: "selam@zenithspa.et",
    userPhone: "+251 91 222 3344",
    userRole: "owner",
    businessId: "biz-10",
    businessName: "Zenith Wellness & Spa",
    assignedAdmin: "Admin Marcus",
    assignedAdminId: "admin_marcus",
    tags: ["call", "tracking", "telemetry"],
    messages: [
      {
        id: "msg-9027-1",
        senderId: "user_owner_selam",
        senderName: "Selamawit Desta",
        senderRole: "owner",
        message:
          "We saw 48 'Call Business' clicks yesterday. Does BizFinder deduplicate multiple taps from the same device within 1 hour?",
        createdAt: "2026-08-15T09:40:00.000Z",
      },
      {
        id: "msg-9027-2",
        senderId: "admin_marcus",
        senderName: "Marcus Vance",
        senderRole: "admin",
        message:
          "Yes, identical device fingerprinted taps are deduplicated within a rolling 30-minute window to ensure accurate conversion metrics.",
        createdAt: "2026-08-15T11:00:00.000Z",
      },
    ],
    lastReply: "Marcus Vance: Yes, identical device fingerprinted taps are deduplicated...",
    lastReplyAt: "2026-08-15T11:00:00.000Z",
    city: "Addis Ababa",
    country: "Ethiopia",
    createdAt: "2026-08-15T09:40:00.000Z",
    updatedAt: "2026-08-15T11:00:00.000Z",
  },
  {
    id: "TCK-9028",
    subject: "Arabic language localized business profile description",
    category: "listing",
    priority: "low",
    status: "open",
    userId: "user_owner_ali",
    userName: "Ali Al-Mansoor",
    userEmail: "ali@redseadiving.et",
    userPhone: "+251 91 432 1098",
    userRole: "owner",
    businessId: "biz-28",
    businessName: "Red Sea Marine Diving Center",
    assignedAdmin: "Unassigned",
    tags: ["multilingual", "arabic", "locale"],
    messages: [
      {
        id: "msg-9028-1",
        senderId: "user_owner_ali",
        senderName: "Ali Al-Mansoor",
        senderRole: "owner",
        message:
          "Can we provide multilingual Arabic and Amharic descriptions for middle eastern tourists visiting the Red Sea route?",
        createdAt: "2026-08-14T12:00:00.000Z",
      },
    ],
    lastReply: "Ali Al-Mansoor: Can we provide multilingual Arabic and Amharic...",
    lastReplyAt: "2026-08-14T12:00:00.000Z",
    city: "Semera",
    country: "Ethiopia",
    createdAt: "2026-08-14T12:00:00.000Z",
    updatedAt: "2026-08-14T12:00:00.000Z",
  },
  {
    id: "TCK-9029",
    subject: "Bank transfer verification receipt upload for annual boost",
    category: "billing",
    priority: "high",
    status: "in_progress",
    userId: "user_owner_tariku",
    userName: "Tariku Wolde",
    userEmail: "tariku@ethiofintech.et",
    userPhone: "+251 91 555 6677",
    userRole: "owner",
    businessId: "biz-15",
    businessName: "EthioFintech Solutions",
    assignedAdmin: "Admin Marcus",
    assignedAdminId: "admin_marcus",
    tags: ["bank", "cbe", "receipt"],
    messages: [
      {
        id: "msg-9029-1",
        senderId: "user_owner_tariku",
        senderName: "Tariku Wolde",
        senderRole: "owner",
        message:
          "We transferred 50,000 ETB via Commercial Bank of Ethiopia branch transfer for our quarterly boost. Slip number CBE-981240. Please confirm activation.",
        createdAt: "2026-08-13T10:30:00.000Z",
      },
      {
        id: "msg-9029-2",
        senderId: "admin_marcus",
        senderName: "Marcus Vance",
        senderRole: "admin",
        message:
          "Finance department is verifying the deposit with our bank branch. Expected confirmation within 2 business hours.",
        createdAt: "2026-08-13T11:45:00.000Z",
      },
    ],
    lastReply: "Marcus Vance: Finance department is verifying the deposit with our...",
    lastReplyAt: "2026-08-13T11:45:00.000Z",
    city: "Addis Ababa",
    country: "Ethiopia",
    createdAt: "2026-08-13T10:30:00.000Z",
    updatedAt: "2026-08-13T11:45:00.000Z",
  },
  {
    id: "TCK-9030",
    subject: "Google Analytics 4 Measurement ID tracking tag integration",
    category: "technical",
    priority: "low",
    status: "closed",
    userId: "user_owner_helen",
    userName: "Helen Teshome",
    userEmail: "helen@oasisbistro.et",
    userPhone: "+251 91 789 0123",
    userRole: "owner",
    businessId: "biz-16",
    businessName: "Oasis Continental Bistro",
    assignedAdmin: "Admin Elena",
    assignedAdminId: "admin_elena",
    tags: ["ga4", "tracking", "seo"],
    messages: [
      {
        id: "msg-9030-1",
        senderId: "user_owner_helen",
        senderName: "Helen Teshome",
        senderRole: "owner",
        message:
          "Where can we input our custom G-XXXXXXXXXX GA4 ID so visits to our listing sync directly to our corporate analytics property?",
        createdAt: "2026-08-12T14:15:00.000Z",
      },
      {
        id: "msg-9030-2",
        senderId: "admin_elena",
        senderName: "Elena Rostova",
        senderRole: "admin",
        message:
          "Navigate to Management → Business Information → 'Custom SEO & Tracking'. Paste your GA4 ID there and click Save.",
        createdAt: "2026-08-12T15:00:00.000Z",
      },
    ],
    lastReply: "Elena Rostova: Navigate to Management → Business Information →...",
    lastReplyAt: "2026-08-12T15:00:00.000Z",
    city: "Addis Ababa",
    country: "Ethiopia",
    createdAt: "2026-08-12T14:15:00.000Z",
    updatedAt: "2026-08-12T15:00:00.000Z",
  },
];
